#!/bin/bash
#########################################################################################
#  Genesis CLI (Genesis Command Line Interface)
#---------------------------------------------------------------------------------------
#   Goals:
#     1.- Provide CLI interface for Genesis System, used for testing purposes
#     2.- Menu interactive user interface without dependencies (fully bash written)
#           Every command of the CLI can be used through the menu, instead command line
#---------------------------------------------------------------------------------------
# Author: Cesar Delgado
# Date: 17-September-2022
# Update: 02-Jul-2026
########################################################################################

#----------------------------
# ECHO COLORS TABLE
#----------------------------
#Black        0;30     Dark Gray     1;30
#Red          0;31     Light Red     1;31
#Green        0;32     Light Green   1;32
#Brown/Orange 0;33     Yellow        1;33
#Blue         0;34     Light Blue    1;34
#Purple       0;35     Light Purple  1;35
#Cyan         0;36     Light Cyan    1;36
#Light Gray   0;37     White         1;37

#--------------------------------
#  GENERAL PARAMETERS
#--------------------------------

# 1.- Constant Values
#--------------------
LOCALE="en_US.UTF-8"
REEMPLAZA_LINEA_CNF="Yes"
ERROR="1"
OK="0"
NC="0"
BLACK="1" ; RED="2"    ; BROWN="7"   ; BLUE="6"  ; PURPLE="5" ; CYAN="13"; SILVER="9"
GRAY="8"  ; ORANGE="4" ; YELLOW="10" ; SKY="11"  ; LILA="12"  ; SEA="3"; WHITE="14"
COLOR=( '\033[0m' \
        '\033[0;30m'  '\033[0;31m' '\033[0;32m' '\033[0;33m' '\033[0;34m' '\033[0;35m' '\033[0;36m' '\033[0;37m' \
        '\033[1;90m'  '\033[1;91m' '\033[1;92m' '\033[1;93m' '\033[1;94m' '\033[1;95m' '\033[1;96m' '\033[1;97m' \
      )

# 2.- Default Values
#--------------------
# 2.1.- Genesis Paths
GENESIS_VIRTUAL_ENVIRONMENT="/opt/stack/bifrost/bin/activate"
GENESIS_WORKING_PATH=$(dirname "$(readlink -f "$0")")
GENESIS_PROJECT_ANSIBLE_CFG="${GENESIS_WORKING_PATH}/ansible.cfg"
GENESIS_HOSTS_WORKING_PATH="${GENESIS_WORKING_PATH}/hosts"
GENESIS_HOSTS_TARGET_FILE="${GENESIS_HOSTS_WORKING_PATH}/target/group_vars/target"
GENESIS_BIFROST_WORKING_PATH="${GENESIS_WORKING_PATH}/roles/genesis.bifrost/genesis.bifrost"
IRONIC_BIFROST_DYNAMIC_INVENTORY="${GENESIS_BIFROST_WORKING_PATH}/bifrost/inventory.py"
IRONIC_CLOUD="bifrost"
IRONIC_NODES_FILE='host_vars/baremetal.yml'
IRONIC_BAREMETAL_NODES=$(cat ${GENESIS_PROJECT_ANSIBLE_CFG} | grep 'inventory=' | awk -F/ '{print $NF}' | tr -d '"' | tr -d ' ' )
GENESIS_BIFROST_INVENTORY_SOURCE="${GENESIS_HOSTS_WORKING_PATH}/${IRONIC_BAREMETAL_NODES}/${IRONIC_NODES_FILE}"
GENESIS_ANSIBLE_INVENTORY_SOURCE="${GENESIS_HOSTS_WORKING_PATH}/${IRONIC_BAREMETAL_NODES}/inventory"
GENESIS_TARGET_INVENTORY_SOURCE="${GENESIS_HOSTS_WORKING_PATH}/target/inventory"

# 2.2.- Installation OPTIONS
DEBUG_ANSIBLE_FLAGS='-vvv '
RUN_BACKGROUND="no"
BAREMETAL_ROOT_PASSWORD="cesar" # Automatic ssh-copy-id

# 2.3.- Genesis Playbooks
REFRESH="0" ; CREATE="1"   ; INIT="2"    ; SETUP="3" ; DEPLOY="4" ; PROVISION="5"  
SSH_MAP="6" ; GRAPHICS="7" ; NETWORK="8" ; NTP="9"   ; GATHER="10"
GENESIS_PLAYBOOKS=( \
	 "${GENESIS_WORKING_PATH}/playbooks/genesis.yml" \
	 "${GENESIS_WORKING_PATH}/playbooks/genesis.yml" \
	 "${GENESIS_WORKING_PATH}/playbooks/genesis.yml" \
	 "${GENESIS_WORKING_PATH}/playbooks/baremetal.yml" \
     "${GENESIS_WORKING_PATH}/playbooks/baremetal.yml" \
	 "${GENESIS_WORKING_PATH}/playbooks/baremetal.yml" \
	 "${GENESIS_WORKING_PATH}/playbooks/install_ssh_trustmap" \
	 "${GENESIS_WORKING_PATH}/playbooks/install_graphics.yaml" \
	 "${GENESIS_WORKING_PATH}/playbooks/install_network.yaml" \
	 "${GENESIS_WORKING_PATH}/playbooks/install_ntp.yaml" \
	 "${GENESIS_WORKING_PATH}/playbooks/gatheringStringConfigurations.yaml" \
)
GENESIS_PLAYBOOKS_HEADER=( \
        "${COLOR[$ORANGE]}[IRONIC]   - REFRESH : Prepare Genesis Machine (G1_refresh.yml)${COLOR[$NC]}" \
        "${COLOR[$ORANGE]}[IRONIC]   - CREATE  : install Ironic in Genesis Node (G2_create.yml)${COLOR[$NC]}" \
        "${COLOR[$ORANGE]}[IRONIC]   - INIT    : load operating system installation images to Ironic (G3_init.yml)${COLOR[$NC]}" \
        "${COLOR[$SEA]}[BAREMETAL] - SETUP   : enroll inventory in Ironic (B4_setup.yml)${COLOR[$NC]}" \
        "${COLOR[$SEA]}[BAREMETAL] - DEPLOY    : unattended installation (B5_deploy.yml)${COLOR[$NC]}" \
        "${COLOR[$SEA]}[BAREMETAL] - PROVISIONING: node drivers and services installation (B6_provision.yml)${COLOR[$NC]}" \
        "${COLOR[$NC]}[BAREMETAL] - TEST MENU: isolated functionality provisioning ${COLOR[$NC]}" \
        "${COLOR[$NC]}[BAREMETAL] - GRAPHICS    : Install propietary 3er party driver${COLOR[$NC]}" \
        "${COLOR[$NC]}[BAREMETAL] - NETWORK     : Install network configurations${COLOR[$NC]}" \
        "${COLOR[$NC]}[BAREMETAL] - NTP         : Deploy NTP configuration${COLOR[$NC]}" \
        "${COLOR[$NC]}[BAREMETAL] - GATHER BAREMETAL CONFIGURATIONS  : Fetch relevant configuration files from String${COLOR[$NC]}" \
)


# 2.3.- Online Installation
DHCP_NIC=0; DHCP_IP=1 ; DHCP_POOL_START=2 ; DHCP_POOL_END=3
network_interface=$( cat "${GENESIS_HOSTS_TARGET_FILE}" | grep 'network_interface:' | head -1 | awk -F: '{print $NF}'  | tr -d '"' | tr -d ' '  )
dhcp_address=$( cat "${GENESIS_HOSTS_TARGET_FILE}" | grep 'dhcp_address:' | head -1 | awk -F: '{print $NF}'  | tr -d '"' | tr -d ' '  )
dhcp_pool_start=$( cat "${GENESIS_HOSTS_TARGET_FILE}" | grep 'dhcp_pool_start:' | head -1 | awk -F: '{print $NF}' | tr -d '"' | tr -d ' ' )
dhcp_pool_end=$( cat "${GENESIS_HOSTS_TARGET_FILE}" | grep 'dhcp_pool_end:' | head -1 | awk -F: '{print $NF}' | tr -d '"' | tr -d ' ' )
PXE=( "${network_interface}" "${dhcp_address}" "${dhcp_pool_start}" "${dhcp_pool_end}" )      

# 2.3.- Dependencies
PIP=0; SCRIPTS=1; INSTALLER=2
DEPENDENCIES=( 'collections/requirements.yml' \
               'roles/requirements.yml' \
               '#' \
			   '#' \
              )

DEPENDENCIES_INSTALLER=( 'ansible-galaxy collection install --force -r ' \
	                     'ansible-galaxy role install --force -r ' \
						 'sed -i "/cdglab.duckdns.org/d" /etc/hosts' \
                        )

########################################################################################
# MODULE 1 => MENU DEFINITION
########################################################################################

#========================================================
#   Function: defineMenu
#--------------------------------------------------------
#   Menu properties to deploy
#========================================================
function defineMenu() {

	#---------------------
	#  LOCAL ENVIRONMENT
	#---------------------
        if [ ! -n "${MENU}" ] ; then MENU="0" ; fi

	#---------------------
	# MENU PROPERTIES
	#---------------------
	case "${MENU}" in
	    0|"MAIN        : back to main menu")
		      MENU_TEXT="INSTRUCTIONS: \n A.- Baremetal Nodes Installation Cycle: SETUP -> DEPLOY -> PROVISION \n B.- Genesis Node  Installation Cycle: REFRESH -> CREATE -> INIT \n C.- To Run Ironic Commands: . $HOME/env.sh ; baremetal node list \n ___________\n STATE TRANSITIONS MENU \n___________"
		      RUTA_OPCIONES=( "MAIN        : back to main menu" \
                              "${COLOR[$ORANGE]}[IRONIC]   - REFRESH : Prepare Genesis Machine (G1_refresh.yml)${COLOR[$NC]}" \
                              "${COLOR[$ORANGE]}[IRONIC]   - CREATE  : install Ironic in Genesis Node (G2_create.yml)${COLOR[$NC]}" \
                              "${COLOR[$ORANGE]}[IRONIC]   - INIT    : load operating system installation images to Ironic (G3_init.yml)${COLOR[$NC]}" \
                              "${COLOR[$SEA]}[BAREMETAL] - SETUP   : enroll inventory in Ironic (B4_setup.yml)${COLOR[$NC]}" \
                              "${COLOR[$SEA]}[BAREMETAL] - DEPLOY    : unattended installation (B5_deploy.yml)${COLOR[$NC]}" \
                              "${COLOR[$SILVER]}[BAREMETAL] - ANSIBLE (pre-ready): Ansible Initial Setup${COLOR[$NC]}" \
                              "${COLOR[$SEA]}[BAREMETAL] - PROVISIONING: node drivers and services installation (B6_provision.yml)${COLOR[$NC]}" \
                              "${COLOR[$NC]}[BAREMETAL] - TEST MENU: isolated functionality provisioning ${COLOR[$NC]}" \
                              "${COLOR[$NC]}[BAREMETAL] - TROUBLESHOOTING MENU: tools to validate installations ${COLOR[$NC]}" \
                              "${COLOR[$NC]}[BAREMETAL] - SOFT-CONFIGURATIONS MENU: tools to help creating soft-configurations ${COLOR[$NC]}" \
                              "Exit" \
		                   )
	          PARAMETRO=(     "MENU" )
              VALOR_DEFECTO=( "0"    )
	          SOLICITA_PARAMETRO=("======> Please, Choose Action  [${VALOR_DEFECTO[0]}]" )
	          unset MENU
              ;;

       1|"${GENESIS_PLAYBOOKS_HEADER[${REFRESH}]}")
	          if [ ! -n "${LOG_FILE}"    ] ; then local LOG_FILE="${HOME}/refresh.log"; fi
			  if [ ! -n "${RUN_BACKGROUND}" ] ; then local RUN_BACKGROUND="No" ; fi			  
		      MENU_TEXT="(1)___________ ${GENESIS_PLAYBOOKS_HEADER[${REFRESH}]}"
	          PARAMETRO=(     "RUN_BACKGROUND" "LOG_FILE" )
              VALOR_DEFECTO=( "No"  "${LOG_FILE}")	  
	          SOLICITA_PARAMETRO=("-----> Run Ansible in Background [${VALOR_DEFECTO[0]}]:" \
			                      "-----> Log File                  [${VALOR_DEFECTO[1]}]:" \
                                 )
              RETURNING_MENU="0"
              RUN_ACTION="1"
              unset RUN_BACKGROUND LOG_FILE
              ;;

	   2|"${GENESIS_PLAYBOOKS_HEADER[${CREATE}]}")
	         if [ ! -n "${LOG_FILE}"    ] ; then local LOG_FILE="${HOME}/create.log" ; fi
			 if [ ! -n "${RUN_BACKGROUND}" ] ; then local RUN_BACKGROUND="No" ; fi			 
		     MENU_TEXT="(2)___________ ${GENESIS_PLAYBOOKS_HEADER[${CREATE}]}"
	         PARAMETRO=(    "network_interface" "dhcp_address" "dhcp_pool_start" "dhcp_pool_end" "RUN_BACKGROUND" "LOG_FILE"   )
             VALOR_DEFECTO=(  "${PXE[$DHCP_NIC]}" \
			                  "${PXE[$DHCP_IP]}" \
							  "${PXE[$DHCP_POOL_START]}" \
							  "${PXE[$DHCP_POOL_END]}" \
							  "No" \
							  "${LOG_FILE}" \
							  )
	         CNF_REEMPLAZO=( "${GENESIS_HOSTS_TARGET_FILE}" \
			                  "${GENESIS_HOSTS_TARGET_FILE}" \
							  "${GENESIS_HOSTS_TARGET_FILE}" \
							  "${GENESIS_HOSTS_TARGET_FILE}" \
							  '' \
							  )
			 CNF_SEPARADOR_CAMPO=( ': ' ': ' ': ' ': ' '' )
			 SOLICITA_PARAMETRO=("-----> DHCP NIC            [${VALOR_DEFECTO[0]}]:" \
			                     "-----> DHCP IP             [${VALOR_DEFECTO[1]}]:" \
			                     "-----> DHCP POOL START IP  [${VALOR_DEFECTO[2]}]:" \
			                     "-----> DHCP POOL END IP    [${VALOR_DEFECTO[3]}]:" \
								 "-----> Run Ansible in Background [${VALOR_DEFECTO[4]}]:" \
								 "-----> Log File            [${VALOR_DEFECTO[5]}]:" \
			                     )
             RETURNING_MENU="0"
             RUN_ACTION="2"
             unset network_interface  dhcp_address dhcp_pool_start  dhcp_pool_end RUN_BACKGROUND LOG_FILE
             ;;

	   3|"${GENESIS_PLAYBOOKS_HEADER[${INIT}]}")
	         if [ ! -n "${LOG_FILE}"    ] ; then local LOG_FILE="${HOME}/init.log" ; fi
			 if [ ! -n "${RUN_BACKGROUND}" ] ; then local RUN_BACKGROUND="No" ; fi
		     MENU_TEXT="(3)___________ ${GENESIS_PLAYBOOKS_HEADER[${INIT}]}"
	         PARAMETRO=(     "RUN_BACKGROUND" "LOG_FILE"    )
             VALOR_DEFECTO=( "No" "${LOG_FILE}" )
	         SOLICITA_PARAMETRO=("-----> Run Ansible in Background [${VALOR_DEFECTO[0]}]:" \
			                     "-----> Log File    [${VALOR_DEFECTO[1]}]:" \
                                )
             RETURNING_MENU="0"
             RUN_ACTION="3"
             unset RUN_BACKGROUND LOG_FILE
		     ;;

	   4|"${GENESIS_PLAYBOOKS_HEADER[${SETUP}]}")
	         if [ ! -n "${LOG_FILE}" ] ; then local LOG_FILE="${HOME}/setup.log"  ; fi
	         MENU_TEXT="(4)___________ ${GENESIS_PLAYBOOKS_HEADER[${SETUP}]}"
			 
             RUTA_OPCIONES=( "${GENESIS_HOSTS_WORKING_PATH}" )
	         PARAMETRO=(     "IRONIC_BAREMETAL_NODES"    "LOG_FILE"   )
             VALOR_DEFECTO=( "0"  "${LOG_FILE}" )
	         SOLICITA_PARAMETRO=("-----> Baremetal Nodes Descripion [${VALOR_DEFECTO[0]}]:" \
	                             "-----> Log File                   [${VALOR_DEFECTO[1]}]:" \
                                    )
             MENU_SKIP_PATHS="1"
			 RETURNING_MENU="0"
             RUN_ACTION="4"
             unset IRONIC_BAREMETAL_NODES LOG_FILE
		     ;;

       5|"${GENESIS_PLAYBOOKS_HEADER[${DEPLOY}]}")
	         if [ ! -n "${TARGET}" ]    ; then local TARGET=''                       ; fi
	         if [ ! -n "${LOG_FILE}" ] ; then local LOG_FILE="${HOME}/deploy.log"  ; fi
	         MENU_TEXT="(5)___________ ${GENESIS_PLAYBOOKS_HEADER[${DEPLOY}]}"
	         PARAMETRO=(  "TARGET"    "LOG_FILE" )
             VALOR_DEFECTO=(  "${TARGET}" "${LOG_FILE}"   )
	         SOLICITA_PARAMETRO=("-----> Target Machines                 [${VALOR_DEFECTO[0]}]:" \
	                             "-----> Log File                        [${VALOR_DEFECTO[1]}]:" \
                                    )
             RETURNING_MENU="0"
             RUN_ACTION="5"
             unset TARGET LOG_FILE
	         ;;

       6|"${COLOR[$SILVER]}[BAREMETAL] - ANSIBLE (pre-ready): Ansible Initial Setup${COLOR[$NC]}")
		     MENU_TEXT="(6)___________ [BAREMETAL] - ANSIBLE     : Ansible Initial Setup"
	         #PARAMETRO=(     "NODE_LIST" )
	         #EXT_OPCIONES=( ".list"      )
             #VALOR_DEFECTO=( "0"         )
	         #SOLICITA_PARAMETRO=("-----> List of Nodes full Path  [${VALOR_DEFECTO[0]}]:" \
             #                )
             RETURNING_MENU="0"
             RUN_ACTION="6"
             unset NODE_LIST
             ;;


	     7|"${GENESIS_PLAYBOOKS_HEADER[${PROVISION}]}")
	          if [ ! -n "${TARGET}" ]    ; then local TARGET=''                    ; fi
	          if [ ! -n "${LOG_FILE}" ] ; then local LOG_FILE="${HOME}/provision.log"  ; fi
	          MENU_TEXT="(7)___________ ${GENESIS_PLAYBOOKS_HEADER[${PROVISION}]}"
	          PARAMETRO=(     "TARGET"     "LOG_FILE")
              VALOR_DEFECTO=(  "${TARGET}"  "${LOG_FILE}" )
	          SOLICITA_PARAMETRO=("-----> Target Machines                 [${VALOR_DEFECTO[0]}]:" \
	                              "-----> Log File                        [${VALOR_DEFECTO[1]}]:" \
                             )
              RETURNING_MENU="0"
              RUN_ACTION="7"
              unset INVENTORY TARGET LOG_FILE
		  ;;

	    9|"${COLOR[$NC]}[BAREMETAL] - TROUBLESHOOTING MENU: tools to validate installations ${COLOR[$NC]}")
		      MENU_TEXT="TROUBLESHOOTING TOOLS: ___________"
		      RUTA_OPCIONES=( "MAIN        : back to main menu" \
                              "${COLOR[$NC]}[BAREMETAL] - TROUBLESHOOTING MENU: tools to validate installations ${COLOR[$NC]}" \
                              "${GENESIS_PLAYBOOKS_HEADER[${SSH_MAP}]}" \
                              "${GENESIS_PLAYBOOKS_HEADER[${GRAPHICS}]}" \
                              "${GENESIS_PLAYBOOKS_HEADER[${NETWORK}]}" \
                              "${GENESIS_PLAYBOOKS_HEADER[${NTP}]}" \
                              "Exit" \
		                   )
	          PARAMETRO=(     "MENU" )
              VALOR_DEFECTO=( "${COLOR[$NC]}[BAREMETAL] - TROUBLESHOOTING MENU: tools to validate installations ${COLOR[$NC]}"    )
	          SOLICITA_PARAMETRO=("======> Please, Choose Action  [${VALOR_DEFECTO[0]}]" )
	          unset MENU
              ;;


       10|"${COLOR[$NC]}[BAREMETAL] - SOFT-CONFIGURATIONS MENU: tools to help creating soft-configurations ${COLOR[$NC]}")
		      MENU_TEXT="SOFT-CONFIGURATIONS TOOLS: ___________"
		      RUTA_OPCIONES=( "MAIN        : back to main menu" \
                              "${COLOR[$NC]}[BAREMETAL] - SOFT-CONFIGURATIONS MENU: tools to help creating soft-configurations ${COLOR[$NC]}" \
                              "${GENESIS_PLAYBOOKS_HEADER[${GATHER}]}" \
                              "Exit" \
		                   )
	          PARAMETRO=(     "MENU" )
              VALOR_DEFECTO=( "${COLOR[$NC]}[BAREMETAL] - SOFT-CONFIGURATIONS MENU: tools to help creating soft-configurations ${COLOR[$NC]}"    )
	          SOLICITA_PARAMETRO=( "======> Please, Choose Action  [${VALOR_DEFECTO[0]}]" )
	          unset MENU
              ;;

        11|"Exit")
	         echo "Removing Temporal Files... rm -f ${OUT_TMP} 2> /dev/null"
	         rm -f "${OUT_TMP}"
             echo "Removing Temporal Files... rm -f ${TMP_FILE}"
             rm -f "${TMP_FILE}" 2> /dev/null
	         echo -e "${COLOR[$SILVER]}*********************************************************************************${COLOR[$NC]}"
	         echo -e "${COLOR[$SILVER]}     Thank you for using Genesis System... hoping you enjoy the experience !!!!  ${COLOR[$NC]}"
	         echo -e "${COLOR[$SILVER]}*********************************************************************************${COLOR[$NC]}"
             exit 0
             ;;
			 
        12|"${GENESIS_PLAYBOOKS_HEADER[${LDAP}]}")
	          if [ ! -n "${LDAP_TYPE}" ] ; then local LDAP_TYPE="idm"    ; fi	  
	          if [ ! -n "${LDAP_GROUP_MACHINES}" ] ; then local LDAP_GROUP_MACHINES="iss_group" ; fi
	          if [ ! -n "${LDAP_DATA}" ] ; then local LDAP_DATA="pv3"    ; fi				  
	          if [ ! -n "${TAGS}"      ] ; then local TAGS="install,policies,user,group,role,privilege" ; fi
			  if [ ! -n "${VAULT}"     ] ; then local VAULT="goteras"    ; fi			  
	          if [ ! -n "${INVENTORY}" ] ; then local INVENTORY="${genesis_DEFAULT_INVENTORY}" ; fi
	          if [ ! -n "${TARGET}"    ] ; then local TARGET=""                   ; fi
	          if [ ! -n "${CALL_LOG}"  ] ; then local CALL_LOG="${HOME}/ldap.log" ; fi
		      MENU_TEXT="(12)___________ ${GENESIS_PLAYBOOKS_HEADER[${LDAP}]}"
	          PARAMETRO=(     "LDAP_TYPE" "LDAP_GROUP_MACHINES" "LDAP_DATA"  "TAGS" "VAULT" "INVENTORY"      "TARGET"     "CALL_LOG" )
              VALOR_DEFECTO=( "${LDAP_TYPE}" "${LDAP_GROUP_MACHINES}" "${LDAP_DATA}" "${TAGS}" "${VAULT}" "${INVENTORY}"   "${TARGET}"  "${CALL_LOG}" )
	          SOLICITA_PARAMETRO=("-----> LDAP Service                    [${VALOR_DEFECTO[0]}]:" \
			                      "-----> Target machine's group          [${VALOR_DEFECTO[1]}]:" \
			                      "-----> LDAP Data Model to Feed         [${VALOR_DEFECTO[2]}]:" \
                                  "-----> Ldap Actions                    [${VALOR_DEFECTO[3]}]:" \
                                  "-----> Vault Password                  [${VALOR_DEFECTO[4]}]:" \
			                      "-----> Machine's Inventory full path   [${VALOR_DEFECTO[5]}]:" \
	                              "-----> Target Machines                 [${VALOR_DEFECTO[6]}]:" \
	                              "-----> Log File                        [${VALOR_DEFECTO[7]}]:" \
                                     )
              RETURNING_MENU="8"
              RUN_ACTION="12"
              unset LDAP_TYPE LDAP_GROUP_MACHINES LDAP_DATA TAGS VAULT INVENTORY TARGET CALL_LOG 
		      ;;

        13|"${GENESIS_PLAYBOOKS_HEADER[${TESTING}]}")
              if [ ! -n "${GROUP_MACHINES}" ] ; then local GROUP_MACHINES="iss_group" ; fi
	          if [ ! -n "${INVENTORY}" ] ; then local INVENTORY="${genesis_DEFAULT_INVENTORY}" ; fi
	          if [ ! -n "${TARGET}" ]    ; then local TARGET=""                   ; fi
	          if [ ! -n "${CALL_LOG}" ]   ; then local CALL_LOG="${HOME}/rabbitmq.log" ; fi
		      MENU_TEXT="(13)___________ ${GENESIS_PLAYBOOKS_HEADER[${TESTING}]}"
	          PARAMETRO=(     "GROUP_MACHINES" "INVENTORY"      "TARGET"     "CALL_LOG" )
              VALOR_DEFECTO=( "${GROUP_MACHINES}" "${INVENTORY}"   "${TARGET}"  "${CALL_LOG}" )
	          SOLICITA_PARAMETRO=("-----> Target Machine's Group          [${VALOR_DEFECTO[0]}]:" \
			                      "-----> Machine's Inventory full path   [${VALOR_DEFECTO[1]}]:" \
	                              "-----> Target Machines                 [${VALOR_DEFECTO[2]}]:" \
	                              "-----> Log File                        [${VALOR_DEFECTO[3]}]:" \
                                     )
              RETURNING_MENU="8"
              RUN_ACTION="13"
              unset GROUP_MACHINES INVENTORY TARGET CALL_LOG
		      ;;			  
			 

        14|"${GENESIS_PLAYBOOKS_HEADER[${SSH_MAP}]}")
	          if [ ! -n "${INVENTORY}" ] ; then local INVENTORY="${genesis_DEFAULT_INVENTORY}" ; fi
	          if [ ! -n "${TARGET}" ]    ; then local TARGET=""                   ; fi
	          if [ ! -n "${CALL_LOG}" ]   ; then local CALL_LOG="${HOME}/ssh.log" ; fi
		      MENU_TEXT="(14)___________ ${GENESIS_PLAYBOOKS_HEADER[${SSH_MAP}]}"
	          PARAMETRO=(     "INVENTORY"      "TARGET"     "CALL_LOG" )
              VALOR_DEFECTO=( "${INVENTORY}"   "${TARGET}"  "${CALL_LOG}" )
	          SOLICITA_PARAMETRO=("-----> Machine's Inventory full path   [${VALOR_DEFECTO[0]}]:" \
	                              "-----> Target Machines                 [${VALOR_DEFECTO[1]}]:" \
	                              "-----> Log File                        [${VALOR_DEFECTO[2]}]:" \
                                     )
              RETURNING_MENU="8"
              RUN_ACTION="14"
              unset INVENTORY TARGET CALL_LOG
		      ;;

        15|"${GENESIS_PLAYBOOKS_HEADER[${GRAPHICS}]}")
	          if [ ! -n "${INVENTORY}" ]    ; then local INVENTORY="${genesis_DEFAULT_INVENTORY}" ; fi
	          if [ ! -n "${TARGET}" ]       ; then local TARGET=""                       ; fi
	          if [ ! -n "${CALL_LOG}" ]     ; then local CALL_LOG="${HOME}/graphics.log" ; fi
		      MENU_TEXT="(15)___________ ${GENESIS_PLAYBOOKS_HEADER[${GRAPHICS}]}"
	          PARAMETRO=(     "INVENTORY"      "TARGET"     "CALL_LOG" )
              VALOR_DEFECTO=( "${INVENTORY}"   "${TARGET}"  "${CALL_LOG}" )
	          SOLICITA_PARAMETRO=("-----> Machine's Inventory full path   [${VALOR_DEFECTO[0]}]:" \
	                              "-----> Target Machines                 [${VALOR_DEFECTO[1]}]:" \
	                              "-----> Log File                        [${VALOR_DEFECTO[2]}]:" \
                                     )
              RETURNING_MENU="8"
              RUN_ACTION="15"
              unset INVENTORY TARGET CALL_LOG
              ;;

       16|"${GENESIS_PLAYBOOKS_HEADER[${NETWORK}]}")
	          if [ ! -n "${INVENTORY}" ]    ; then local INVENTORY="${genesis_DEFAULT_INVENTORY}" ; fi
	          if [ ! -n "${TARGET}" ]       ; then local TARGET=""                       ; fi
	          if [ ! -n "${CALL_LOG}" ]      ; then local CALL_LOG="${HOME}/network.log" ; fi
 		      MENU_TEXT="(16)___________ ${GENESIS_PLAYBOOKS_HEADER[${NETWORK}]}"
	          PARAMETRO=(     "INVENTORY"      "TARGET"     "CALL_LOG" )
              VALOR_DEFECTO=( "${INVENTORY}"   "${TARGET}"  "${CALL_LOG}" )
	          SOLICITA_PARAMETRO=("-----> Machine's Inventory full path   [${VALOR_DEFECTO[0]}]:" \
	                              "-----> Target Machines                 [${VALOR_DEFECTO[1]}]:" \
	                              "-----> Log File                        [${VALOR_DEFECTO[2]}]:" \
                                    )
              RETURNING_MENU="8"
              RUN_ACTION="16"
              unset INVENTORY TARGET CALL_LOG
              ;;

       17|"${GENESIS_PLAYBOOKS_HEADER[${NTP}]}")
	          if [ ! -n "${INVENTORY}" ]    ; then local INVENTORY="${genesis_DEFAULT_INVENTORY}" ; fi
	          if [ ! -n "${TARGET}" ]       ; then local TARGET=""                       ; fi
	          if [ ! -n "${CALL_LOG}" ]      ; then local CALL_LOG="${HOME}/ntp.log"     ; fi
		      MENU_TEXT="(17)___________ ${GENESIS_PLAYBOOKS_HEADER[${NTP}]}"
	          PARAMETRO=(     "INVENTORY"      "TARGET"     "CALL_LOG" )
              VALOR_DEFECTO=( "${INVENTORY}"   "${TARGET}"  "${CALL_LOG}" )
	          SOLICITA_PARAMETRO=("-----> Machine's Inventory full path   [${VALOR_DEFECTO[0]}]:" \
	                              "-----> Target Machines                 [${VALOR_DEFECTO[1]}]:" \
	                              "-----> Log File                        [${VALOR_DEFECTO[2]}]:" \
                                     )
              RETURNING_MENU="8"
              RUN_ACTION="17"
              unset INVENTORY TARGET CALL_LOG
              ;;

       22|"${GENESIS_PLAYBOOKS_HEADER[${GATHER}]}")
	          if [ ! -n "${GATHERING_FOLDER}" ]   ; then local GATHERING_FOLDER="${genesis_CFGS_PATH}/gathering" ; fi
	          if [ ! -n "${INVENTORY}" ]    ; then local INVENTORY="${genesis_DEFAULT_INVENTORY}" ; fi
	          if [ ! -n "${TARGET}"        ]      ; then local TARGET=""                    ; fi
	          if [ ! -n "${CALL_LOG}" ]      ; then local CALL_LOG="${HOME}/gathering.log"  ; fi
		      MENU_TEXT="(22)___________ ${GENESIS_PLAYBOOKS_HEADER[${GATHER}]}"
	          PARAMETRO=(     "INVENTORY"   "TARGET" "GATHERING_FOLDER"  "CALL_LOG" )
              VALOR_DEFECTO=( "${INVENTORY}"  "${TARGET}" "${GATHERING_FOLDER}" "${CALL_LOG}" )
	          SOLICITA_PARAMETRO=("-----> Machine's Inventory full path   [${VALOR_DEFECTO[0]}]:" \
	                              "-----> Target Machines            [${VALOR_DEFECTO[1]}]:" \
	                              "-----> Results Uploading Folder   [${VALOR_DEFECTO[2]}]:" \
	                              "-----> Log File                   [${VALOR_DEFECTO[3]}]:" \
                                     )
              RETURNING_MENU="10"
              RUN_ACTION="22"
              unset GATHERING_FOLDER INVENTORY  TARGET CALL_LOG
              ;;

	     [?])
	         echo "Removing Temporal Files... rm -f ${OUT_TMP} 2> /dev/null"
	         rm -f "${OUT_TMP}" 2> /dev/null
             echo "Removing Temporal Files... rm -f ${TMP_FILE}"
             rm -f "${TMP_FILE}" 2> /dev/null
	         echo -e "${COLOR[$SILVER]}*********************************************************************************${COLOR[$NC]}"
	         echo -e "${COLOR[$SILVER]}     Thank you for using Genesis System... hoping you enjoy the experience !!!!  ${COLOR[$NC]}"
	         echo -e "${COLOR[$SILVER]}*********************************************************************************${COLOR[$NC]}"
             exit 0
	         ;;
	esac
        OUT="$?"
}

########################################################################################
# MODULE 2 => HELPERS
#     Auxiliar functions
#  I.e.: ayuda(), error(), etc.
########################################################################################

#========================================================
#   Function: ayuda
#--------------------------------------------------------
#  Show help, the options of the command
#========================================================
function ayuda() {
	echo -e "------------------------------------------------------"
	echo -e "genesisCli -[hHRDLSKAPIQMGNTi:t:a:v:g:s:e:l:b:p:d:u:m:] "
	echo -e "  -h <HELP>        : Show this help"
	echo -e "---------- iDAS Transitions -------"
	echo -e "  -R <REFRESH>     : Shoot refresh iDAS build"
	echo -e "  -D <DEPLOY>      : Shoot deploy iDAS"
	echo -e "  -S <SETUP>       : Shoot setup iDAS"
	echo -e "  -K <KICKSTART>   : Shoot kickstart "
	echo -e "  -P <PROVISION>   : Shoot provision "
	echo -e "------------ iDAS Tools ------------"
	echo -e "  -L <LOAD CFGs>   : Shoot load iDAS CFGs"
	echo -e "  -A <ANSIBLE>     : Shoot ansible initializations"	
	echo -e "----------- iDAS Plugins -----------"	
	echo -e "  -I <IDM/LDAP>    : Shoot plugin idm/ldap"
	echo -e "  -Q <RABBIT MQ>   : Shoot plugin rabbit MQ"	
	echo -e "----------- iDAS Testing -----------"		
	echo -e "  -G <GRAPHICS>    : Shoot graphics"
	echo -e "  -M <MAP SSH>     : Shoot map ssh"
	echo -e "  -N <NETWORK>     : Shoot network"
	echo -e "  -T <NTP>         : Shoot NTP "

	echo -e "----------- Playbook Parameters -----------"	
    echo -e "  -i <INVENTORY>  [${genesis_DEFAULT_INVENTORY}] : Full path to inventory file"
    echo -e "  -t <TARGET>        []: comma separated IP addresses of target machines"
    echo -e "  -v <VAULT>     [root]: vault password where iDAS setup critical parameters are encrypted"
    echo -e "  -a <TAGS>          []: playbook tags to shoot"
    echo -e "  -e <EXTRA_VARS>    []: playbook additional environmental variables"
	
	echo -e "----------- Genesis Parameters -----------"	
    echo -e "  -p <PROJECT_NAME> [pansa]    : Project Name to install"	
    echo -e "  -g <CFGS_CORE>  []    : String CFGs to Load"
    echo -e "  -b <genesis_BUILD> []    : Path to build file"
    echo -e "  -s <SLOT>       [1]   : slot for setting up iDAS unattended installation files"
    echo -e "  -l <LOG_FILE>   [${HOME}/tests.log] : full path to log direct actions"

	echo -e "----------- Plugins Parameters -----------"
    echo -e "  -d <LDAP_DATA>           [pv3]      : LDAP Data to Feed"	
    echo -e "  -u <LDAP_TYPE>           [idm]      : IDM / LDAP"
    echo -e "  -m <LDAP_GROUP_MACHINES> [fdp_group]: Plugin Target Group of Machines"
	echo -e "------------------------------------------------------"
    OUT="$OK"
	
}

#========================================================
#   Function: error
#--------------------------------------------------------
#  Print Error Messages
#
# Parameters:
#    $1 Type of Error
#    $2 Missing Parameters
#========================================================
function error() {

	local RUTA_ACTUAL=`pwd`
	local TIMESTAMP=$(date -R)
    local LABEL="genesisCli"
	case "$1" in
		"-x"|"-noExec")   echo -e "[${TIMESTAMP}]: ${COLOR[$RED]} FATAL | [$LABEL] ABORTING: No {Exists/Execution Permisions} [$2] ${COLOR[$NC]}" ;;
		"-w"|"-noWrite")  echo -e "[${TIMESTAMP}]: ${COLOR[$RED]} FATAL | [$LABEL] ABORTING: No {Exists/Write Permisions} [$2] ${COLOR[$NC]}" ;;
		"-r"|"-noRead")   echo -e "[${TIMESTAMP}]: ${COLOR[$RED]} FATAL | [$LABEL] ABORTING: No {Exists/Read Permisions} [$2] ${COLOR[$NC]}" ;;
		"-e"|"-noExist")  echo -e "[${TIMESTAMP}]: ${COLOR[$RED]} FATAL | [$LABEL] ABORTING: No {File/Folder} found [$2] ${COLOR[$NC]}" ;;
		"-o"|"-noOwner")  echo -e "[${TIMESTAMP}]: ${COLOR[$RED]} FATAL | [$LABEL] ABORTING: No owner of path [$2] ${COLOR[$NC]}"
			              echo -e "[${TIMESTAMP}]: ${COLOR[$RED]} FATAL | [$LABEL] ABORTING: Usually you need to be 'root' to shoot iDAS ${COLOR[$NC]}" ;;
		[?])              echo -e "[${TIMESTAMP}]: ${COLOR[$RED]} FATAL | [$LABEL] ABORTING: Undefined error: [$2] ${COLOR[$NC]}" ;;
	esac

	OUT="${ERROR}"
}

#===================================================
#   Function: detectOS 
#---------------------------------------------------
#  Private Function
#
#  Detect Operating System
#===================================================
detectOS() {

 # 1.- Detect OS
 #--------------
 if [ -f /etc/os-release ]; then
    # freedesktop.org and systemd
    . /etc/os-release
    OS=$ID
    VER=$VERSION_ID
 elif type lsb_release >/dev/null 2>&1; then
    # linuxbase.org
    OS=$(lsb_release -si)
    VER=$(lsb_release -sr)
 elif [ -f /etc/lsb-release ]; then
    # For some versions of Debian/Ubuntu without lsb_release command
    . /etc/lsb-release
    OS=$DISTRIB_ID
    VER=$DISTRIB_RELEASE
 elif [ -f /etc/debian_version ]; then
    # Older Debian/Ubuntu/etc.
    OS=Debian
    VER=$(cat /etc/debian_version)
 elif [ -f /etc/SuSe-release ]; then
    # Older SuSE/etc.
    local SUSE=$(head -1 /etc/SuSe-release)
    local SUSE="${SUSE%%(*}"
    OS="${SUSE%% *}"
    VER=$(echo "${SUSE}" | tr -dc '0-9')
 elif [ -f /etc/redhat-release ]; then
    # Older Red Hat, CentOS, etc.
    local RH=$(cat /etc/redhat-release)
    OS="${RH%% *}"
    VER=$(echo "${RH}" | tr -dc '0-9')
 else
    # Fall back to uname, e.g. "Linux <version>", also works for BSD, etc.
    OS=$(uname -s)
    VER=$(uname -r)
 fi

 # 2.- Formatting Output
 #---------------
 OS=$( echo "${OS}"  | tr -d ' ' | tr [:upper:] [:lower:] )
 VER=$( echo "${VER}"  | tr -d ' ' | tr [:upper:] [:lower:] )
 LOG_HEADER="[${OS}-${VER}]-"
}

#===================================================
#   Function: {distro}Fixes
#---------------------------------------------------
#  Private Function
#
#  Pack Distro Specific fixes
#===================================================
ubuntuFixes() {

  # 0.- Logging
  #----------------------
  echo "........ LOCALE=[${LOCALE}]"
  
  # 1.- Fix Locales
  #----------------
  echo "${LOG_HEADER} -> sudo locale-gen ${LOCALE}"
  sudo locale-gen "${LOCALE}"

  echo "${LOG_HEADER} -> dpkg-reconfigure --frontend=noninteractive locales"
  sudo dpkg-reconfigure --frontend=noninteractive locales

  echo "${LOG_HEADER} ->  update-locale LANG=${LOCALE}"
  sudo update-locale LANG="${LOCALE}"

  echo "export LC_ALL=C.UTF-8"
  export LC_ALL="C.UTF-8"
    
}

redhatFixes() {
    
	# 1.- Repositories
	#-------------------
	# EPEL 
	echo "${LOG_HEADER} ->  sudo yum install epel-release -y"
	sudo yum install epel-release -y
    
	echo "${LOG_HEADER} -> sudo yum update -y"
    sudo yum update -y

	# Change SSH Configuration
	echo "${LOG_HEADER} ->  sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config"
	sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
	
	echo "${LOG_HEADER} -> echo '    StrictHostKeyChecking no' >> /etc/ssh/ssh_config"
    sudo echo "    StrictHostKeyChecking no" >> /etc/ssh/ssh_config
	
	echo "${LOG_HEADER} -> echo systemctl restart sshd.service" 
    sudo systemctl restart sshd.service
	
	# 2.- locale
	#-------------------	
	echo "${LOG_HEADER} -> sudo localectl set-locale LANG=${LOCALE}"	
	sudo localectl set-locale LANG="${LOCALE}"
	
	echo "${LOG_HEADER} -> localedef -v -c -i ${LOCALE%%.*} -f ${LOCALE##*.} ${LOCALE}"
	sudo localedef -v -c -i "${LOCALE%%.*}" -f "${LOCALE##*.}" "${LOCALE}"
	
	echo "export LC_ALL=C.UTF-8"
    export LC_ALL="C.UTF-8"
  
}

#===================================================
#   Function: firewallZone
#---------------------------------------------------
#  Private Function
#
#  Create Bifrost Firewall Zone
#===================================================
firewallZone() {

    if systemctl is-active --quiet firewalld ; then
       if [ -x "/bin/firewall-cmd" ] ; then
	     echo "${LOG_HEADER} -> sudo /bin/firewall-cmd --permanent --new-zone=bifrost"
         sudo /bin/firewall-cmd --permanent --new-zone=bifrost
	     echo "${LOG_HEADER} -> sudo /bin/firewall-cmd --permanent --zone=bifrost --add-service=ssh"		 
         sudo /bin/firewall-cmd --permanent --zone=bifrost --add-service=ssh
	     echo "${LOG_HEADER} -> sudo /bin/firewall-cmd --reload"			 
         sudo /bin/firewall-cmd --reload
       elif [ -x "/sbin/firewall-cmd" ] ; then
	     echo "${LOG_HEADER} -> sudo /sbin/firewall-cmd --permanent --new-zone=bifrost"
         sudo /sbin/firewall-cmd --permanent --new-zone=bifrost
	     echo "${LOG_HEADER} -> sudo /sbin/firewall-cmd --permanent --zone=bifrost --add-service=ssh"		 
         sudo /sbin/firewall-cmd --permanent --zone=bifrost --add-service=ssh
	     echo "${LOG_HEADER} -> sudo /sbin/firewall-cmd --reload"			 
         sudo /sbin/firewall-cmd --reload	 
	   fi 
    else  
	   echo "FIREWALL NOT ACTIVE IN THIS MACHINE -> Nothing to do"
	   systemctl status firewalld
    fi	
}

#===================================================
#   Function: setEnvironment
#---------------------------------------------------
#  Private Function
#
#  Set environment
#===================================================
setEnvironment() {
   case "${OS}" in
     "ubuntu"|"debian")
       DEP_INSTALLER=( 'python3' 'git' 'ansible' ) 
       DEP_DOCKER=( 'podman-docker' )
       INSTALLER_CMD="sudo -H -E apt-get -y install"
       CHECK_CMD="dpkg -s"
       ;;
     "redhat"|"centos")
       DEP_INSTALLER=( 'python3' 'git' 'ansible' 'glibc-locale-source' 'glibc-langpack-en' )
       DEP_DOCKER=( 'podman-docker' )
       PKG_MANAGER=$(/usr/bin/which dnf || /usr/bin/which yum)
       INSTALLER_CMD="sudo -H -E ${PKG_MANAGER} -y install"
       CHECK_CMD="rpm -q"
       ;;
     "suse"|"opensuse")
       INSTALLER_CMD="zipper"
       DEP_DOCKER=( 'podman-docker' )
       ;;
   esac
   
}

#===================================================
#   Function: setEnvironment
#---------------------------------------------------
#  Private Function
#
#  Set environment
#===================================================
runOSfixes() {
   case "${OS}" in
     "ubuntu"|"debian")
       ubuntuFixes
       ;;
     "redhat"|"centos")
       redhatFixes
       ;;
     "suse"|"opensuse")
       ;;
   esac
   
}

prepareImageCreation() {
   case "${OS}" in
     "ubuntu"|"debian")
       echo "${LOG_HEADER} -> sudo systemctl disable --now apparmor"
       sudo systemctl disable --now apparmor 
       ;;
     "redhat"|"centos")
       echo "${LOG_HEADER} -> SELinux"
       ;;
   esac
   
   local USER=$(whoami)
   echo "${LOG_HEADER} -> sudo chown -R $USER:ironic ${GENESIS_WORKING_PATH}/repo"
   sudo chown -R $USER:ironic ${GENESIS_WORKING_PATH}/repo
}

#===================================================
#   Function: runScripts
#---------------------------------------------------
#  Private Function
#
#  Shoot Bifrost Script
#===================================================
runScripts() {

   local FILE
   for FILE in ${FILES[@]} ; do
       if [ -n "$COMMAND" ] ; then   
	      local F=$(echo $FILE | wc -m)
          if [ "${F}" -gt 2 ] ; then
              echo "${LOG_HEADER} -> ${COMMAND} ${RUTA}/${FILE}"		  
		      ${COMMAND} ${RUTA}/${FILE}
		  else
              echo "${LOG_HEADER} -> ${COMMAND}"		  
		      sudo bash -c "${COMMAND}"
          fi
       elif [ -x "${RUTA}/${FILE}" ] ; then
          echo "${LOG_HEADER} -> ${RUTA}/${FILE}"
	      ${RUTA}/${FILE}
       else
	      error "-x" "${RUTA}/${FILE}" 
       fi
   done
}


#===================================================
#   Function: installDependencies
#---------------------------------------------------
#  Private Function
#
#  Chack Bifrost Installer Dependencies
#===================================================
installDependencies() {
  if [ ! -n "${PACKAGES}" ] ; then local  PACKAGES=( ${DEP_INSTALLER[@]} ) ; fi
  echo "${LOG_HEADER} -> ${INSTALLER_CMD} ${PACKAGES[@]}"
  ${INSTALLER_CMD} ${PACKAGES[@]}
}


#===================================================
#   Function: installEnvironment
#---------------------------------------------------
#  Private Function
#
#  Download Bifrost Dependencies
#===================================================
installEnvironment() {
   
   # Local Environment
   #------------------
   local RUTA_PROJECT="${GENESIS_WORKING_PATH}"

   # Actions
   #--------
   local INDEX_DEP=0
   local INDEX_CMD=0
   setupCommand
   while [[ "${INDEX_DEP}" < "${#DEPENDENCIES[@]}" ]] ; do

	 # 1.- Get Command 
	 if [ "${INDEX_CMD}" -lt "${#DEPENDENCIES_INSTALLER[@]}" ] ; then
	     local COMMAND="${DEPENDENCIES_INSTALLER[${INDEX_CMD}]}"
	     local INDEX_CMD=$(expr ${INDEX_CMD} + 1)
	  fi
          
	  # 2.- Get CMD Result
	  local FILES=( "${DEPENDENCIES[$INDEX_DEP]}" )
		  
	  # 3.- RUN Script	  
	  local RUTA="${RUTA_PROJECT}"
	  runScripts
          #echo -e "${PRINT_NAME} ${COLOR[$SILVER]} ${PRINT_STATUS} ${COLOR[$NC]}"

          # 4.- Update the loop		  
	  local INDEX_DEP=$(expr ${INDEX_DEP} + 1)     
   done
  
}


#===================================================
#   Function: bifrostScriptsWorkaround
#---------------------------------------------------
#  Private Function
#
#  Bifrost Scripts path detection depends on linux distro
#  - This work around seems to fix the issue
#===================================================
bifrostScriptsWorkaround() {
 
 if [ -x "${GENESIS_BIFROST_WORKING_PATH}/scripts/env-setup.sh" ] ; then
    echo "${LOG_HEADER} -> cd ${GENESIS_BIFROST_WORKING_PATH} "
    cd "${GENESIS_BIFROST_WORKING_PATH}"
	
	echo "${LOG_HEADER} -> ./scripts/env-setup.sh"
    ./scripts/env-setup.sh
	
	echo "${LOG_HEADER} -> cd -"
    cd -
	
  else
    error -x "${GENESIS_BIFROST_WORKING_PATH}/scripts/env-setup.sh"
  fi
}

#===================================================
#   Function: prepareLocalMachine
#---------------------------------------------------
#  Private Function
#
#  Chack Bifrost Installer Dependencies
#===================================================
prepareLocalMachine() {
  local  PACKAGES=( ${DEP_INSTALLER[@]} )
  runOSfixes
  installDependencies
  firewallZone
  installEnvironment
  bifrostScriptsWorkaround
}

#========================================================
#   Function: updateInventory
#--------------------------------------------------------
#   iDAS ISOS generation
#    - common.yaml... create from /mnt/isos/ contents
#========================================================
function updateInventory() {
   	
	if [ -n "${IRONIC_BAREMETAL_NODES}" ] ; then
	
	   # Local Environment
	   local POSICION=0
	   local CNF_REEMPLAZO=( "${GENESIS_PROJECT_ANSIBLE_CFG}" )
	   local VAR='inventory'
	   local VALOR="hosts/target,hosts/${IRONIC_BAREMETAL_NODES##*/}"
	   local SIN_COMILLA="Si"
	   
	   # 1.- Replace Pattern
	   echo "${LOG_HEADER} - reemplazaParametro Si"
       reemplazaParametro "Si"
       local PERMISSIONS=$(stat -c "%a %n" ${CNF_REEMPLAZO[${POSICION}]} | awk '{print $1;}')
	   echo "${LOG_HEADER} - chmod $PERMISSIONS ${OUT_TMP}"
       chmod "$PERMISSIONS" "${OUT_TMP}"
	   echo "${LOG_HEADER} - mv ${OUT_TMP} ${CNF_REEMPLAZO[${POSICION}]}"
	   mv "${OUT_TMP}" "${CNF_REEMPLAZO[${POSICION}]}"	
 
       # 2.- Update environment Variables
       GENESIS_BIFROST_INVENTORY_SOURCE="${GENESIS_HOSTS_WORKING_PATH}/${IRONIC_BAREMETAL_NODES##*/}/${IRONIC_NODES_FILE}"
       GENESIS_ANSIBLE_INVENTORY_SOURCE="${GENESIS_HOSTS_WORKING_PATH}/${IRONIC_BAREMETAL_NODES##*/}/inventory"
       echo "${LOG_HEADER} -..... GENESIS_BIFROST_INVENTORY_SOURCE=[${GENESIS_BIFROST_INVENTORY_SOURCE}]"
       echo "${LOG_HEADER} -... GENESIS_ANSIBLE_INVENTORY_SOURCE=[${GENESIS_ANSIBLE_INVENTORY_SOURCE}]"	
       setupCommand
	   
	   # 3 Clean environment
	   unset PERMISSIONS POSICION CNF_REEMPLAZO PARAMETRO inventory
 	  	     	   
	fi
}


#===================================================
#   Function: addGenesisToHosts
#---------------------------------------------------
#  Private Function
#
#  Add Genesis IP address to /etc/hosts 
#     in order to use names in YAML group_vars profiles
#===================================================
addGenesisToHosts()  {

   echo "Entra "
   # 1.- Add Genesis to Hosts
   local GENESIS_NAME="genesis.maas.lab"
   if [ -r "$GENESIS_HOSTS_TARGET_FILE" ; then
       local GENESIS_NAME=$(cat $GENESIS_HOSTS_TARGET_FILE | grep 'genesis_hostvars_name:' | head -1 | awk -F: '{print $NF}' | tr -d '"' )
   fi
   local ADDR=$( echo "${PXE[$DHCP_IP]}" | awk -F/ '{print $1}' | tr -d ' ' )
   local NAME=$( echo "${GENESIS_NAME}" | tr -d ' ' )
   echo "${LOG_HEADER} -...... GENESIS_NAME=[${NAME}]"
   echo "${LOG_HEADER} -... GENESIS_ADDRESS=[${ADDR}]"
   echo "${LOG_HEADER} -> sudo sed -i /${NAME}/d /etc/hosts"
   sudo bash -c "sed -i /${NAME}/d /etc/hosts"
   echo "${LOG_HEADER} -> sudo bash -c echo ${ADDR} ${NAME} >> /etc/hosts"
   sudo bash -c "echo ${ADDR} ${NAME} >> /etc/hosts"
   
   # 2.- Add User to Ironic group 
   local USER=$(whoami)
   echo "${LOG_HEADER} -> sudo usermod -a -G ironic $USER"   
   sudo usermod -a -G ironic "$USER"
}


#===================================================
#   Function: enableIronicNetworkInterface
#---------------------------------------------------
#  Private Function
#
#  Before Installing Ironic, enable DHCP interface
#===================================================
enableIronicNetworkInterface() {

   #---------------------
   # Actions
   #---------------------

   # 0.- Logging
   #----------------------
   echo "..PXE[DHCP_NIC]=[${PXE[$DHCP_NIC]}]"
   echo "...PXE[DHCP_IP]=[${PXE[$DHCP_IP]}]"


   # 1.- Enable Network Interface
   #----------------------
   detectOS
   case "${OS}" in
     "ubuntu"|"debian")
	    
        echo "${LOG_HEADER} -> sudo netplan set ethernets.${PXE[$DHCP_NIC]}.dhcp4=false"
        sudo netplan set ethernets.${PXE[$DHCP_NIC]}.dhcp4=false
        
        echo "${LOG_HEADER} -> sudo netplan set ethernets.${PXE[$DHCP_NIC]}.addresses=[${PXE[$DHCP_IP]}]"
        sudo netplan set ethernets.${PXE[$DHCP_NIC]}.addresses=["${PXE[$DHCP_IP]}"]
        
        echo "${LOG_HEADER} -> sudo timeout 3s bash -c netplan apply"
        sudo timeout 3s bash -c "netplan apply"

		;;
    *) 
	    if [ -n "${DETECT_CONEXION}" ] ; then 
    	  echo "${LOG_HEADER} ->  nmcli con add con-name pxe ifname ${PXE[$DHCP_NIC]} type ethernet ipv4.methodmanual ipv4.addresses=${PXE[$DHCP_IP]}"
          nmcli con add con-name "pxe" ifname "${PXE[$DHCP_NIC]}" type "ethernet" ipv4.method="manual" ipv4.addresses="${PXE[$DHCP_IP]}"
    	  echo "${LOG_HEADER} -> nmcli con up pxe"
    	  nmcli con up "pxe"
        fi	
		;;
	esac
}


#========================================================
#   Function: passwordlessDetection
#--------------------------------------------------------
#  -Generate User SSH key in localhost
#  -Ensure localhost passwordless access
#========================================================
function passwordlessDetection() {

    #------------------
    # LOCAL ENVIRONMENT
    #------------------
    local HOST="${1}"
    local USER="${2}"
    local USER_PASSWORD="${3}"	
    local SSH_TIMEOUT="3"

    #------------------
    # ACTIONS
    #------------------
	
	# 1.- Passwordless Detection
    local PASSWORDLESS_DETECTED=$(ssh -oBatchMode='yes' -oConnectTimeout="${SSH_TIMEOUT}" -oStrictHostKeyChecking='no' ${USER}${HOST} 'echo DONE' 2> /dev/null)
	if [ -n "${OKD_CLUSTER_NAME}" ] ; then 
       local PASSWORDLESS_OKD=$(ssh -i "/home/okd/.ssh/${OKD_CLUSTER_NAME}" -oBatchMode='yes' -oConnectTimeout=${SSH_TIMEOUT} -oStrictHostKeyChecking='no' core@${HOST} 'echo DONE' 2> /dev/null)
	fi
	
	# 2.- Trying to establish passwordless connection
    if [[ "${PASSWORDLESS_DETECTED}" == "DONE" ]] ; then
        echo -e "[genesisCli.passwordlessDetection] - ${COLOR[$SEA]}Passwordless already Enabled at ${USER}${HOST}${COLOR[$NC]}"
	elif [[ "${PASSWORDLESS_OKD}" == "DONE" ]] ; then
	    echo -e "[genesisCli.passwordlessDetection] - ${COLOR[$SEA]}Passwordless already Enabled at [su - okd] core@${HOST}${COLOR[$NC]}"
    elif [ -x "/bin/ssh-copy-id" ] || [ -x "/sbin/ssh-copy-id" ] ; then

        echo "rm -f ${HOME}/.ssh/known_hosts"		
		rm -f "${HOME}/.ssh/known_hosts"
		   
	    if [ -n "${USER_PASSWORD}" ] ; then
		   echo "[genesisCli.passwordlessDetection] -  sshpass -p ${USER_PASSWORD} ssh-copy-id -oConnectTimeout=${SSH_TIMEOUT} -oStrictHostKeyChecking='no' ${USER}${HOST} 2> ${OUT_TMP}" 
           sshpass -p "${USER_PASSWORD}" ssh-copy-id -oConnectTimeout="${SSH_TIMEOUT}" -oStrictHostKeyChecking='no' "${USER}${HOST}" 2> "${OUT_TMP}"
		else
		   echo "[genesisCli.passwordlessDetection] - ssh-copy-id -oConnectTimeout=${SSH_TIMEOUT} -oStrictHostKeyChecking='no' ${USER}${HOST} 2> ${OUT_TMP}"
		   ssh-copy-id -oConnectTimeout="${SSH_TIMEOUT}" -oStrictHostKeyChecking='no' "${USER}${HOST}" 2> "${OUT_TMP}"
		fi 
        local SUCCESS="$?"
        local OUTPUT_COPY=$(cat ${OUT_TMP} | grep ERR)
		
		if [[ "${SUCCESS}" == "0" ]] ; then
		    echo -e "[genesisCli.passwordlessDetection] - ${COLOR[$SEA]}Passwordless was successfully Established at ${USER}${HOST}? [$SUCCESS] (OK=$OK, ERROR=$ERROR) ${OUTPUT_COPY}${COLOR[$NC]}"
		else
             echo -e "[genesisCli.passwordlessDetection] - ${COLOR[$RED]}Passwordless was not successfully Established at ${USER}${HOST}? [$SUCCESS] (OK=$OK, ERROR=$ERROR) ${OUTPUT_COPY}${COLOR[$NC]}"		
		fi

    fi
    OUT="$?"
}

#========================================================
#   Function: sshUserKey
#--------------------------------------------------------
#  -Generate User SSH key in localhost
#  -Ensure localhost passwordless access
#========================================================
function sshUserKey() {

	#---------------------
	#  ACTIONS
	#---------------------
	
    # 1.- Create SSH folder
    #-----------------------
    if [ ! -e "${HOME}/.ssh" ] ; then
       mkdir -p "${HOME}/.ssh"
       chmod 700 "${HOME}/.ssh"
    fi

    # 2.- Detect SSH Keys
    #-----------------------
    local KEYS=$(ls ${HOME}/.ssh/*pub 2> /dev/null)
    echo -e ".... User SSH Keys detected: \n$KEYS"
    if [ ! -n "${KEYS}" ] ; then
       if [ -x "/bin/ssh-keygen" ] || [ -x "/sbin/ssh-keygen" ] ; then
          echo "............................................................................"
          echo " No SSH Key detected on this user... we proceed with interactive generation"
		  echo "     ssh-keygen -b 2048 -t rsa -f ${HOME}/id_rsa -q -N ' ' "
          echo "............................................................................"
          ssh-keygen -b 2048 -t rsa -f "${HOME}/.ssh/id_rsa" -q -N "" 
      else
	      error "-x" "[genesisCli.sshUserKey] - /bin/ssh-keygen || /sbin/ssh-keygen"
       fi
    else
	   echo "[genesisCli.sshUserKey] - Detected Keys [${KEYS}]" 
	fi

    # 3.- Localhost Passwordless SSH Access
    #-----------------------
    local USER="$(whoami)"
    passwordlessDetection "localhost" "${USER}@" "${GENESIS_ROOT_PASSWORD}"
}

#========================================================
#   Function: trust_relationships
#--------------------------------------------------------
#  -Load Inventory list of hosts
#  -Ensure String passwordless access
#========================================================
function trust_relationships() {

    #---------------------------
    # LOCAL ENVIRONMENT
    #---------------------------
    if [ ! -n "${BAREMETAL_ROOT_PASSWORD}" ] ; then local BAREMETAL_ROOT_PASSWORD="root" ; fi	
    local LIST_OF_NODES_FILE="${1}"
    local NODE INVENTORY_LIST
    if [ -n "${USER}" ] ; then local USER="${USER}@" 
	else                       local USER="root@"  
	fi    
	
    #---------------------------
    # ACTIONS
    #---------------------------
	
	# 1.- Load list of IP nodes
    if [ -r "${LIST_OF_NODES_FILE}" ] ; then
        . "${LIST_OF_NODES_FILE}" 2> /dev/null
    elif [ -r "${GENESIS_ANSIBLE_INVENTORY_SOURCE}" ] ; then
	    local INVENTORY_LIST=( $(runAdHoc ' ' '--list-hosts' | sed '1d') )
    fi
	
	# 2.- Detect Passwordless 
	echo "NODES.... [${INVENTORY_LIST[@]}]"
    if [ -n "${INVENTORY_LIST}" ] ; then
       for NODE in "${INVENTORY_LIST[@]}" ; do
           passwordlessDetection "${NODE}" "${USER}" "${BAREMETAL_ROOT_PASSWORD}"
           OUT="$?"
       done
    else
       echo -e "[genesisCli.trust_relationships] - ${COLOR[$YELLOW]} [WARN] - MISSING CONFIGURATION FILE: please try to SETUP iDAS before ${COLOR[$NC]}"
       error "-r" "[genesisCli.trust_relationships] - ${GENESIS_ANSIBLE_INVENTORY_SOURCE}"
    fi	
    unset NODE INVENTORY_LIST LIST_OF_NODES_FILE
}


#========================================================
#   Function: runChecks
#--------------------------------------------------------
#  Run verifications
#========================================================
function runChecks() {
   if [ -n "${CHECK_CMD}" ] ; then 
	   local INDEX_CMD="0"
	   
       while [[ "${INDEX_CMD}" < "${#CHECK_CMD[@]}" ]] ; do

		  # 0.- Get Command	     
	      local COMMAND="${CHECK_CMD[${INDEX_CMD}]}"
  		  
		  # 1.- Get Verification Name
		  if [ -n "${CHECK_NAME}" ] ; then 
		     if [ "${INDEX_CMD}" -lt "${#CHECK_NAME[@]}" ] ; then
		        local PRINT_NAME="${CHECK_NAME[${INDEX_CMD}]}"
		     fi
		  fi
		  
		  # 2.- Get Ansible AdHoc Module
		  if [ -n "${CHECK_MODULE}" ] ; then 
		    unset ANSIBLE_MODULE
		    if [ "${INDEX_CMD}" -lt "${#CHECK_MODULE[@]}" ] ; then
		       local ANSIBLE_MODULE="${CHECK_MODULE[${INDEX_CMD}]}"
		    fi
         fi			
          
		  # 3.- Print Results
          if [ -n "${CHECK_ANSIBLE}" ] ; then
		     echo -e "${PRINT_NAME}"
		     runAdHoc "${ANSIBLE_MODULE}" "${COMMAND}"  "${CALL_LOG}"
		  else
		     local PRINT_STATUS=$( timeout 3 ${COMMAND} )
			 echo -e "${PRINT_NAME} ${COLOR[$SILVER]} ${PRINT_STATUS} ${COLOR[$NC]}"
		  fi
		  
          # 5.- Update the loop		  
		  local INDEX_CMD=$(expr ${INDEX_CMD} + 1)
		  
       done	   
   fi   
   unset ANSIBLE_MODULE COMMAND PRINT_NAME
}

#========================================================
#   Function: state_status
#--------------------------------------------------------
#  Verify state reached after a transition
#========================================================
function state_status() {

    #---------------------------
    # LOCAL ENVIRONMENT
    #---------------------------
	local STATE_NAME="$1"	
    local RPM_NAME="$2"
	case "${STATE_NAME}" in
       ${REFRESH}|"genesis_machine_ready") 
	        local STATE_FULL_NAME="G-${REFRESH}: Genesis Machine Ready"		   
	        local SSH_LOCALHOST="YES"
	        local CHECK_NAME=( \
			                   "...Script Working Folder: " \
                               "........Operating System: " \
                               "...........Repos Created: " \
                               ".........Firewall Status: " \
                               "..........SELinux Status: " \
		                       )
	        local CHECK_CMD=( \
			                   "pwd" \
			                   "cat /etc/os-release" \
							   "ls ${GENESIS_WORKING_PATH}/repo/*" \
							   "systemctl status firewalld" \
							   "sestatus" \
			                )
	    ;;
      ${CREATE}|"genesis_installed")   
	        local STATE_FULL_NAME="G-${CREATE}: Genesis Created"	  
	        local CHECK_NAME=( \
                               "Service DNSMASQ: " \
                               "..Service NGINX: " \
							   ".Service IRONIC: " \
							   "......PXE Files: " \
							   "....DNS Active?: " \
		                       )
	        local CHECK_CMD=( \
			                   'systemctl status dnsmasq'  \
			                   'systemctl status nginx'    \
			                   'systemctl status ironic'   \
							   'ls /var/lib/tftpboot/*/'   \
							   'nslookup genesis.maas.lab' \
			                )
	   ;;

      ${INIT}|"genesis_init") 
	        local STATE_FULL_NAME="G-${INIT}: Genesis Init"
	        local CHECK_NAME=( \
                               "Images Repo: "   \
                               "ORAS Registry: "   \
		                       )
	        local CHECK_CMD=( \
			                   "ls -la ${GENESIS_WORKING_PATH}/repo/dib/"  \
			                   'oras version'  \
			                )
	   ;;
	   
      ${SETUP}|"baremetal_setup") 
	        local STATE_FULL_NAME="B-${SETUP}: Baremetal Nodes Ready to Deploy"
			unset INVENTORY PLAYBOOK
			local ATARGET='localhost'
	        local CHECK_NAME=( \
                               "Ironic List State of Nodes: "   \
                               "Ironic Deployment Ports: "   \							   
		                       )							   
	        local CHECK_CMD=( \
			                   'baremetal node list'  \
			                   'baremetal port list'  \							   
			                )
	   ;;	   
	   
      ${DEPLOY}|"baremetal_deploy") 
	        local STATE_FULL_NAME="B-${DEPLOY}: Baremetal Nodes run OS unattended installation"
			unset INVENTORY PLAYBOOK
			local ATARGET='localhost'
	        local CHECK_NAME=( \
                               "Ironic List State of Nodes: "   \
		                       )							   
	        local CHECK_CMD=( \
			                   'baremetal node list'  \
			                )
	   ;;	   
      6|"baremetal_ansible") 
	        local STATE_FULL_NAME="Ansible Pre-Ready: Baremetal Nodes ready to provision Software profile"	  
	        local CHECK_ANSIBLE=1
			unset INVENTORY PLAYBOOK
			unset INVENTORY
	        local CHECK_NAME=( \
                               "Ansible Ping: " \
		                       )
	        local CHECK_MODULE=( \
			                   'ping' \
			                )							   
	        local CHECK_CMD=( \
			                   ' ' \
			                )
	   ;;	   
    esac

    #---------------------------
    # ACTIONS
    #---------------------------
	if [ -n "${CHECK_CMD}" ] && [ -n "${CHECK_NAME}" ] ; then
       echo -e "--------------------------------------------" 
       echo -e "     STATE [${STATE_FULL_NAME}] - STATUS" 	   
       echo -e "--------------------------------------------"
	   if [ -n "${SSH_LOCALHOST}" ] ; then sshUserKey ; fi
	   setupCommand
       runChecks 	   
       echo -e "--------------------------------------------" 
       echo -e "     STATE [${STATE_FULL_NAME}] - STATUS" 	   
       echo -e "--------------------------------------------" 
	fi
	unset CHECK_NAME CHECK_CMD SSH_LOCALHOST
}

########################################################################################
# MODULE 3 => MENU OPTIONS CAPTURE: dynamic (list of files from a path) and static (list of strings)
########################################################################################

#========================================================
#   Function: listaOpciones_Dinamica
#--------------------------------------------------------
#  List of files inside a folder is used as menu options
#========================================================
function listaOpciones_Dinamica() {

	#------------------
	# LOCAL ENVIRONMENT
	#------------------
	local INDICE="$1"
	local REMOVE_PATH="$2"
	local RUTA="${RUTA_OPCIONES[${INDICE}]}"
	local EXT="${EXT_OPCIONES[${INDICE}]}"
	local ELIMINA="${SUPRIME_EXT[${INDICE}]}"

	#-----------------
	# ACTIONS
	#-----------------
    if [ -r "${RUTA}" ] ; then
            local LIST_FILES=$(ls -1 -d "${RUTA}/"*${EXT} 2> /dev/null)
            if [ -n "${LIST_FILES[@]}" ] ; then
	        local INDICE="0"
	        for ELEMENTO in $(ls -1 -d "${RUTA}/"*${EXT} 2> /dev/null) ; do

		        # Nombre de la opcion  (with/without path-extension)
		        if [ -n "${REMOVE_PATH}" ] ; then local ELEMENTO="${ELEMENTO##*/}" ; fi
		        if [ -n "${ELIMINA}"     ] ; then local ELEMENTO="${ELEMENTO%%.*}" ; fi

                # Variables Publicas
		        ELEMENTOS_MENU[${INDICE}]="${ELEMENTO}"
		        NUM_OPCIONES="${INDICE}"

		        # Listando Opciones
		        echo -e "${INDICE} .- ${ELEMENTO}"
		        local INDICE=`expr "${INDICE}" + 1`
	        done
        else
           error "-r" "${RUTA}/*${EXT}"
        fi
    else
        error "-r" "${RUTA}"
    fi
}

#========================================================
#   Function: listaOpciones_Estatica
#--------------------------------------------------------
#  List of strings already provided in data model
#========================================================
function listaOpciones_Estatica() {

	#------------------
	# LOCAL ENVIRONMENT
	#------------------
	local INDICE="$1"

	#-----------------
	# ACTIONS
	#-----------------
	local INDICE="0"
	for ELEMENTO in "${RUTA_OPCIONES[@]}" ; do
        
		if [ ! -n "${MENU_SKIP_PATHS}" ] || [ ! -d "${ELEMENTO}" ] ; then	
        
			# Variables Publicas
			ELEMENTOS_MENU[${INDICE}]="${ELEMENTO}"
			NUM_OPCIONES="${INDICE}"

			# Listando Opciones
			echo -e "${INDICE} .- ${ELEMENTO}"
		fi
		
		local INDICE=`expr "${INDICE}" + 1`

	done
}

#========================================================
#   Function: capturaOpcionLista
#--------------------------------------------------------
#  Capture option value from list of available options
#========================================================
function capturaOpcionLista() {

	# 1.- Espera Entrada
	#--------------------
	eval read -e INDICE_OPCION

	# 2.- Evalua Entrada
	#--------------------
	# Se introdujo una opcion ----------------------------- COMPROBACION 1
	if [ -n "${INDICE_OPCION}" ] ; then
		VALOR=""
		while [ ! -n "$VALOR" ] ; do

			# La opcion es un numero  ------------- COMPROBACION 2
			if [ "${INDICE_OPCION}" -eq "${INDICE_OPCION}" 2> /dev/null ]; then

				# La opcion es numero valido -- COMPROBACION 3
				if [ "${INDICE_OPCION}" -le "${NUM_OPCIONES}" ] ; then
					VALOR="${ELEMENTOS_MENU[${INDICE_OPCION}]}"

				# La opcion es numero valido -- COMPROBACION 3
				else
					echo -e "[${INDICE_OPCION}] - No valid Option [0-${NUM_OPCIONES}], please try again"
					eval read -e INDICE_OPCION
					if [ ! -n "${INDICE_OPCION}" ] ; then break ; fi
				fi

			# La opcion es un numero  ------------- COMPROBACION 2
			else
				echo -e "[${INDICE_OPCION}] - No numeric value introduced, please try again"
				eval read -e INDICE_OPCION
				if [ ! -n "${INDICE_OPCION}" ] ; then break ; fi
			fi
		done
	fi
}

#========================================================
#   Function: capturaValor
#--------------------------------------------------------
#  Capture Value in two different use cases
#    Case 1.- List of Values
#         1.1.- Display list of Strings as options
#         1.2.- Display list of files from a folder
#    Case 2.- Text input
#========================================================
function capturaValor() {

	#------------------
	# LOCAL ENVIRONMENT
	#------------------
	local INDICE="$1"
	local RUTA_LISTA="${RUTA_OPCIONES[${INDICE}]}"

	#-----------------
	# ACTIONS
	#-----------------

	# 1.- List of Options
	#--------------------
	if [ -n "${RUTA_LISTA}" ] ; then

	    # 1.1.- List of files from a folder as Options
		if [ -r "${RUTA_LISTA}" ] ; then

		    # 1.1.1.- Build list and Capture option
		    listaOpciones_Dinamica "${INDICE}" "${MENU_SKIP_PATHS}"
		    capturaOpcionLista

		    # 1.1.2.- Assign default value
            if [ ! -n "${VALOR}" ] ; then
                 local INDICE_OPCION="${VALOR_DEFECTO[${POSICION}]}"
                 VALOR="${ELEMENTOS_MENU[${INDICE_OPCION}]}"
		    fi

        # 1.2.- List of Strings as Options
		else
			listaOpciones_Estatica "${INDICE}"
			capturaOpcionLista
		fi

	# 2.- Plain Input
	#--------------------
	else
		eval read -e VALOR
	fi

	# 3.- Default Value
	#--------------------
    if [ ! -n "${VALOR}" ] ; then
		VALOR="${VALOR_DEFECTO[${POSICION}]}"
    fi
}

########################################################################################
# MODULE 4 - DEPLOY MENU
########################################################################################

#========================================================
#   Function: reemplazoParametro
#--------------------------------------------------------
#   Replace text in configuration file
#========================================================
function reemplazaParametro() {

	local REEMPLAZA_LINEA="$1"
	local SEPARADOR_CAMPO='='
	if [ -n "${CNF_SEPARADOR_CAMPO[${POSICION}]}" ] ; then local SEPARADOR_CAMPO="${CNF_SEPARADOR_CAMPO[${POSICION}]}" ; fi 
	if [ -w "${CNF_REEMPLAZO[${POSICION}]}" ] ; then
	   if [ -n "${REEMPLAZA_LINEA}" ] ; then
	     if [ ! -n "${SIN_COMILLA}" ] ; then local REPLN="${VAR}${SEPARADOR_CAMPO}\"${PREPO}${VALOR}\""
		 else                                local REPLN="${VAR}${SEPARADOR_CAMPO}${PREPO}${VALOR}" 
		 fi
	   	 echo "===> sed s|^${VAR}${SEPARADOR_CAMPO}.*$|$REPLN| ${CNF_REEMPLAZO[${POSICION}]} > ${OUT_TMP}"
	   	 sed "s|^${VAR}${SEPARADOR_CAMPO}.*$|$REPLN|" "${CNF_REEMPLAZO[${POSICION}]}" > "${OUT_TMP}"
	   else
	   	 local REPLN="${PREPO}${VALOR}"
	   	 echo "===> sed s|${VAR}|$REPLN|g ${CNF_REEMPLAZO[${POSICION}]} > ${OUT_TMP}"
	   	 sed "s|${VAR}|$REPLN|g" "${CNF_REEMPLAZO[${POSICION}]}" > "${OUT_TMP}"
	   fi
	else
	   error "-w" "${CNF_REEMPLAZO[${POSICION}]}"
	fi
    OUT="$?"
}
#========================================================
#   Function: deployMenu
#--------------------------------------------------------
#   Deploy menu according to properties in data model
#========================================================
function deployMenu() {

    #------------------
	# ENTORNO LOCAL
	#------------------
	local REEMPLAZA_LINEA="$1"
	local POSICION="0"
    local VAR VALOR PREPO

	#------------------
	# ACCIONES
	#------------------

	# 1.- Display Text of the Menu
	#--------------------
	if [ -n "${MENU_TEXT}" ] ; then
	   echo -e "${MENU_TEXT}"
	   unset MENU_TEXT
	fi

	# 2.- Capture sequence of parameters
	#--------------------
	while [ "${POSICION}" -lt "${#PARAMETRO[@]}" ] ; do

		# 2.1.- Capture Variable and Value
		#--------------------------------
		VAR="${PARAMETRO[${POSICION}]}"
		VALOR="${!VAR}"

		# 2.2.- Request and Capture Value
		#------------------------------------
		if [ ! -n "${VALOR}" ] && [ -n "${SOLICITA_PARAMETRO[${POSICION}]}" ] ; then

			# 2.2.1.- Capture Parameter
			echo ""
			echo -e "${SOLICITA_PARAMETRO[${POSICION}]}"
			capturaValor "${POSICION}"

			# 2.2.2.- Print resulting value
			echo -e " Resulting Option: [${VALOR}]"

            # 2.2.3.- Break Menu Display 
			if [ -n "${MENU_BREAK_TEXT}" ] ; then
			   if [ "${MENU_BREAK_TEXT}" == "${POSICION}" ] ; then unset RUTA_OPCIONES ; fi
			fi
		fi
		
		# 2.3.- Value Treatment
		#-----------------------------
		PREPO=""

		# 2.3.1.- CNF for text Replacement
		if [ -n "$VALOR" ] && [ -n "${CNF_REEMPLAZO[$POSICION]}" ] ; then

			#    2.3.1.1.- Replace / for \/ for the sed command
			#            BEWARE: dump results to temporal file in order to avoid issues with bash of different systems
			echo "${VALOR}" | awk 'BEGIN{FS="/"} {linea=$1;for(i=2;i<=NF;i++) {linea=linea "\\/" $i }} END{print linea}' > "${OUT_TMP}"
			VALOR=`cat "${OUT_TMP}"`

			#   2.3.1.2.- Add preposition
			PREPO="${PREPOSICION[${POSICION}]}"
               if [ -n "${CNF_REEMPLAZO[${POSICION}]}" ] ; then 
                 reemplazaParametro "${REEMPLAZA_LINEA}"
			     local PERMISSIONS=$(stat -c "%a %n" ${CNF_REEMPLAZO[${POSICION}]} | awk '{print $1;}')
			     chmod "$PERMISSIONS" "${OUT_TMP}"
		         mv "${OUT_TMP}" "${CNF_REEMPLAZO[${POSICION}]}"				
               fi
		fi 

		# 2.3.2.- Capture List Value
		if [ -n "$VALOR" ] ; then
            echo "${VAR}='${VALOR}'" > "${OUT_TMP}"
            . "${OUT_TMP}"
		fi

		# 2.4.- Loop index update
		#----------------------------
		POSICION=`expr "${POSICION}" +  1`
	done


	# 3.- Restore loop Environment
	#--------------------
    OUT="$?"
	unset VALOR VAL PREPO POSICION
}

########################################################################################
# MODULE 5 - ACTIONS HELPERS
########################################################################################

#========================================================
#   Function: replacePattern
#--------------------------------------------------------
#   Replace pattern in a text file
#========================================================
function replacePattern() {

   #---------------------
   # LOCAL ENVIRONMENT
   #---------------------
   local DEST_FILE="$1"
   local REPLACE_PATTERN="$2"
   local DETECTION_PATTERN="$3"

   #---------------------
   # ACTIONS
   #---------------------
   if [ -w "${DEST_FILE}" ] ; then
      if [ -n "${REPLACE_PATTERN}" ] ; then
         if [ -n "${DETECTION_PATTERN}" ] ; then
           echo "-> Replacing pattern: sed -i s|^${DETECTION_PATTERN}.*|${REPLACE_PATTERN}| ${DEST_FILE}"
           sed -i "s|^${DETECTION_PATTERN}.*|${REPLACE_PATTERN}| " "${DEST_FILE}"
         fi
      fi
   else
      error -w "${DEST_FILE}"
   fi
}

#========================================================
#   Function: vaultPass
#--------------------------------------------------------
#  -Create Vault File with encripted password
#========================================================
function vaultPass() {

   #---------------------
   # LOCAL ENVIRONMENT
   #---------------------
   local TMP_PATH="$1"
   local PASSWORD
   if [ ! -n "${TMP_PATH}" ] ; then local TMP_PATH="/tmp/" ; fi

   #---------------------
   # ACTIONS
   #---------------------

   # 1.- Removing Old Temp File
   #----------------
   if [ -w "${TMP_FILE}" ]  ; then
        echo "Removing Temporal Files... rm -f ${TMP_FILE}"
        rm -f "${TMP_FILE}" 2> /dev/null
        OUT="$?"
   fi

   # 2.- Create New Temp File
   #----------------
   if [ -w "${TMP_PATH}" ]  ; then

	  # 2.1.- Create Temp File with password encrypted
      if [ -x "/bin/mktemp" ] ||  [ -x "/sbin/mktemp" ] ; then
		 TMP_FILE=$(mktemp ${TMP_PATH}ansible.xsVtj.XXXX)
      else
         error "-x" "/bin/mktemp || /sbin/mktemp"
      fi		 
	  	 
	  # 2.2.- Create Encrypted Password	 
	  if [ -x "/bin/python" ] ||  [ -x "/sbin/python" ] ; then
         PASSWORD=$(python - <<END
import hashlib, base64, hmac
hash_code= hmac.HMAC(b"", b'${VAULT}', hashlib.sha512).digest()
base64_bytes = base64.b64encode(hash_code)
base64_string = base64_bytes.decode("ascii")
print(base64_string)
END
)
      elif [ -x "/bin/python3" ] ||  [ -x "/sbin/python3" ] ; then
         PASSWORD=$(python3 - <<END
import hashlib, base64, hmac
hash_code= hmac.HMAC(b"", b'${VAULT}', hashlib.sha512).digest()
base64_bytes = base64.b64encode(hash_code)
base64_string = base64_bytes.decode("ascii")
print(base64_string)
END
)		 
	  else
		  error "-x" "/bin/python3 || /sbin/python3 || /bin/python || /sbin/python"
	  fi
	  
      # 2.3.- Dump Encrypted Password in Temp File
	  if [ -n "${PASSWORD}" ] ; then
         if [ -w "${TMP_FILE}" ] ; then 	  
           echo "${PASSWORD}" > "${TMP_FILE}"
           OUT="$?"
		 else
		   error "-w" "${TMP_FILE}"
		 fi 
	  fi

   else
     error "-w" "${TMP_PATH}"
   fi

   # 3.- Clean Local Environment
   #----------------
   unset PASSWORD TMP_PATH
}

#========================================================
#   Function: buildCommand
#--------------------------------------------------------
#  -Build Playbook Options
#========================================================
function buildCommand() {

        # 0.- Defaults
        #----------------------
        if [ -n "${TARGET}"      ] ; then local PTARGET="localhost,${TARGET}"         ; fi

        # 1.- Build Playbook Options
        #----------------------
        OPTIONS=''
		if [ -n "${DEBUG_ANSIBLE_FLAGS}" ] ; then OPTIONS="${DEBUG_ANSIBLE_FLAGS} " ; fi
        if [ -n "${INVENTORY}"      ] ; then OPTIONS="${OPTIONS} -i ${INVENTORY}"   ; fi
        if [ -n "${ADHOC_MODULE}"   ]  && [ ! "${ADHOC_MODULE}" == ' ' ] ; then 
		     OPTIONS="${OPTIONS} -m ${ADHOC_MODULE}"  
		     if [ -n "${ADHOC_CALL}" ] && [ ! "${ADHOC_CALL}" == ' ' ] ; then 
			    OPTIONS="${OPTIONS} -a '${ADHOC_CALL}'" 
			 fi 	 
		elif [ -n "${ADHOC_CALL}" ] ; then 
		     OPTIONS="${OPTIONS} --list-hosts"		 
	    fi		
        if [ -n "${PTARGET}"        ] ; then OPTIONS="${OPTIONS} -l ${PTARGET}"     ; fi
		if [ -n "${FLUSH_CACHE}"    ] ; then OPTIONS="${OPTIONS} --flush-cache"     ; fi
        if [ -n "${EXTRA_VARS}"     ] ; then OPTIONS="${OPTIONS} -e ${EXTRA_VARS}"  ; fi	
        if [ -n "${TAGS}"           ] ; then OPTIONS="${OPTIONS} --tags ${TAGS}"  ; fi
        if [ -n "${VAULT}"          ] ; then
             vaultPass "/tmp/"
             OPTIONS="${OPTIONS} --vault-password-file ${TMP_FILE}"
        fi
		
        OUT="$?"
		
        # 3.- Logging
        #----------------------
        if [ ! "${LOG}" == "/dev/null" ] ; then
           echo "........ INVENTORY=[${INVENTORY}]"
           echo "........... TARGET=[${PTARGET}]"
           echo "............. TAGS=[${TAGS}]"		   
           echo "............ VAULT=[${VAULT}]"
           echo "....... EXTRA_VARS=[${EXTRA_VARS}]"
           echo "..... ADHOC_MODULE=[${ADHOC_MODULE}]"
           echo "....... ADHOC_CALL=[${ADHOC_CALL}]"
        fi
}

#===================================================
#   Function: shootPlaybook
#---------------------------------------------------
#  Private Function
#
#  Shoot Playbook not depending on enviromental parameters
#===================================================
function shootPlaybook() {
   if [ -r "${PLAYBOOK}" ] ; then
   
      if [ -x /opt/stack/bifrost/bin/ansible-playbook ] ; then
          if [ -n "${RUN_BACKGROUND}" ] ; then
            echo "[${TIMESTAMP}] : nohup /opt/stack/bifrost/bin/ansible-playbook ${OPTIONS} ${PLAYBOOK}  > ${LOG}.nohup &"
            nohup /opt/stack/bifrost/bin/ansible-playbook ${OPTIONS} ${PLAYBOOK}  > "${LOG}.nohup" 2>&1 &
			unset PLAYBOOK 
          else
            echo "[${TIMESTAMP}] : /opt/stack/bifrost/bin/ansible-playbook ${OPTIONS} ${PLAYBOOK} "
            /opt/stack/bifrost/bin/ansible-playbook ${OPTIONS} ${PLAYBOOK}
			unset PLAYBOOK
			state_status "${CALL}"
          fi   
       elif [ -x /usr/bin/ansible-playbook ] ; then
          if [ -n "${RUN_BACKGROUND}" ] ; then
             echo "[${TIMESTAMP}] : /usr/bin/ansible-playbook ${OPTIONS} ${PLAYBOOK} &"
             nohup /usr/bin/ansible-playbook ${OPTIONS} ${PLAYBOOK} > "${LOG}.nohup" 2>&1 &
	         unset PLAYBOOK
          else
             echo "[${TIMESTAMP}] : /usr/bin/ansible-playbook ${OPTIONS} ${PLAYBOOK} "
             /usr/bin/ansible-playbook ${OPTIONS} ${PLAYBOOK}
			 unset PLAYBOOK 
			 state_status "${CALL}"
          fi
       elif [ -x /usr/sbin/ansible-playbook ] ; then
          if [ -n "${RUN_BACKGROUND}" ] ; then
             echo "[${TIMESTAMP}] : /usr/sbin/ansible-playbook ${OPTIONS} ${PLAYBOOK} &"
             nohup /usr/sbin/ansible-playbook ${OPTIONS} ${PLAYBOOK} > "${LOG}.nohup" 2>&1 & 
			 unset PLAYBOOK
          else
             echo "[${TIMESTAMP}] : /usr/sbin/ansible-playbook ${OPTIONS} ${PLAYBOOK} "
             /usr/sbin/ansible-playbook ${OPTIONS} ${PLAYBOOK} 
			 unset PLAYBOOK
			 state_status "${CALL}"
          fi
		  			
       elif [ -x /usr/bin/ansible-playbook-3 ] ; then
          if [ -n "${RUN_BACKGROUND}" ] ; then
             echo "[${TIMESTAMP}] : /usr/bin/ansible-playbook-3 ${OPTIONS} ${PLAYBOOK} &"
             nohup /usr/bin/ansible-playbook-3 ${OPTIONS} ${PLAYBOOK} > "${LOG}.nohup" 2>&1 &
			 unset PLAYBOOK
          else
             echo "[${TIMESTAMP}] : /usr/bin/ansible-playbook-3 ${OPTIONS} ${PLAYBOOK} "
             /usr/bin/ansible-playbook-3 ${OPTIONS} ${PLAYBOOK} 
			 unset PLAYBOOK
			 state_status "${CALL}"
          fi
	   
       elif [ -x /usr/sbin/ansible-playbook-3 ] ; then
          if [ -n "${RUN_BACKGROUND}" ] ; then
            echo "[${TIMESTAMP}] : /usr/sbin/ansible-playbook-3 ${OPTIONS} ${PLAYBOOK} &"
            nohup /usr/sbin/ansible-playbook-3 ${OPTIONS} ${PLAYBOOK} > "${LOG}.nohup" 2>&1 &
			unset PLAYBOOK 
          else
            echo "[${TIMESTAMP}] : /usr/sbin/ansible-playbook-3 ${OPTIONS} ${PLAYBOOK} "
            /usr/sbin/ansible-playbook-3 ${OPTIONS} ${PLAYBOOK}
			unset PLAYBOOK
			state_status "${CALL}"
          fi
       else
          echo "ANSIBLE INSTALLATION NOT FOUND: please try to REFRESH iDAS build installation (option 1)"
          error "-x" "ansible-playbook/ansible-playbook-3"
       fi
       OUT="$?"
	   
   else
     echo -e "${COLOR[$YELLOW]} [WARN] - GENESIS INSTALLATION FAILURE: ${COLOR[$NC]} please try to REFRESH Genesis installation (option 1)"
     error "-r" "${PLAYBOOK}"
   fi
   
   unset OPTIONS PLAYBOOK
}

#===================================================
#   Function: detectBackgroundExecution
#---------------------------------------------------
#  Private Function
#
#  Detect Background execution
#===================================================
detectBackgroundExecution() {
   local INPUT=$( echo "${RUN_BACKGROUND}" | tr '[:upper:]' '[:lower:]' )
   case "${INPUT}" in
       "s"|"si"|"y"|"yes" ) echo '---> Run Playbook in Background'
	   ;;
	  *) unset RUN_BACKGROUND 
	    ;;
   esac
}

#===================================================
#   Function: setupCommand
#---------------------------------------------------
#  Private Function
#
#  Detect Background execution
#===================================================
function setupCommand() {
   local TIMESTAMP=$(date -R)
   detectBackgroundExecution
   if [ -n "${GENESIS_PROJECT_ANSIBLE_CFG}" ] ; then
      echo  "[$TIMESTAMP] -> export ANSIBLE_CONFIG=${GENESIS_PROJECT_ANSIBLE_CFG}"    
      export ANSIBLE_CONFIG="${GENESIS_PROJECT_ANSIBLE_CFG}"
   fi
   
   if [ -n "${GENESIS_VIRTUAL_ENVIRONMENT}" ] ; then
       echo "[$TIMESTAMP] -> source ${GENESIS_VIRTUAL_ENVIRONMENT}"
       source "${GENESIS_VIRTUAL_ENVIRONMENT}"
       echo "-> echo source ${GENESIS_VIRTUAL_ENVIRONMENT} > $HOME/env.sh"
       echo "source ${GENESIS_VIRTUAL_ENVIRONMENT}" > "$HOME/env.sh"
   fi
   
   if [ -n "${IRONIC_CLOUD}" ] ; then
       echo "[$TIMESTAMP] -> export OS_CLOUD=${IRONIC_CLOUD}"
       export OS_CLOUD="${IRONIC_CLOUD}"
       echo "[$TIMESTAMP] -> echo export OS_CLOUD=${IRONIC_CLOUD} >> $HOME/env.sh"
       echo "export OS_CLOUD=${IRONIC_CLOUD}" >> "$HOME/env.sh"
   fi 
   
   echo "[$TIMESTAMP] -> export BIFROST_INVENTORY_SOURCE=${GENESIS_BIFROST_INVENTORY_SOURCE}"
   export BIFROST_INVENTORY_SOURCE="${GENESIS_BIFROST_INVENTORY_SOURCE}" 
}

#===================================================
#   Function: shootAdhoc
#---------------------------------------------------
#  Private Function
#
#  Shoot AdHoc ansible command
#===================================================
function shootAdhoc() {

   # 0.- Trace Entry
   if [ ! -n "${ATARGET}" ] ; then  local ATARGET="all" ; fi
   if [[ ! "${LOG}" == "/dev/null" ]] ; then
      echo "[${TIMESTAMP}] :  ansible  ${OPTIONS} ${ATARGET}"
   fi
   
   # 1.- Shoot Ad-Hoc Command
   if   [ -x /opt/stack/bifrost/bin/ansible ] ; then
        echo $OPTIONS
        /opt/stack/bifrost/bin/ansible  ${OPTIONS} ${ATARGET}
   elif [ -x /usr/bin/ansible    ] ; then
        /usr/bin/ansible ${ATARGET} ${OPTIONS} 
   elif [ -x /usr/sbin/ansible   ] ; then
         /usr/sbin/ansible ${ATARGET} ${OPTIONS} 		 
   elif [ -x /usr/bin/ansible-3  ] ; then
        /usr/bin/ansible-3 ${ATARGET} ${OPTIONS} 
   elif [ -x /usr/sbin/ansible-3 ] ; then
       /usr/sbin/ansible-3 ${ATARGET} ${OPTIONS} 
   else
     echo -e "${COLOR[$YELLOW]} [WARN] - GENESIS INSTALLATION FAILURE: ${COLOR[$NC]} please try to REFRESH Genesis Node (option 1)"
     error "-x" "ansible ${ATARGET} ${OPTIONS}"
   fi	
   
   unset OPTIONS
}

#===================================================
#   Function: shootCommand
#---------------------------------------------------
#  Private Function
#
#  Shoot Playbook not depending on enviromental parameters
#===================================================
function shootCommand() {

   #--------------------
   #  LOCAL ENVIRONMENT
   #--------------------
   local LOG="${1}"    
   local LOG_PATH="${LOG%/*}"
   local LOG_NAME="${LOG##*/}"
   local TIMESTAMP=$(date -R)

   #--------------------
   #  ACTIONS
   #--------------------

   # 0.- Trace values
   if [[ ! "${LOG}" == "/dev/null" ]] ; then   
      echo "......... PLAYBOOK=[${PLAYBOOK}]"
      echo ".......... OPTIONS=[${OPTIONS}]"
      echo ".............. LOG=[${LOG}]"
   fi
   
   # 1.- Ansible Logging Options
   export ANSIBLE_LOG_PATH
   export ANSIBLE_ACTION_WARNINGS ANSIBLE_COMMAND_WARNINGS ANSIBLE_DEPRECATION_WARNINGS ANSIBLE_DEVEL_WARNING ANSIBLE_LOCALHOST_WARNING ANSIBLE_SYSTEM_WARNINGS
   if [ -w "${LOG_PATH}" ] ; then export ANSIBLE_LOG_PATH="${LOG}"  ; fi
   if [ -n "${DISABLE_WARNS}" ] ; then
      export ANSIBLE_ACTION_WARNINGS=false
      export ANSIBLE_COMMAND_WARNINGS=false
      export ANSIBLE_DEPRECATION_WARNINGS=false
      export ANSIBLE_DEVEL_WARNING=false
      export ANSIBLE_LOCALHOST_WARNING=false
      export ANSIBLE_SYSTEM_WARNINGS=false
   fi

   # 2.- Shoot Playbook
   if [ -n "${PLAYBOOK}" ] ; then
      shootPlaybook "${PLAYBOOK}"
      
   elif [ -n "${ADHOC_MODULE}" ] ; then
      shootAdhoc
   fi
   
}

#========================================================
#   Function: runPlaybook
#--------------------------------------------------------
#  -Run diferent playbooks with the options captured
#========================================================
function runPlaybook() {
   local LOG="${1}"
   if [ ! -n "${LOG}" ] ; then local LOG="${HOME}/nolog.log" ; fi     
   buildCommand
   setupCommand
   shootCommand "${LOG}"
   unset INVENTORY PTARGET SLOT VAULT EXTRA_VARS ADHOC_MODULE ADHOC_CALL
 
}

#========================================================
#   Function: runAdHoc
#--------------------------------------------------------
#  -Run diferent playbooks with the options captured
#========================================================
function runAdHoc() {
   local ADHOC_MODULE="${1}"
   local ADHOC_CALL="${2}"
   local LOG="${3}"
   if [ ! -n "${LOG}" ] ; then local LOG="/dev/null" ; fi  
   buildCommand
   setupCommand
   shootCommand "${LOG}"
   unset INVENTORY PTARGET SLOT VAULT EXTRA_VARS ADHOC_MODULE ADHOC_CALL
}

########################################################################################
# MODULE 6 - MENU ACTIONS
########################################################################################

#========================================================
#   Function: 0_call
#--------------------------------------------------------
#   Basic playbook call without special context
#========================================================
function 0_call() {
	
   #--------------------
   #  LOCAL ENVIRONMENT
   #--------------------	
    local CALL="${1}"   
    local PLAYBOOK="${GENESIS_PLAYBOOKS[${CALL}]}"
    #if [ ! -n "${INVENTORY}" ] ; then local INVENTORY="${genesis_DEFAULT_INVENTORY}" ; fi	
	local CALL_LOG="${HOME}/${CALL}.log"
    if [ -n "${LOG_FILE}" ] ; then local CALL_LOG="${LOG_FILE}"   ; fi
    
   #--------------------
   #  ACTIONS
   #--------------------	
   # 1.- Trace Entry
   echo -e '------------------------------------------------------------------------------------------------------'
   echo -e "    [${IRONIC_BAREMETAL_NODES}] -  ${GENESIS_PLAYBOOKS_HEADER[${CALL}]} - #${PLAYBOOK}#"
   echo -e '------------------------------------------------------------------------------------------------------'
   echo -e "${COLOR[$SEA]}----> To run Ironic commands:${COLOR[$NC]}"
   echo -e "${COLOR[$SEA]}. $HOME/env.sh${COLOR[$NC]}"
   echo -e "${COLOR[$SEA]}baremetal node list${COLOR[$NC]}"
   # 2.- Run Playbook
   runPlaybook "${CALL_LOG}"

   # 4.- Clean Environments 
   echo "Removing Temporal Files... rm -f ${TMP_FILE}"
   rm -f "${TMP_FILE}" 2> /dev/null
   unset PLAYBOOK TMP_FILE CALL LOG_FILE 
}	 

#========================================================
#   Function: 1_refresh
#--------------------------------------------------------
#  - Remove iDAS files from /mnt
#  - Untar iDAS build in /mnt
#  - Remove iDAS packages
#  - Create Yum Repositories for iDAS installation
#  - Install iDAS RPM packages
#  - Check Status "iDAS-1: Installed"
#========================================================
function 1_refresh() {
      
   #--------------------
   #  ACTIONS
   #--------------------
   # 1.- load Configuration
   prepareLocalMachine
   
   # 2.- Call
   if [ ! -n "${ONLINE}" ] ; then
      #local INVENTORY="${GENESIS_TARGET_INVENTORY_SOURCE}" 
      local EXTRA_VARS="genesis_stage='G1'"	  
      0_call "${REFRESH}" 
   fi  
   
   # 3.- Clean environment
   unset PXE_DHCP_IP PXE_DHCP_NIC CNF_REEMPLAZO CNF_SEPARADOR_CAMPO
   echo -e '......................................................................................................'
   echo -e "   BEWARE !!!! ====> Don't forget DEPLOY (option 2) and SETUP (option 4) iDAS"
   echo -e '......................................................................................................'
}

#========================================================
#   Function: 2_create
#--------------------------------------------------------
#  - Load String Data Model
#  - Run installPxe playbook
#========================================================
function 2_create() {

   #--------------------
   #  LOCAL ENVIRONMENT
   #--------------------
   local EXTRA_VARS="genesis_stage='G2'"
   local FLUSH_CACHE="yes"
   if [ -n "${network_interface}" ] ; then PXE[${DHCP_NIC}]="${network_interface}"      ; fi
   if [ -n "${dhcp_address}" ] ; then PXE[${DHCP_IP}]=$( echo "$dhcp_address" | tr -d \/  |  tr '\' '/' )    ; fi
   if [ -n "${dhcp_pool_start}"   ] ; then PXE[${DHCP_POOL_START}]="${dhcp_pool_start}" ; fi
   if [ -n "${dhcp_pool_end}"     ] ; then PXE[${DHCP_POOL_END}]="${dhcp_pool_end}"     ; fi
   #DISABLE_WARNS="Yes"
   
   #--------------------
   #  ACTIONS
   #--------------------  
   # 1.- Load Configurations
   enableIronicNetworkInterface
   addGenesisToHosts
   
   # 2.- Call
   #local INVENTORY="${GENESIS_TARGET_INVENTORY_SOURCE}"
   0_call "${CREATE}"
      
   # 3.- Clean Environemnt
   unset LOG_FILE CNF_REEMPLAZO CNF_SEPARADOR_CAMPO
   
   echo -e '......................................................................................................'
   echo -e "   BEWARE !!!! ====> Don't forget SETUP (option 4) iDAS"
   echo -e '......................................................................................................'
}


#========================================================
#   Function: 3_init
#--------------------------------------------------------
#  - Create OS Image
#  - Load OS Image to Ironic
#========================================================
function 3_init() {

   local EXTRA_VARS="genesis_stage='G3'"   
   prepareImageCreation
   0_call "${INIT}" 
   unset LOG_FILE 
}

#========================================================
#   Function: 4_setup
#--------------------------------------------------------
#  - Enroll Nodes to Ironic
#========================================================
function 4_setup() {
   updateInventory
   local INVENTORY="${IRONIC_BIFROST_DYNAMIC_INVENTORY}"
   local EXTRA_VARS="genesis_stage='B4'"   
   0_call "${SETUP}" 
   unset IRONIC_BAREMETAL_NODES LOG_FILE
}

#========================================================
#   Function: 5_deploy
#--------------------------------------------------------
#  - Enroll Nodes to Ironic
#========================================================
function 5_deploy() {
   local INVENTORY="${IRONIC_BIFROST_DYNAMIC_INVENTORY}"  
   local EXTRA_VARS="genesis_stage='B5'"      
   0_call "${DEPLOY}" 
   unset TARGET LOG_FILE
}


#========================================================
#   Function: 6_ansible
#--------------------------------------------------------
#  - Prepare Ansible SSH Relationships
#========================================================
function 6_ansible() {
   echo -e '------------------------------------------------------------------------------------------------------'
   echo -e "   [${IRONIC_BAREMETAL_NODES}] - [BAREMETAL] - ANSIBLE     : Ansible Initial Setup "
   echo -e '------------------------------------------------------------------------------------------------------'
   if [ -n "${LOG_FILE}"    ] ; then local CALL_LOG="${LOG_FILE}" ; fi
   trust_relationships "${NODE_LIST}"
   state_status "6"
}

#========================================================
#   Function: 7_provision
#--------------------------------------------------------
#  - Enroll Nodes to Ironic
#========================================================
function 7_provision() {
   local EXTRA_VARS="genesis_stage='B6'"      
   0_call "${PROVISION}" 
   unset TARGET LOG_FILE
}

#========================================================
#   Function: 8_plugins
#--------------------------------------------------------
#  - Shoot Plugins
#========================================================
function 8_plugins() {
    local PLUGIN="${1}"
	
	# 1.- Install RPM
	if [ ! -r "${GENESIS_PLAYBOOKS[${PLUGIN}]}" ] ; then
       local  PACKAGES=( ${GENESIS_PLUGINS_RPM[${PLUGIN}]} )	
       installDependencies
	fi
	
	# 2.- Shoot Plugin
	if [ -r "${GENESIS_PLAYBOOKS[${PLUGIN}]}" ] ; then 
	   0_call "${PLUGIN}"
	fi
	
	# 3.- Clean Environment 
	unset LDAP_TYPE LDAP_GROUP_MACHINES LDAP_DATA TAGS VAULT INVENTORY TARGET LOG_FILE GROUP_MACHINES
}

#========================================================
#   Function: 22_gathering
#--------------------------------------------------------
#  - Run gathering String configuration files
#========================================================
function 22_gathering() {
   if [ -n "${GATHERING_FOLDER}" ] ; then local EXTRA_VARS="gathering_folder=${GATHERING_FOLDER}"   ; fi
   0_call "${GATHER}"
   unset EXTRA_VARS
}

#========================================================
#   Function: runActions
#--------------------------------------------------------
#  Execute Menu actions
#========================================================
function runActions() {

    local ACTION="$1" 
    case "${ACTION}" in
        1|"${GENESIS_PLAYBOOKS_HEADER[${REFRESH}]}") 1_refresh ;;
        2|"${GENESIS_PLAYBOOKS_HEADER[${CREATE}]}")  2_create  ;;
        3|"${GENESIS_PLAYBOOKS_HEADER[${INIT}]}")    3_init    ;;
        4|"${GENESIS_PLAYBOOKS_HEADER[${SETUP}]}")   4_setup   ;;
        5|"${GENESIS_PLAYBOOKS_HEADER[${DEPLOY}]}")  5_deploy  ;;
        6|"${COLOR[$SILVER]}[BAREMETAL] - ANSIBLE (pre-ready): Ansible Initial Setup${COLOR[$NC]}") 6_ansible ;;		
        7|"${GENESIS_PLAYBOOKS_HEADER[${PROVISION}]}") 7_provision ;;
        12|"${GENESIS_PLAYBOOKS_HEADER[${LDAP}]}")     8_plugins "${LDAP}"   ;;
        13|"${GENESIS_PLAYBOOKS_HEADER[${TESTING}]}")  8_plugins "${TESTING}" ;;
        14|"${GENESIS_PLAYBOOKS_HEADER[${SSH_MAP}]}")  0_call "${SSH_MAP}"   ;;
        15|"${GENESIS_PLAYBOOKS_HEADER[${GRAPHICS}]}") 0_call "${GRAPHICS}"  ;;
        16|"${GENESIS_PLAYBOOKS_HEADER[${NETWORK}]}")  0_call "${NETWORK}"   ;;
        17|"${GENESIS_PLAYBOOKS_HEADER[${NTP}]}")      0_call "${NTP}"       ;;
	    22|"${GENESIS_PLAYBOOKS_HEADER[${GATHER}]}")  22_gathering           ;;
    esac
}

########################################################################################
# MODULO 7 => MENU SYSTEM
########################################################################################

#========================================================
#   Function: initParameters
#--------------------------------------------------------
#   Set all parameters to Run Direct Action
#========================================================
function initParameters() {
  
   local ACTION="$1"
   
   # => 1.- Set common default values
   if [ ! -n "${LOG_FILE}"  ] ; then LOG_FILE="${HOME}/tests.log"     ; fi
   INVENTORY=$(echo ${INVENTORY} | tr -d ' ' )
   PROJECT_NAME=$(echo ${PROJECT_NAME} | tr -d ' ' | tr [:lower:] [:upper:] )
   TARGET=$(echo ${TARGET} | tr -d ' ' )
   LOG_FILE=$(echo ${LOG_FILE} | tr -d ' ' )
   
   # => 2.- Set Default Action Values
   case "${ACTION}" in
     1|"${COLOR[$ORANGE]}[iDAS]   - REFRESH     : Reinstall iDAS Build${COLOR[$NC]}")
	   if [ ! -n "${genesis_BUILD}" ] ; then genesis_BUILD=$(ls -1 /mnt/build*.tgz | head -1 2> /dev/null)  ; fi
	   genesis_BUILD=$(echo ${genesis_BUILD} | tr -d ' ' )   
	 ;;
     3|"${COLOR[$SILVER]}[iDAS]   - LOAD (pre-setup): load String configuration files${COLOR[$NC]}")
	   if [ ! -n "${CFGS_CORE}" ] ; then CFGS_CORE=$(ls -1 -d ${genesis_CFGS_PATH}/* | head -1 2> /dev/null)  ; fi
	   CFGS_CORE=$(echo ${CFGS_CORE} | tr -d ' ' )
     ;;	 
     4|"${GENESIS_PLAYBOOKS_HEADER[${SETUP}]}")
       if [[ "${PROJECT_NAME}" == "LVNL" ]] ; then 
          if [ ! -n "${SLOT}"      ] ; then SLOT="1"     ; fi
          if [ ! -n "${VAULT}"     ] ; then VAULT="root" ; fi
          SLOT=$(echo ${SLOT} | tr -d ' ' )
          VAULT=$(echo ${VAULT} | tr -d ' ' )
       fi	 
	 ;;	
     12|"${GENESIS_PLAYBOOKS_HEADER[${LDAP}]}") 
       if [ ! -n "${VAULT}" ] ; then VAULT="trufa"  ; fi	 
       if [ ! -n "${LDAP_DATA}" ] ; then LDAP_DATA="pv3"  ; fi	    
       if [ ! -n "${LDAP_TYPE}" ] ; then LDAP_TYPE="idm"  ; fi
       if [ ! -n "${LDAP_GROUP_MACHINES}" ] ; then LDAP_GROUP_MACHINES="iss_group"  ; fi
	   VAULT=$(echo ${VAULT} | tr -d ' ' )
       LDAP_TYPE=$(echo ${LDAP_TYPE} | tr -d ' ' | tr [:upper:] [:lower:]  )
       LDAP_DATA=$(echo ${LDAP_DATA} | tr -d ' ' | tr [:upper:] [:lower:]  )
       LDAP_GROUP_MACHINES=$(echo ${LDAP_GROUP_MACHINES} | tr -d ' ' | tr [:upper:] [:lower:]  )	  	   
	 ;;
     13|"${GENESIS_PLAYBOOKS_HEADER[${TESTING}]}")	
       if [ ! -n "${GROUP_MACHINES}" ] ; then GROUP_MACHINES="iss_group"  ; fi
       GROUP_MACHINES=$(echo ${GROUP_MACHINES} | tr -d ' ' | tr [:upper:] [:lower:]  )	   
	 ;;
   esac

   # => 4.- Avoid startMenu
   unset MENU
}


#========================================================
#   Function: startMenu
#--------------------------------------------------------
#   Run the menu system
#========================================================
function startMenu() {

    # 0.- Trazado Inicial
    #--------------------
    echo -e "${COLOR[$SILVER]}*********************************************************************************${COLOR[$NC]}"
    echo -e "${COLOR[$SILVER]}               WELCOME TO GENESIS PROVISIONING SYSTEM !!!!!! ${COLOR[$NC]}"
    echo -e "${COLOR[$SILVER]}---------------------------------------------------------------------------------${COLOR[$NC]}"
    echo -e "${COLOR[$SILVER]}  -> New Features Requests: Cesar Delgado (cesar.electronic.engineer@gmail.com) ${COLOR[$NC]}"
    echo -e "${COLOR[$SILVER]}*********************************************************************************${COLOR[$NC]}"

    # 1.- Menu System
    #--------------------
    while [ -n "${MENU}" ] ; do

         # 1.1.- Interactive Menu 
         defineMenu	 
         deployMenu "${REEMPLAZA_LINEA_CNF}"

         # 1.2.- Actions (menu = 2 loops: display + parameters, it must be avoided runAction twice)
         if [ -n "${RUN_ACTION}"     ] ; then runActions "${RUN_ACTION}" ; fi
         if [ -n "${RETURNING_MENU}" ] ; then MENU="${RETURNING_MENU}"   ; fi

         # 1.3.- Clean Loop Environment
         unset  MENU_TEXT SOLICITA_PARAMETRO PARAMETRO VALOR_DEFECTO RUTA_OPCIONES EXT_OPCIONES RUN_ACTION RETURNING_MENU MENU_SKIP_PATHS MENU_BREAK_TEXT CALL_LOG

    done
}

########################################################################################
# MAIN
########################################################################################
if [ -w "/dev/null" ] ; then

    # ..... Move to home folder in order to avoid REFRESH issues
    if [ -w "${HOME}" ] ; then
         cd "${HOME}"
    else
         error -w "${HOME}"
    fi

    # ..... Load Context + Start Menu System
    if [ -O "./" ] ; then

		#=========================
		# ENVIRONMENT
		#=========================
		OUT_TMP="/tmp/reemplazo.out"
		MENU="0"

		#=============================
		# CAPTURE COMMAND FLAGS
		#=============================
		while getopts "hHRDLSKAPIQMGNTi:t:a:v:g:s:e:l:b:p:d:u:m:" OPCION ; do
			case "$OPCION" in
				h|H)   ayuda ; exit 1 ;;
				R)   RUN_ACTION="1"  ; unset MENU ;;
				D)   RUN_ACTION="2"  ; unset MENU ;;
				L)   RUN_ACTION="3"  ; unset MENU ;;
				S)   RUN_ACTION="4"  ; unset MENU ;;
				K)   RUN_ACTION="5"  ; unset MENU ;;
				A)   RUN_ACTION="6"  ; unset MENU ;;
				P)   RUN_ACTION="7"  ; unset MENU ;;
				I)   RUN_ACTION="12" ; unset MENU ;;
				Q)   RUN_ACTION="12" ; unset MENU ;;				
				M)   RUN_ACTION="14" ; unset MENU ;;
				G)   RUN_ACTION="15" ; unset MENU ;;
				N)   RUN_ACTION="16" ; unset MENU ;;
				T)   RUN_ACTION="17" ; unset MENU ;;
                i)   if [ -n "$OPTARG" ] ; then INVENTORY="$OPTARG"  ; fi ;;
                t)   if [ -n "$OPTARG" ] ; then TARGET="$OPTARG"     ; fi ;;
                a)   if [ -n "$OPTARG" ] ; then TAGS="$OPTARG"       ; fi ;;				
                v)   if [ -n "$OPTARG" ] ; then VAULT="$OPTARG"      ; fi ;;
                g)   if [ -n "$OPTARG" ] ; then CFGS_CORE="$OPTARG"  ; fi ;;
                s)   if [ -n "$OPTARG" ] ; then SLOT="$OPTARG"       ; fi ;;
                e)   if [ -n "$OPTARG" ] ; then EXTRA_VARS="$OPTARG" ; fi ;;
                l)   if [ -n "$OPTARG" ] ; then LOG_FILE="$OPTARG"   ; fi ;;
                b)   if [ -n "$OPTARG" ] ; then genesis_BUILD="$OPTARG" ; fi ;;
                p)   if [ -n "$OPTARG" ] ; then PROJECT_NAME="$OPTARG" ; fi ;;
                d)   if [ -n "$OPTARG" ] ; then LDAP_DATA="$OPTARG" ; fi ;;
                u)   if [ -n "$OPTARG" ] ; then LDAP_TYPE="$OPTARG" ; fi ;;					
                m)   if [ -n "$OPTARG" ] ; then 
				        GROUP_MACHINES="$OPTARG" 
						LDAP_GROUP_MACHINES="$OPTARG" 
					 fi 
					 ;;
				[?]) ayuda ;; # Unknown parameter
			esac
		done
		
		#=============================
		# ACTIONS
		#=============================
        
		# 0.- Set Script Environemt 
        detectOS
        setEnvironment

        # 1.- Direct Action
        if [ -n "${RUN_ACTION}"     ] ; then
            initParameters "${RUN_ACTION}"
	        state_status "genesis_machine_ready" 2>&1 > "${LOG_FILE}"
            runActions     "${RUN_ACTION}"    2>&1 >>"${LOG_FILE}"
        fi

        # 2.- Menu System
        if [ -n "${MENU}" ] ; then
		   state_status "genesis_machine_ready"
		   startMenu 
		fi

        # 4.- Exit
		exit "$OUT"
	else
		error -noOwner "./"
        exit "$ERROR"
	fi
else
	error -noWrite "/dev/null"
    exit "$ERROR"
fi
#=======================================================================================================
#  END GENESISCLI.SH
#=======================================================================================================
