- name: "STEP 5 - Download ORAS tarball"
  get_url:
     url: "{{ oras_download_url }}"
     dest: "{{ genesis_files_path }}/openstack/{{oras_tarball_name}}"
     checksum: "sha256:{{ oras_checksum }}"
     mode: '0644'