---
# tasks file for genesis.refresh
- name: "------------------> REFRESH GENESIS NODE <------------------" 
  block:
    - name: "REFRESH"
      ansible.builtin.include_tasks: "{{ genesis_refresh_stage | default ('1_repos.yml') }}"
      loop:
         - "1_repos.yml"
         - "2_git.yml"
         - "3_os.yml"
         - "4_ipa.yml"
         - "5_ora.yml"
         - "6_setup.yml"        
      loop_control:
        loop_var: "genesis_refresh_stage"
        
  rescue:
    - name: "------------------> REFRESH GENESIS NODE - Error"
      debug:
        msg:
        - "Possible errors:"