---
# Versioning: https://releases.openstack.org/
openstack_version:
  openstacksdk:
     "stable/2025.2": "4.7.2"
  diskimage-builder:
     "stable/2025.2": "3.42.0"
  ironic :
     "stable/2025.2": "32.0.1"
     "stable/2026.1": "32.0.1"
     "stable/2026.2": "32.0.1"
  ironic-inspector:
     "stable/2025.2": "12.5.0"
  ironic-python-agent:
     "stable/2025.2": "11.2.0"
  ironic-python-agent-builder:
     "stable/2025.2": "6.2.0"
  ironic-prometheus-exporter:
     "stable/2025.2": "4.6.0"
  ironic-staging-drivers:
     "stable/2025.2": "0.11.0"   
  python-ironic-inspector-client:
     "stable/2025.2": "5.4.0"
  python-ironicclient:
     "stable/2025.2": "5.13.1"  
     
