---
# all.ymnl
#
#  - Local Repo Creation from Listed Sources
#  
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0
#

#-------------------------
# 1.- Checksums 
#-------------------------
genesis_local_checksum_file:
  path: "{{ genesis_repo_path | realpath }}/checksum"
  content: |
   aef4855862bffea1086d59becf67fbe10c90d3d2a21fd74a01770eb75d138ac8 *fedora-coreos-44.20260913.3.2-live-iso.x86_64.iso
   6a728775cde8cdc5a68de2b1db9ed9a73e2d3a37dc79a6bbc1fb12c075a70fac *fedora-coreos-44.20260913.3.2-live-initramfs.x86_64.img 
   fc48ea53cf994d2f2e4e3969824a643498b31d9be5540270a53040159a874820 *fedora-coreos-44.20260913.3.2-live-kernel.x86_64
   f453f83d177fde78ee2630f5769a8c8458137065a67bfa3bff879f27bf0cadaf *fedora-coreos-44.20260913.3.2-live-rootfs.x86_64.img
   3c0ace903c0a78b13a09d5649ffc4409370f6d8dab2a79fea310b20ac20a2ac2 *Leap-16.0-offline-installer-x86_64-Build178.27.install.iso
genesis_local_checksum_url: "file://{{ genesis_local_checksum_file.path }}"

#-------------------------
# 2.- Local Repo Sources
#-------------------------
genesis_download_images:

   #-----------------------------------
   # Server OS
   #-----------------------------------
  - distribution: "CentOS"
    distribution_version: "9"
    distribution_arch: "x86_64"
    os_image_name: "x86_64.iso"
    extract_ramdisk: yes
    mount: yes

  - distribution: "Ubuntu"
    distribution_version: "24.04"
    distribution_version_minor: "5"
    distribution_arch: "amd64"
    os_image_name: "x86_64.iso" 
    extract_ramdisk: yes
    mount: yes

  - distribution: "Debian"
    distribution_version: "13.7"
    distribution_arch: "amd64"
    os_image_name: "netboot.iso"  
    latest: yes # Debian URLs: current / historical Repository
    installer: 'cd'
    netinstall_ramdisk: "mini"
    extract_ramdisk: yes
    mount: yes

  - distribution: "Debian"
    distribution_version: "13.7"
    distribution_arch: "amd64"
    os_image_name: "x86_64.iso" 
    latest: yes # Debian URLs: current / historical Repository
    mount: yes

    # SuSE 16 has different Product Name (for Amanda Installer) / ISO Name (for URL download) 
    #   Alias for Amanda Installer is a must => URL [ALIAS] pattern replacement will fail 
  - distribution: "SuSE"
    distribution_version: "16.0"
    distribution_minor: "Build178.27"
    distribution_arch: "x86_64"
    os_image_name: "x86_64.iso"
    image: "https://download.opensuse.org/distribution/leap/16.0/offline/Leap-16.0-offline-installer-x86_64-Build178.27.install.iso"
    extract_ramdisk: yes
    mount: yes

   #-----------------------------------
   # Cluster OS
   #-----------------------------------
  - distribution: "CoreOS"
    distribution_version: "44"
    distribution_version_minor: "20260913.3.2"
    distribution_arch: "x86_64"
    os_image_name: "x86_64.iso"

  - distribution: "CoreOS"
    distribution_version: "44"
    distribution_version_minor: "20260913.3.2"
    distribution_arch: "x86_64"
    os_image_name: "vmlinuz" 
    installer: 'kernel'


  - distribution: "CoreOS"
    distribution_version: "44"
    distribution_version_minor: "20260913.3.2"
    distribution_arch: "x86_64"
    os_image_name: "initrd"
    installer: 'ramdisk'

  - distribution: "CoreOS"
    distribution_version: "44"
    distribution_version_minor: "20260913.3.2"
    distribution_arch: "x86_64"
    os_image_name: "install.img"
    installer: 'rootfs'

   #-----------------------------------
   # QCOWs for Cloud OS Installers
   #-----------------------------------
  - distribution: "CentOS"
    distribution_version: "9"
    os_image_name: "partition.qcow2"
    installer: 'qcow'

#-------------------------
# 3.- OpenStack Versioning
#-------------------------
# Versioning: https://releases.openstack.org/
openstack_version:
  openstacksdk:
     "stable/2025.2": "4.7.2"
  diskimage-builder:
     "stable/2025.2": "3.42.0"
  ironic :
     "stable/2025.2": "32.0.1"
     "stable/2026.1": "32.0.1"
     "stable/2026.2": "32.0.1"
  ironic-inspector:
     "stable/2025.2": "12.5.0"
  ironic-python-agent:
     "stable/2025.2": "11.2.0"
  ironic-python-agent-builder:
     "stable/2025.2": "6.2.0"
  ironic-prometheus-exporter:
     "stable/2025.2": "4.6.0"
  ironic-staging-drivers:
     "stable/2025.2": "0.11.0"   
  python-ironic-inspector-client:
     "stable/2025.2": "5.4.0"
  python-ironicclient:
     "stable/2025.2": "5.13.1"  
     
