---
# genesis.deploy main.yml
#   - Node Lifecycle Stage 1 - Clean
#   - Node Lifecycle Stage 2 - Deploy
#   - Node Lifecycle Stage 3 - Active
#  
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0
#

#-----------------------
# 1.- Clean Disks
#-----------------------
- name: "------------------> B5- DEPLOY BAREMETAL NODE <------------------" 
  when: 
    - b5_baremetal_vars_file is defined
    - b5_baremetal_vars_file is not none
    - b5_baremetal_vars_file is string
    - b5_baremetal_vars_file is not mapping
    - b5_baremetal_vars_file | length > 0
    - lookup('ansible.builtin.file', b5_baremetal_vars_file, errors='ignore') is not none
  block:
    - name: "B5 - DEPLOY - Cargar el modelo de datos guardado del nodo"
      ansible.builtin.include_vars:
        file: "{{ b5_baremetal_vars_file }}"
    - ansible.builtin.include_tasks: "1_clean/1_partition_table.yml"

#-----------------------
# 2.- Deploy Instance
#-----------------------
- name: "------------------> B5- DEPLOY BAREMETAL NODE <------------------" 
  when: 
    - b5_baremetal_vars_file is defined
    - b5_baremetal_vars_file is not none
    - b5_baremetal_vars_file is string
    - b5_baremetal_vars_file is not mapping
    - b5_baremetal_vars_file | length > 0
    - lookup('ansible.builtin.file', b5_baremetal_vars_file, errors='ignore') is not none
  block:
    - name: "B5 - DEPLOY - Cargar el modelo de datos guardado del nodo"
      ansible.builtin.include_vars:
        file: "{{ b5_baremetal_vars_file }}"
    - ansible.builtin.include_tasks: "2_deploy/1_instance.yml"
  delegate_to: "{{ groups['target'][0] if groups['target'] is defined else 'localhost' }}"
  
    
#-----------------------
# 3.- Activate Instance
#----------------------- 
#- name: "B5 - DEPLOY - Stage 3:  Active - HeartBeat, Network Connection, Hardware Configuration"
#  ansible.builtin.include_tasks: "{{ b5_active | default ('3_active/1_hearbeat.yml') }}"
#  loop:
#     - "3_active/1_hearbeat.yml"
#     - "3_active/2_hardware.yml"		 
#     - "3_active/3_network.yml"
#  loop_control:		 
#    loop_var: "b5_active"