---
# genesis.setup 2_lifecycle/5_deploy.yml
#   - Bootloader Rendering
#   - OS Installer Properties
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0
#

- name: "STEP 4 - Set Instance Information"
  shell:
     cmd: "{{command | default('ls') }}"
  vars:
     node_uuid: "{{ uuid | default(' ') }}"
     node_name: "{{ name | default(' ') }}"
     node_image_source: "{{ instance_info.image_source | default('') }}"
     #node_image_type: "{{ node.value.instance_info.image_type | default('whole_disk') }}"
     node_image_source_name: "{{node_image_source | basename | default('') }}"
     node_image_os_hash_value: "{{ instance_info.image_os_hash_value | default('') }}"
     node_image_os_hash_algo: "{{ instance_info.image_os_hash_algo | default('sha256') }}"
     node_image_source_localpath: "{{bifrost_repo}}/{{node_image_source_name}}"
     node_boot_iso: "{{ instance_info.boot_iso |  default('') }}"
     node_ks_template: "{{ instance_info.ks_template |  default('') }}"
     node_boot_interface: "{{ instance_info.boot_interface |  default('ipxe') }}"
     node_deploy_interface: "{{ instance_info.deploy_interface |  default('direct') }}"
     node_kernel: "{{ instance_info.kernel |  default('') }}"
     node_ramdisk: "{{ instance_info.ramdisk |  default('') }}"
     command_create: |
       . /opt/stack/bifrost/bin/activate
       export OS_CLOUD=bifrost
       baremetal allocation create --name {{node_name}} --resource-class baremetal --wait
       baremetal node set {{node_uuid}} --boot-interface {{node_boot_interface}}
       baremetal node set {{node_uuid}} --deploy-interface {{node_deploy_interface}}
       baremetal node set secure boot off {{node_uuid}}          
     command_image: |
       . /opt/stack/bifrost/bin/activate
       export OS_CLOUD=bifrost
       if [ -n '{{node_image_source}}' ] ; then
          baremetal node set {{node_uuid}} --instance-info image_source="{{node_image_source}}"
       fi    
     command_hash: |
       . /opt/stack/bifrost/bin/activate
       export OS_CLOUD=bifrost
       if [ -n '{{node_image_source}}' ] ; then
          if [ -n '{{ node_image_os_hash_value }}' ] ; then
             baremetal node set {{node_uuid}} --instance-info image_os_hash_value="{{ node_image_os_hash_value }}"
             baremetal node set {{node_uuid}} --instance-info image_os_hash_algo="{{ node_image_os_hash_algo }}"
          fi
       fi                     
     command_kernel: |    
       . /opt/stack/bifrost/bin/activate
       export OS_CLOUD=bifrost           
       if [ -n '{{node_ks_template}}' ] ; then
          baremetal node set {{node_uuid}} --instance-info ks_template="{{node_ks_template}}"
       fi
       if [ -n '{{node_boot_iso}}' ] ; then
          baremetal node set {{node_name}} --instance-info boot_iso="{{node_boot_iso}}"
       fi
       if [ -n '{{node_kernel}}' ] ; then
          baremetal node set {{node_name}} --instance-info kernel="{{node_kernel}}"
       fi
       if [ -n '{{node_ramdisk}}' ] ; then
          baremetal node set {{node_name}} --instance-info ramdisk="{{node_ramdisk}}"
       fi          
     commands: 
      - "{{ command_create | default('ls')     }}"
      - "{{ command_image  | default('whoami') }}"
      - "{{ command_hash   | default('date') }}"          
      - "{{ command_kernel | default('df -h') }}"          
  loop: "{{ commands | default('') }}"
  loop_control:
    loop_var: command