---
# lifecycle.ymnl
#
#   - Lifecycle Stages Definition
#     - Enroll
#     - Inspect
#     - Clean
#     - Deploy
#     - Mantainace
#     - Retire
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0
#

#-----------------
# 1.- Enroll Stage
#-----------------
enroll:

   # 1.1.- Chassis Information
   name: "serverb199"
   uuid: "fa1331e3-b94c-48b6-bff8-992ec9f9b067"
   properties:
     boot_mode: "uefi" 
     secure_boot: false
     cpu_arch: "x86_64"
     ram: "4096"
     disk_size: "32"
     cpus: "4"  

   # 1.2.- Network Devices Description    
   nics:
     - mac: "BC:24:11:70:D8:B0"
       ipv4: "192.168.1.151" 
       network_interface: "noop" # No-Operation = No network Setup
       pxe: yes
     - mac: "BC:24:11:E5:66:0C"
       ipv4: "10.10.10.151"
       network_interface: "noop" # No-Operation = No network Setup

   # 1.3.- Out-of-Band BMC Information       
   driver: "redfish"
   driver_info:
     redfish_node_id: "103"

#-----------------
# 2.- Deploy Stage
#-----------------
deploy:   
   boot_interface:   "ipxe"
   deploy_interface: "ramdisk"
   os:
     name: "CentOS"
     version: "9"