---
# genesis.deploy 1_deploy/2_instance.yml
#  - Unattended OS installation
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0

- ansible.builtin.include_role:
    name: "{{ b5_baremetal_deploy.name }}"
  when: 
    - b5_baremetal_deploy.name is defined
    - b5_baremetal_deploy.condition | default(true) | bool 
  loop: "{{ b5_baremetal_deploy_roles | default([]) }}"
  loop_control:
    loop_var: "b5_baremetal_deploy"  