---
#------------------------
# PATHS
#------------------------
genesis_workpath:  >-
  {{ lookup('env', 'GENESIS_WORKING_PATH')
     | default(inventory_path + '/../../', True) 
     | default(playbook_path + '/../', True) 
     | realpath }}
bifrost_airgap_path: "{{ (genesis_workpath + '/repo') | realpath }}"
bifrost_workpath:  >-
  {{ (genesis_working_path + '/roles/openstack.bifrost/openstack.bifrost/')
     | realpath }}
bifrost_playbooks_path: "{{bifrost_workpath}}/playbooks"
bifrost_roles_path: "{{bifrost_playbooks_path}}/roles"     
bifrost_dynamic_inventory:  "{{ bifrost_root_path }}/bifrost/inventory.py"
bifrost_inventory_source: >-
  {{ lookup('env', 'BIFROST_INVENTORY_SOURCE')
     | default(inventory_path + 'group_vars.yml', True) }}