---
# genesis.setup 2_manage/2_lifecycle.yml
#   - Configure Instance Properties
#      - Map lifecycle data model into Ironic API
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0
#

- name: "B4 SETUP - Manage: Instance Info"
  vars:
    b4_ironic_base_url: "http://{{ b4_url_genesis_ip | default('127.0.0.1') }}"
    b4_ironic_port: "{{ b4_url_ironic_port | default(':6385') }}" 
    b4_ironic_path: "/v1/nodes/{{ uuid | default(name) }}"
    b4_ironic_uri: "{{ b4_ironic_base_url }}{{ b4_ironic_port }}{{ b4_ironic_path }}"
    b4_ironic_api_version: "{{ genesis_ironic_api_version | default('1.31') }}"
    b4_ironic_api_default_status: [200, 202, 204]
  block:

    - name: "B4 SETUP - Manage: Instance Properties vía URI"
      ansible.builtin.uri:
        url:    "{{ b4_ironic_uri }}{{ lifecycle_stage.path | default('') }}"
        method: "{{ lifecycle_stage.method }}"
        body_format: json
        headers:
          X-OpenStack-Ironic-API-Version: "{{ b4_ironic_api_version }}"  
        body: "{{ lifecycle_stage.body  | default(omit) }}"
        status_code: "{{ lifecycle_stage.status_code | default(b4_ironic_api_default_status) }}"
      register: b4_pipeline_results
      loop:
        # Stage 1 - Enroll Properties 
        - method: "PATCH"
          body:
           - op: "add"
             path: "/properties"
             value: "{{ properties | default({}) }}"
        # Stage 5 - Deploy Properties 
        - method: "PATCH"
          body:
           - op: "replace"
             path: "/boot_interface"
             value: "{{ boot_interface | default('ipxe') }}"
        - method: "PATCH"
          body:
           - op: "replace"
             path: "/deploy_interface"
             value: "{{ deploy_interface | default('direct') }}"
        - method: "PATCH"
          body:
           - op: "add"
             path: "/instance_info"
             value: "{{ instance_info | default({}) }}"
        # Stage 2 - Manage Properties 
        - method: "PATCH"
          body:
           - op: "add"
             path: "/instance_info/bootif"
             value: "{{ b4_enroll_nic_provision_mac | default(omit) }}" 
        - method: "PUT"
          path: "/management/boot_device"
          body:
            boot_device: "pxe"
            persistent: true
        # Power Off			 
        - method: "PUT"
          path: "/states/power"
          body:
            target: "power off"
        # Verification: Gather Instance Information
        - method: "GET"

      loop_control:
         loop_var: "lifecycle_stage"