---
# genesis.setup 2_manage/5_available.yml
#   - Leave Node in available State (ready to Deploy)
#      - Force Ironic to Render PXE Files for check
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0
#

#---------------------------------------
# 1.- Force Ironic to Render PXE File
#---------------------------------------  

#---------------------------------------
# 2.- Audit & Diagnostic Results
#---------------------------------------  
- name: "B4 - SETUP -2- MANAGE: 5.1) Available: AUDIT Results"
  ignore_errors: yes
  vars:
    b4_status_cmd:
      - |
        . /opt/stack/bifrost/bin/activate
        export OS_CLOUD=bifrost
        baremetal node show '{{ uuid }}' -f json
      - |
        systemctl status dnsmasq
      - |
        ss -tuplen | grep -i 'dnsmasq'
      - |
        systemctl status nginx
      - |
        ss -tuplen | grep -i 'nginx'
 
  block:
    - name: "B4 - SETUP -2- MANAGE: 5.1) Available: AUDIT Status Capture"
      ansible.builtin.shell: "{{ b4_status }}"
      environment:
        OS_CLOUD: "bifrost"
        PATH: "/opt/stack/bifrost/bin:{{ ansible_env.PATH }}"  
      loop: "{{ b4_status_cmd | default([]) }}"
      loop_control: 
        loop_var: "b4_status"
      register: g1_audit_payload_raw
      changed_when: false

    #-----------------------------------------------------------------------
    # 5.2.- Available: DIAGNOSTICS, trace result
    #-----------------------------------------------------------------------
    - name: "B4 - SETUP -2- MANAGE: 5.2) Available: DIAGNOSTICS, trace result"
      delegate_to: localhost
      ignore_errors: true
      vars:
        # --- Unificación limpia de arrays a texto multilínea nativo ---
        ironic_nice:            "{{ g1_audit_payload_raw.results[0].stdout | default('{}') | from_json | to_nice_json(indent=2) }}"
        dnsmasq_status:         "{{ g1_audit_payload_raw.results[1].stdout_lines | default(['No dnsmasq status captured']) | join('\n   ') }}"
        dnsmasq_sockets:        "{{ g1_audit_payload_raw.results[2].stdout_lines | default(['No dnsmasq sockets detected']) | join('\n   ') }}"
        nginx_status:           "{{ g1_audit_payload_raw.results[3].stdout_lines | default(['No nginx status captured']) | join('\n   ') }}"
        nginx_sockets:          "{{ g1_audit_payload_raw.results[4].stdout_lines | default(['No nginx sockets detected']) | join('\n   ') }}"
        dnsmasq_conf_interface: "{{ g1_audit_payload_raw.results[5].stdout_lines | default(['No conf directives detected']) | join('\n   ') }}"
        
        # --- Construcción del bloque continuo de diagnóstico ---
        t4_diagnostics_block: |
          --- IRONIC BAREMETAL INSTANCE DATA ---
          {{ ironic_nice }}
          ----------- PXE SERVICES -------------
          
          => DNSMASQ CONFIGURATION DIRECTIVES:
          network_interface=[{{ network_interface }}]
             {{ dnsmasq_conf_interface }}
          
          => DNSMASQ SERVICE STATUS:
             {{ dnsmasq_status }}
         
          => ACTIVE DNSMASQ SOCKETS:
             {{ dnsmasq_sockets }}
           
          => NGINX SERVICE STATUS:
             {{ nginx_status }}
          
          => ACTIVE NGINX SOCKETS:
             {{ nginx_sockets }}
          --------------------------------------
      ansible.builtin.debug:
        msg: "{{ t4_diagnostics_block.splitlines() }}"