---
# genesis.init 1_copy.yml
#   - Load OS images
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0
#

#---------------------------------------
# 1. Destinatin Folders
#---------------------------------------  
- name: "STEP 1: Detect Ironic Destination Folder"
  file:
    path: "{{ genesis_dest_folder }}"
    state: "directory"
    recurse: yes
    owner: ironic
    group: ironic
  loop: "{{ genesis_bifrost_dest_folder | default([]) }}"
  loop_control:
    loop_var: "genesis_dest_folder"

#---------------------------------------
# 2. Copy Files
#---------------------------------------  
- name: "STEP 1: Copy Downloaded Files to Ironic Images Master Path"
  ansible.builtin.copy:
    src:  "{{ genesis_repo_path | realpath }}/{{ genesis_init_repos[2] | default('qcow') }}/"
    dest: "{{ ironic_tftp_master_path | default('/var/lib/ironic/master_images') }}/"
    owner: ironic
    group: ironic
  #when:
  #  - not genesis_skip_image_creation | bool | default(false) 