---
# genesis.init 1_tftp.yml
#   - Populate TFTP service for PXE boot interface
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0
#

- name: "G3 - INIT: 1.- Setup PXE-TFTP - Upload Bootloader & OS Installers"
  vars:  
    # 1.- OS Particulars
    g3_image_os_distro:                   "{{ g3_image.distribution         | default('RedHat') | lower }}"
    g3_image_os_distro_version:           "{{ g3_image.distribution_version | default('8') }}"
    g3_image_os_distro_version_minor:     "{{ g3_image.distribution_version_minor | default('0') }}"
    g3_image_os_distro_version_main:      "{{ g3_image_os_distro_version    | string | split('.') | first }}"
    g3_image_os_distro_arch:              "{{ g3_image.distribution_arch    | default('x86_64') | lower }}"

    # 2.- Destination Paths
    g3_deploy_os_path:     "{{ g3_repo_os_path | realpath }}/{{ g3_image_os_distro }}/{{ g3_image_os_distro_version }}"
    g3_deploy_tftp_path:   "{{ g3_tftp_path    | realpath }}/{{ g3_image_os_distro }}/{{ g3_image_os_distro_version }}"   

    # 3.- Source Filename
    g3_default_netinstall_ramdisk: "{{ g3_image.netinstall_ramdisk | default('') }}"
    g3_default_netinstall_url_image_name: "{{ g3_image.netinstall_url | default('') | basename }}" 
    g3_default_netinstall_fix_image_name: "{{ ('mini' in g3_default_netinstall_ramdisk) | ternary('mini.iso','') }}"
    g3_default_netinstall_image_name: "{{ g3_default_netinstall_url_image_name | default(g3_default_netinstall_fix_image_name, true) | default('', true) }}"   
    g3_default_os_fix_image_name: "{{ g3_image_os_distro_arch }}.iso"
    g3_default_os_image_name:     "{{ g3_image.os_image_name | default(g3_default_os_fix_image_name) | default('x86_64.iso') | lower }}"
    g3_deploy_image_name:  "{{ g3_default_netinstall_image_name | default(g3_default_os_image_name, true) | lower }}" 

    # 4.- Ramdisk Files to Extract
    g3_src_type:      "{{ g3_default_netinstall_ramdisk | default('iso',true) }}"
    g3_src_distro:    "{{ g3_extract_os_installer[g3_src_type] | default([]) }}"
    g3_iso_files:     "{{ g3_src_distro[g3_image_os_distro]    | default([]) }}"
    g3_ramdisk_src:   "{{ g3_iso_files | map(attribute='src')  | list | default([]) }}"
    g3_ramdisk_files: "{{ g3_ramdisk_src | map('replace', '[ARCH]', g3_image_os_distro_arch) | list | default([]) }}"

    # 5.- Firmware Drivers for Ramdisk concatenation

 
  block: 
    - ansible.builtin.include_tasks: "1_tftp/1_folder.yml"
    - ansible.builtin.include_tasks: "1_tftp/2_os_installer.yml"	  
    - ansible.builtin.include_tasks: "1_tftp/3_cp_installer.yml"      
      loop: 
        - "{{ g3_deploy_os_path | realpath | default('') }}"
        - "{{ g3_deploy_tftp_path | realpath | default('') }}"
      loop_control:
        loop_var: "g3_os_installer_path"