---
# genesis.init 2_http.yml
#   - Load OS images
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0
#
- name: "G3 - INIT: Setup PXE-HTTP: Populate OS Images"
  ansible.builtin.include_tasks: "{{ g3_http_setup | default ('2_http/1_mount.yml') }}"
  vars:
    # 1.- OS Particulars
    g3_image_os_distro:        "{{ g3_image.distribution | default(g3_node_default_os) | default('RedHat') }}"
    g3_image_os_distro_version: "{{ g3_image.distribution_version | default(g3_node_default_version) | default('8') }}"

    # 2.- Image Name Default Values
    g3_deploy_image_default_name: "{{ g3_image.image | default('') | basename }}"
    g3_deploy_image_default_ext:  "{{ g3_deploy_image_default_name | ansible.builtin.splitext | last }}"
    g3_default_os_image_name:     "{{ genesis_default_os_image_name[g3_deploy_image_default_ext] |  default(g3_deploy_image_default_name) }}" 
    g3_deploy_image_name: "{{ g3_image.os_image_name | default(g3_default_os_image_name) }}" 

    # 3.- Mount Points
    g3_mount_path: "{{ g3_image.mount_path | default(g3_mount_repo_path) | default('/mnt') | realpath }}"    
  loop:
     - "2_http/1_mount.yml"   
     #- "2_http/2_cloud_image.yml"   
     #- "2_http/3_ipa.yml"       
  loop_control:
    loop_var: "g3_http_setup"