---
# genesis.init 3_load_ironic.yml
#   - Load OS images to Ironic
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0
#

- name: "STEP 3: Copy Bootable OS Images to Ironic Destination Folder"
  ansible.builtin.copy:
    src: "{{ genesis_repo_dib_path }}/"
    dest: "{{ ironic_tftp_master_path | default('/var/lib/ironic/httpboot') }}/"
    owner: ironic
    group: ironic