---
# genesis.init 3_os_installer.yml
#   - Load OS images
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0
#

- name: "STEP 1: Extract OS Native Installer"
  become: yes
  community.general.iso_extract:
    image: "{{ repo_image }}"
    dest:  "{{ deploy_path }}"
    files: "{{ ramdisk_files }}"
  vars:
    repo_path: "{{ ironic_tftp_master_path | default('/tmp') | realpath }}"
    repo_os_distro:  "{{ img_src.distribution | default('distro') }}"
    repo_os_distro_version:  "{{ img_src.distribution_version | default('unknown') }}"
    deploy_path: "{{ repo_path }}/{{ repo_os_distro }}/{{ repo_os_distro_version }}" 
    deploy_image_default_name: "{{ img_src.image | default('') | basename }}"
    deploy_image_default_ext: "{{ deploy_image_default_name | ansible.builtin.splitext | last }}"
    default_os_image_name: "{{ genesis_default_os_image_name[deploy_image_default_ext] | default(deploy_image_default_name) }}" 
    deploy_image_name: "{{ img_src.os_image_name | default(default_os_image_name) }}"
    repo_image: "{{ deploy_path }}/{{ deploy_image_name }}"
    ramdisk_files: "{{ genesis_extract_os_installer[repo_os_distro] | default('RedHat') }}"
  when: 
    - img_src.extract_ramdisk is defined
    - img_src.extract_ramdisk
    
  loop: "{{ download_image_sources | default([]) }}"
  loop_control:
    loop_var: "img_src"

