---
# genesis.init main.yml
#  - Populate PXE services
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0
#

- name: "------------------> G3- INIT - Populate PXE Services <------------------" 
  block:

    #---------------------------------------
    # 1. PXE - TFTP: Upload Bootloader & OS Installers
    #---------------------------------------   
    - ansible.builtin.include_tasks: "1_tftp.yml"
      loop: "{{ download_image_sources | default([]) }}"
      loop_control:
         loop_var:  "g3_image"
         index_var: "g3_image_index"       

    #---------------------------------------
    # 2. PXE - HTTP: Full Access to Images Repositories
    #--------------------------------------- 
    - ansible.builtin.include_tasks: "2_http.yml"
      loop: "{{ download_image_sources | default([]) }}"      
      loop_control:
         loop_var: "g3_image"
         index_var: "g3_image_index"
         
    - name: "G3 - INIT: 2.- Setup PXE-HTTP - 4) Expose Images Repositories"
      ansible.builtin.include_tasks: "2_http/4_expose.yml"  

    #---------------------------------------
    # 3. PXE - ORAS: Full Access to Images Repositories
    #---------------------------------------     
    #- name: "G3 - INIT: Setup PXE-ORAS - Expose Images Repositories"
    #  ansible.builtin.include_tasks: "3_oras.yml"
    #  loop: "{{ download_image_sources | default([]) }}"
    #  loop_control:
    #     loop_var: "g3_image"
    #     index_var: "g3_image_index"                

    #---------------------------------------
    # 4. Ironic Full Access to Installation Resources
    #---------------------------------------
    - ansible.builtin.include_tasks: "4_ready/1_ironic.yml"
      ignore_errors: yes