---
# genesis.init main.yml
#  - Setup PXE services
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0
#
- name: "------------------> G3- INIT GENESIS NODE <------------------" 
  ignore_errors: yes
  block:

    #---------------------------------------
    # 1. PXE - TFTP: Upload Bootloader & OS Installers
    #---------------------------------------   
    - name: "G3 - INIT: Setup PXE-TFTP - Upload Bootloader & OS Installers"
      ansible.builtin.include_tasks: "1_tftp.yml"
      loop: "{{ download_image_sources | default([]) }}"
      loop_control:
         loop_var: "g3_image"
         index_var: "g3_image_index"       

    #---------------------------------------
    # 2. PXE - HTTP: Full Access to Images Repositories
    #--------------------------------------- 
    - name: "G3 - INIT: Setup PXE-HTTP - Expose Images Repositories"
      ansible.builtin.include_tasks: "2_http.yml"
      loop: "{{ download_image_sources | default([]) }}"
      loop_control:
         loop_var: "g3_image"
         index_var: "g3_image_index"      
  
    #---------------------------------------
    # 3. PXE - ORAS: Full Access to Images Repositories
    #---------------------------------------      
    #- name: "G3 - INIT: Setup PXE-ORAS - Expose Images Repositories"
    #  ansible.builtin.include_tasks: "3_oras.yml"
    #  loop: "{{ download_image_sources | default([]) }}"
    #  loop_control:
    #     loop_var: "g3_image"
    #     index_var: "g3_image_index"                
    
    #---------------------------------------
    # 4. Users
    #---------------------------------------      
    - name: "G3 - INIT: Ready PXE: Users Permissions to Allow Ironic SetUp"
      ansible.builtin.user:
        name: "{{ g3_user.name }}"
        groups:  "{{ g3_user.groups }}" 
        append: true
        state: present  
      vars:
        # Eventually choose according to genesis distro
        g3_groups: "cesar,adm,cdrom,sudo,dip,plugdev,lxd,ironic"      
      loop:
        - name: "cesar"
          groups: "{{ g3_groups }}"
        - name: "ironic"
          groups: "{{ g3_groups }}"
      loop_control:
         loop_var: "g3_user"
         index_var: "g3_user_index"                    