---
# genesis.setup defaults
#   - Generate Install Manifesto for each Node
#   - Enroll Nodes
#   - Set Boot Interface
#   - Set deploy Interface
#   - Move across node life cycle transitions until Available State
#  
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0
#

######################################################
#  GENESIS PATHS (global for update all genesis roles at once)
######################################################
# 1.- Repos Paths
genesis_repo_path:     "{{ role_path }}/../../repo"
genesis_local_repo_url: "file://{{ genesis_repo_path | realpath }}"
genesis_rsyslog_port: "5456"
file_url_port_tls: "8083"


# 2.- Bifrost Role Paths
genesis_bifrost_role_name: "genesis.bifrost"
genesis_bifrost_path:  "{{ role_path }}/../{{ genesis_bifrost_role_name }}"
genesis_bifrost_roles: "{{ genesis_bifrost_path | realpath }}/{{ genesis_bifrost_role_name }}/playbooks/roles"
genesis_bifrost_files_path: "{{ genesis_bifrost_path | realpath }}/files"
genesis_bifrost_venv_dir: "{{ lookup('env', 'VENV') or '/opt/stack/bifrost' }}"

# 3.- Repositories
genesis_default_repos:
  os: "os"
  manifesto: "manifesto" 
  components: "openstack"
  cloud: "dib"
  ipa: "dib/files" 
  repo: "mnt"

genesis_os_definitions:
  centos:
    ansible_distribution: "CentOS"
    installer: "anaconda"
    prefix: "ks_"
    ext: ".ks" 
  redhat:
    ansible_distribution: "RedHat"
    installer: "anaconda"
    prefix: "ks_"
    ext: ".ks"  
  esxi:
    ansible_distribution: "unknown"
    installer: "anaconda"
    ext: ".ks"     
  ubuntu:
    ansible_distribution: "Ubuntu"
    installer: "subsiquity"
  coreos:
    ansible_distribution: "CoreOS"
    installer: "ignition"
    ext: ".ign"     
  debian:
    ansible_distribution: "Debian"
    installer: "preseed" 
    ext: ".cfg"     
 
######################################################
# B4 - PATHS
######################################################
# 1.- Paths
b4_repos: "{{ genesis_airgap_repos | default(genesis_default_repos) }}" 
b4_repo_os_path: "{{ genesis_repo_path | realpath }}/{{ b4_repos['os'] | default('os') }}"
b4_manifesto_subpath: "{{ b4_repos['manifesto'] | default('manifesto') }}"
b4_repo_manifesto_path: "{{ genesis_repo_path | realpath }}/{{ b4_manifesto_subpath }}"
b4_http_manifesto_path: "{{ ironic_http_path | realpath }}/{{ b4_manifesto_subpath }}"

# 2.- URLs
b4_url_protocol: "http"
b4_url_short_subpath:  "{{ b4_node_os | lower }}{{ b4_node_os_version | lower}}"
b4_url_full_subpath:   "{{ b4_node_os }}/{{ b4_node_os_version }}"
b4_url_genesis_ip: "{{ dhcp_address | ansible.utils.ipaddr('address') | default('') }}"
b4_url_genesis_gateway: "{{ dhcp_address | ansible.utils.ipaddr('last_usable') | default('') }}" 
b4_url_genesis_netmask: "{{ dhcp_address | ansible.utils.ipaddr('netmask') | default('255.255.255.0') }}"
b4_genesis_port:
  http:  "{{ genesis_http_port  | default(file_url_port)     | default('8080') }}"
  https: "{{ genesis_https_port | default(file_url_port_tls) | default('8083') }}" 
b4_url_genesis_port: "{{ b4_genesis_port[b4_url_protocol] is defined | ternary (':','','') }}{{ b4_genesis_port[b4_url_protocol] | default('') }}"
b4_url_genesis_url: "{{ genesis_address | default(b4_url_genesis_ip) }}{{ b4_url_genesis_port }}"


######################################################
#  BIFROST ROLES DEFINITION 
######################################################
b4_configdrive_roles:
   - name: "bifrost-configdrives-dynamic"

b4_enroll_roles:
   - name: "ironic-enroll-dynamic"
   - name: "ironic-inspect-node"
     condition: "{{ inspect_nodes | default('false') | bool }}" 

######################################################
# NODE PARTICULARS
######################################################

# 1.- Node Details
#------------------
# 1.1.- Properties
b4_node_name: "{{ name | default(hostname) | default(inventory_hostname_short) | default(inventory_hostname) | default(ansible_hostname) | default('nohost') }}" 

# 1.2.- BMC
b4_node_bmc_driver: "{{ driver | default('redfish') }}"
b4_node_bmc_info:   "{{ driver_info | default('') }}"
b4_node_bmc_mac:    ""
b4_node_bmc_ip: ""
b4_node_bmc_gateway: "" 
b4_node_bmc_netmask: ""

# 1.2.- OS
b4_node_default_os: "CentOS"
b4_node_default_os_version: "9"
b4_node_default_os_arch: "x86_64"
b4_node_default_os_profile: "none"
b4_capture_node_os:   "{{ os.name | default(b4_node_default_os) | lower }}"
b4_node_os_definitions: "{{ genesis_os_definitions[b4_capture_node_os] }}"
b4_node_os:           "{{ b4_node_os_definitions['ansible_distribution'] | default('unknown') }}"
b4_node_os_version:   "{{ os.version | default(b4_node_default_os_version) }}"
b4_node_os_arch:      "{{ os.arch    | default(b4_node_default_os_arch) }}"
b4_node_os_profile:   "{{ os.profile | default(b4_node_default_os_profile) }}"
b4_node_os_installer: "{{ b4_node_os_definitions['installer'] | default('anaconda') | lower}}"
b4_node_os_manifesto_file: "{{ b4_node_os_definitions['prefix'] }}{{ b4_node_name }}{{ b4_node_os_definitions['ext'] }}"

# 2.- Users 
#------------------
b4_default_user_name: 'genesis'
b4_default_user_password: ''
b4_root_user_password: ''

# 3.- OS Installers URLs
#------------------
b4_netinstall_base_url: "{{ b4_url_protocol }}://{{ b4_url_genesis_url }}"
b4_netinstall_os_manifesto_url:    "{{ b4_netinstall_base_url }}/{{ b4_manifesto_subpath }}"
b4_netinstall_os_images_url:       "{{ b4_netinstall_base_url }}/{{ b4_url_full_subpath }}"
b4_netinstall_os_mounted_repo_url: "{{ b4_netinstall_base_url }}/{{ b4_url_short_subpath }}"
b4_netinstall_os_iso_url:          "{{ b4_netinstall_os_images_url }}/{{ b4_node_os_iso | default(b4_node_os_arch + '.iso') }}"

#####################################################
# OS_NATIVE: INSTALLERS TEMPLATES RENDERING
#   TODO: Install definition API that abstracts installer particulars
##################################################### 

#------------------------------------
# 1.- Kickstart
#------------------------------------
b4_kickstart_template_defaults:
  system: |
    # Use NFS installation media
    url --url {{ b4_netinstall_os_mounted_repo_url }}    
    
    #system Language
    lang en_GB
           
    #system keyboard
    keyboard uk
           
    # Firewall configuration
    firewall --disabled
    
    # SELinux configuration
    selinux --disabled
           
    # System authorization information
    auth  --useshadow --passalgo=sha512   
    
    #Sytem timezone
    timezone --utc Europe/London
    
    #Use text mode install
    text
    
    # Install OS instead of upgrade
    install
  logging: |
    # Reboot after installation
    reboot
    
    # Installation logging level
    logging --level=info     
  network: |
    network  --bootproto=static --ip={{ b4_node_bmc_ip }} --netmask={{ b4_node_bmc_netmask }} --gateway={{ b4_node_bmc_gateway }} --onboot=on --hostname={{ b4_node_name }} --device={{ b4_node_bmc_mac }}
  packages: |
    @ base
    @ core
  storage: |
    # Clear the Master Boot Record
    zerombr
    
    # System bootloader configuration
    bootloader --location=mbr
    
    # Partition clearing information
    clearpart --all --initlabel
    
    #Partitions
    part / --fstype=ext4 --size=17408
    part pv.lab-okd-worker3-0001 --grow --size=1
    volgroup VolGroup00 --pesize=4096 pv.{{ b4_node_name }}
    logvol /nats --fstype=ext4 --name=LogVol03 --vgname=VolGroup00 --grow --size=1024
    logvol swap --name=lv_LogVol00 --vgname=VolGroup00 --grow --size=1008 --maxsize=16288

b4_kickstart_template_profiles:
  vmware_esxi: 
    storage: |
      # Clear the Master Boot Record
      zerombr
      
      # System bootloader configuration
      bootloader --location=mbr
      
      # Partition clearing information
      clearpart --all --initlabel
      
      #Partitions
      part / --fstype=ext4 --size=17408
      part pv.lab-okd-worker3-0001 --grow --size=1
      volgroup VolGroup00 --pesize=4096 pv.{{ b4_node_name }}
      logvol /nats --fstype=ext4 --name=LogVol03 --vgname=VolGroup00 --grow --size=1024
      logvol swap --name=lv_LogVol00 --vgname=VolGroup00 --grow --size=1008 --maxsize=16288     

#------------------------------------
# 2.- Cloud Init
#------------------------------------
b4_subsiquity_template_defaults:
  system: |
    user-data:
      disable_root: false
    identity:
      hostname: {{ b4_node_name }}
      username: {{ b4_default_user_name }}
      password: '{{ b4_default_user_password }}'
    keyboard:
      layout: us
    locale: en_US.UTF-8   
  ssh: |
    allow-pw: true
    authorized-keys: []
    install-server: true
  logging: |
    remotes:
      log_serv: "*.* @@{{ b4_http_genesis_address }}:{{ genesis_rsyslog_port }}"     
  network: |
    network:
      version: 2
      ethernets:
        eno1:
          critical: true
          addresses:
            - {{ b4_node_bmc_ip }}
          gateway4: {{ b4_node_bmc_gateway }}
          match:
            macaddress: {{ b4_node_bmc_mac }}
          set-name: eno1         
  storage: |
    layout:
      name: lvm
      match: {} 
  packages: |
    # even set to no/false, geoip lookup still happens
    geoip: no
    preserve_sources_list: false
    sources_list: |
      deb [trusted=yes] http://{{ b4_netinstall_os_mounted_repo_url }} ./
    packages:
     - ubuntu-desktop-minimal          
  preinstall: |
    - path: /run/tmpfiles.d/bootorder.sh
      content: |
        #!/bin/bash
        BOOT_OS=$(/target/usr/bin/efibootmgr |egrep ubuntu|cut -b5-8|tr -s '\n' ',')
        BOOT_DEVICE=$(/target/usr/bin/efibootmgr |egrep -v "ubuntu|^Time|^BootC|^BootO|^Desired|^Mirror"|cut -b5-8|tr -s '\n' ','|sed 's/.$//')
        /target/usr/bin/efibootmgr -o ${BOOT_OS}${BOOT_DEVICE}     
  postinstall: |
    - echo '{{ b4_default_user_name }} ALL=(ALL) NOPASSWD:ALL' > /target/etc/sudoers.d/{{ b4_default_user_name }}
    - sed -i 's|^root:.:|root:{{ b4_root_user_password }}|' /target/etc/shadow
    - sed -i 's|#PermitRootLogin prohibit-password|PermitRootLogin yes|' /target/etc/ssh/sshd_config
    - /bin/bash /run/tmpfiles.d/bootorder.sh
      
#------------------------------------
# 3.- Preseeds
#------------------------------------


#------------------------------------
# 4.- Ignition
#------------------------------------


######################################################
#  LIFECYCLE DEFINITION: DEPLOY STAGE 
###################################################### 

#------------------------------------
# 1.- OS Installer Manifesto
#------------------------------------
b4_os_installer_manifesto:
  anaconda:
    template:  
      - "kickstart.j2"
    file:      
      - "{{ b4_repo_manifesto_path }}/{{ b4_node_os_manifesto_file }}"
    url:       "{{ b4_netinstall_os_manifesto_url }}/{{ b4_node_os_manifesto_file }}" 
    defaults:  "{{ b4_kickstart_template_defaults | default({}) }}"
    profiles:  "{{ b4_kickstart_template_profiles | default({}) }}"
    
  esxi:
    template:  
      - "kickstart.j2"
    file:      
      - "{{ b4_repo_manifesto_path }}/{{ b4_node_os_manifesto_file }}"
    url:       "{{ b4_netinstall_os_manifesto_url }}/{{ b4_node_os_manifesto_file }}" 
    defaults:  "{{ b4_kickstart_template_defaults | default({}) }}"
    profiles:  "{{ b4_kickstart_template_profiles | default({}) }}"    
    
  preseed:
    template:  
      - "preseed.j2"
    file:      
      - "{{ b4_repo_manifesto_path }}/{{ b4_node_os_manifesto_file }}"
    url:       "{{ b4_netinstall_os_manifesto_url }}/{{ b4_node_os_manifesto_file }}" 
    defaults:  "{{ b4_preseed_template_defaults | default({}) }}"
    profiles:  "{{ b4_preseed_template_profiles | default({}) }}"   
    
  subsiquity:
    template:  
      - "cloud-init/meta-data.j2"
      - "cloud-init/user-data.j2"     
    file:      
      - "{{ b4_repo_manifesto_path }}/{{ b4_node_name }}/meta-data"
      - "{{ b4_repo_manifesto_path }}/{{ b4_node_name }}/user-data"
    url:       "{{ b4_netinstall_os_manifesto_url }}/{{ b4_node_name }}/meta-data"  
    defaults:  "{{ b4_subsiquity_template_defaults | default({}) }}"
    profiles:  "{{ b4_subsiquity_template_profiles | default({}) }}"
    
  ignition:
    template:  
      - "ignition.j2"    
    file:      
      - "{{ b4_repo_manifesto_path }}/{{ b4_node_os_manifesto_file }}"
    url:       "{{ b4_netinstall_os_manifesto_url }}/{{ b4_node_os_manifesto_file }}" 
    defaults:  "{{ b4_ignition_template_defaults | default({}) }}"
    profiles:  "{{ b4_ignition_template_profiles | default({}) }}"
  
#------------------------------------
# 2.- OS Installer Call from Bootloader
#------------------------------------
b4_node_default_os_manifesto: "{{ b4_os_installer_manifesto['anaconda'] }}"
b4_node_os_manifesto: "{{ b4_os_installer_manifesto[b4_node_os_installer] | default(b4_node_default_os_manifesto) }}"
b4_os_installer_bootloader_call:
  anaconda:
    kernel:  "{{ b4_netinstall_os_images_url }}/{{ b4_node_os_definions.kernel  | default('vmlinuz') }}"
    initram: "{{ b4_netinstall_os_images_url }}/{{ b4_node_os_definions.initram | default('initrd.img') }}"
    menu:    "inst.ks={{ b4_node_os_manifesto.url }} inst.repo={{ b4_netinstall_os_mounted_repo_url }}"
  esxi:     
    kernel:  "{{ b4_netinstall_os_images_url }}/{{ b4_node_os_definions.kernel  | default('vmlinuz') }}"
    initram: "{{ b4_netinstall_os_images_url }}/{{ b4_node_os_definions.initram | default('initrd.img') }}"
    menu:    "ks={{ b4_node_os_manifesto.url }}"
  subsiquity:
    kernel:  "{{ b4_netinstall_os_images_url }}/{{ b4_node_os_definions.kernel  | default('vmlinuz') }}"
    initram: "{{ b4_netinstall_os_images_url }}/{{ b4_node_os_definions.initram | default('initrd') }}"  
    menu:    "url={{ b4_netinstall_os_iso_url }} autoinstall ds=nocloud-net;s={{ b4_node_os_manifesto.url }}"
  ignition:
    kernel:  "{{ b4_netinstall_os_images_url }}/{{ b4_node_os_definions.kernel | default('vmlinuz') }}"
    initram: "{{ b4_netinstall_os_images_url }}/{{ b4_node_os_definions.initram | default('initramfs') }}"      
    menu:    "ignition.config.url={{ b4_node_os_manifesto.url }} ip=dhcp" 
  preseed:  
    kernel:  "{{ b4_netinstall_os_images_url }}/{{ b4_node_os_definions.kernel  | default('vmlinuz') }}"
    initram: "{{ b4_netinstall_os_images_url }}/{{ b4_node_os_definions.initram | default('initrd') }}"  
    menu:    "auto=true priority=critical url={{ b4_node_os_manifesto.url }}" 