---
# sources.ymnl
#
#  G1- REFRESH Setup
#    - Local Repo Creation from Listed Sources
#  
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0
#

#-------------------------
# 1.- Checksums 
#-------------------------
genesis_sources_enabled: yes
genesis_local_checksum_file:
  path: "{{ genesis_repo_path | realpath }}/checksum"
  content: |
   8ffd0d0fc218eae95c578ec12839fe598d60f96de85fab63d424ad021ed1a62f *fedora-coreos-44.20260707.3.1-live-iso.x86_64.iso
   360c3b6b4cc8a58807fca8ac6947c8ec578e482af52d2311ae99ef02fe9d8dc5 *fedora-coreos-44.20260707.3.1-live-initramfs.x86_64.img 
   b0389e187ed951727560f517d589f3daa2736dc34dc9aa245b986d72b6f6c3ee *fedora-coreos-44.20260707.3.1-live-kernel.x86_64
   3c0ace903c0a78b13a09d5649ffc4409370f6d8dab2a79fea310b20ac20a2ac2 *Leap-16.0-offline-installer-x86_64-Build178.27.install.iso
genesis_local_checksum_url: "file://{{ genesis_repo_path | realpath }}/checksum"

#-------------------------
# 2.- Local Repo Sources
#-------------------------
genesis_download_images:

   #-----------------------------------
   # ISOs for OS Native Network Installers
   #-----------------------------------
  - distribution: "CentOS"
    distribution_version: "9"
    os_image_name: "x86_64.iso"
    image: "https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/iso/CentOS-Stream-9-latest-x86_64-dvd1.iso"
    checksum: "https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/iso/CentOS-Stream-9-latest-x86_64-dvd1.iso.SHA256SUM"
    checksum_algorithm: "sha256"
    extract_ramdisk: yes
    mount: yes

  - distribution: "Ubuntu"
    distribution_version: "24.04"
    os_image_name: "x86_64.iso"
    image: "https://releases.ubuntu.com/noble/ubuntu-24.04.4-live-server-amd64.iso"
    checksum: "https://releases.ubuntu.com/noble/SHA256SUMS"
    checksum_algorithm: "sha256"
    extract_ramdisk: yes

  - distribution: "CoreOS"
    distribution_version: "44"
    os_image_name: "x86_64.iso"  
    image: "https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/44.20260707.3.1/x86_64/fedora-coreos-44.20260707.3.1-live-iso.x86_64.iso"
    checksum: "{{ genesis_local_checksum_url }}"
    checksum_algorithm: "sha256"      
  - distribution: "CoreOS"
    distribution_version: "44"
    os_image_name: "vmlinuz"
    image: "https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/44.20260707.3.1/x86_64/fedora-coreos-44.20260707.3.1-live-kernel.x86_64"
    checksum: "{{ genesis_local_checksum_url }}"
    checksum_algorithm: "sha256"
  - distribution: "CoreOS"
    distribution_version: "44"
    os_image_name: "initramfs" 
    image: "https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/44.20260707.3.1/x86_64/fedora-coreos-44.20260707.3.1-live-initramfs.x86_64.img"
    checksum: "{{ genesis_local_checksum_url }}"
    checksum_algorithm: "sha256"

  - distribution: "Debian"
    distribution_version: "13.0"
    os_image_name: "x86_64.iso"
    image: "https://debian-cd.repulsive.eu/current/amd64/iso-cd/debian-13.6.0-amd64-netinst.iso"
    checksum: "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/SHA512SUMS"
    checksum_algorithm: "sha256"
    extract_ramdisk: yes

  - distribution: "SuSE"
    distribution_version: "16.0"
    os_image_name: "x86_64.iso"
    image: "https://download.opensuse.org/distribution/leap/16.0/offline/Leap-16.0-offline-installer-x86_64-Build178.27.install.iso"
    checksum: "{{ genesis_local_checksum_url }}"
    checksum_algorithm: "sha256"
    extract_ramdisk: yes

   #-----------------------------------
   # QCOWs for Cloud OS Installers
   #-----------------------------------
  - distribution: "CentOS"
    distribution_version: "9"
    os_image_name: "partition.qcow2"
    image: "https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2"
    checksum: "https://cloud.centos.org/centos/9-stream/x86_64/images/CHECKSUM"
    checksum_algorithm: "sha256"