---
# lifecycle.ymnl
#
#   - Lifecycle Stages Definition - Overwrite default values
#     - 1) Enroll  - Out-Band BMC Connectivity Assurance
#     - 2) Manage  - In-Band Connectivity Assurance
#     - 3) Inspect - BMC/IPA Steps for Gathering Hardware Details
#     - 4) Clean   - BMC/IPA Steps to wipe and setup physical disks (RAIDs, etc.)
#     - 5) Deploy  - Install Operating System
#     - 6) Active  - Hearbeat + Tenant networks
#     - 7) Repair  - BMC/IPA Steps to Flash Hardware Firmwares
#     - 8) Delete  - Un-enroll, remove the node
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0
#

#-----------------
# 1.- Enroll - Ensure Out-Band Access to the Node
#-----------------
enroll:

   # 1.1.- Out-of-Band BMC Information  
   uuid: "c6c53f30-bc69-4bbb-b7df-05f1900e2fe6"
   driver_info:
      node_id: "102"

   # 1.2.- Chassis Information
   capabilities: 
     boot_mode: "uefi" 
     secure_boot: false
   properties:
     cpu_arch: "x86_64"
     ram: "4096"
     disk_size: "32"
     cpus: "4"  

   # 1.3.- Network Devices Description    
   nics:
     outband:
       - mac: "BC:24:11:28:C3:E2"
         ipv4: "10.10.41.150/24" 
         network_interface: "noop" # No-Operation = No network Setup	 
     inband:  
       - provision: yes
         mac: "BC:24:11:7A:BD:68"
         ipv4: "10.10.51.150/24"
         network_interface: "noop" # No-Operation = No network Setup	 

#-----------------
# 5.- Deploy - Install Operating System
#-----------------
deploy:   
   boot_interface:   "ipxe"
   deploy_interface: "ramdisk"
   os:
     name: "CentOS"
     version: "9"