---
# lifecycle.ymnl
#
#   - Lifecycle Stages Definition - Overwrite default values
#      B4) Genesis SETUP
#         - B4.1) Enroll  - Out-Band BMC Connectivity Assurance
#         - B4.2) Manage  - In-Band Connectivity Assurance
#         - B4.3) Inspect - BMC/IPA Steps for Gathering Hardware Details
#      B5) Genesis DEPLOY
#         - B5.4) Clean   - BMC/IPA Steps to wipe and setup physical disks (RAIDs, etc.)
#         - B5.5) Deploy  - Install Operating System
#         - B5.6) Active  - Hearbeat + Tenant networks
#      B6) Genesis PROVISION
#         - B6.7) Strategy- Apply Integrated Bundles of Software Profiles
#         - B6.8) Repair  - BMC/IPA Steps to Flash Hardware Firmwares
#         - B6.9) Delete  - Un-enroll, remove the node
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0
#

#-----------------
# 1.- Enroll - Ensure Out-Band Access to the Node
#-----------------
enroll:

   # 1.1.- Out-of-Band BMC Information  
   uuid: "c6c53f30-bc69-4bbb-b7df-05f1900e2fe6" # BIOS ID
   node_id: "201"                               # BMC ID

   # 1.2.- Chassis Information
   capabilities: 
     boot_mode: "uefi" 
     secure_boot: false
     boot_device: "disk" # fix boot device... erase disk partitions an reboot to shoot pxe
   properties:
     cpu_arch: "x86_64"
     ram: "8192"
     disk_size: "32"
     cpus: "4"  

   # 1.3.- Network Devices Description    
   nics:
     outband:
       - mac: "BC:24:11:28:C3:E2"
         ipv4: "10.10.41.150/24" 
     inband:  
       - provision: yes
         mac: "BC:24:11:7A:BD:68"
         ipv4: "10.10.51.150/24"

#-----------------
# 5.- Deploy - Install Operating System
#-----------------
deploy:   
   boot_interface:   "ipxe"
   deploy_interface: "ramdisk"
   os:
     name: "Ubuntu"
     version: "24.04"