---
# genesis.init handlers
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0

- name: "Restart Web Server"
  ansible.builtin.service:
    name: nginx
    state: reloaded