---
# genesis.setup 1_manifesto/1_os_native.yml
#   - Generate Install Manifesto:
#      - cloud-init
#      - kickstart
#      - ignition
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0
#

#---------------------------------------
# 1. Manifest Folder
#---------------------------------------   
- name: "STEP 1 - Create Manifesto Folders"
  file:
     path: "{{ b4_folder | realpath }}"
     state: "directory"  
     recurse: true
  loop: 
    - "{{ b4_repo_manifesto_path }}"
  loop_control:
    loop_var: "b4_folder" 
    
- name: "STEP 1 - Expose Manifesto Folder"
  file:
    src:  "{{ b4_repo_manifesto_path }}"
    dest: "{{ b4_http_manifesto_path }}"   
    state: link
    
#---------------------------------------
# 2. Manifest Rendering (KickStart, Cloud-Init, Ignition)
#---------------------------------------
- name: "STEP 1 - Rendering OS Installation Manifest"
  ansible.builtin.template:
    src:   "{{ b4_node_manifesto_src  | default(omit) }}"
    dest:  "{{ b4_node_manifesto_dest | default(omit)  }}"
  vars:
    b4_node_manifesto_default_dest: "{{ b4_node_manifesto_files[0] | default(b4_node_name) }}"
    b4_node_manifesto_dest: "{{ b4_node_manifesto_files[b4_node_manifesto_dest_index] | default(b4_node_manifesto_default_dest) }}"
  loop: "{{ b4_os_manifesto_templates | default([]) }}"
  loop_control:
    loop_var: "b4_node_manifesto_src"
    index_var: "b4_node_manifesto_dest_index"