---
# genesis.test 1_hypervisor/proxmox_facts.yml
#  - Working Conditions on Hypervisor
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0

- name: "T1 - TESTING ENVIRONMENT: Proxmox Testing User Provisioning"
  block:

    - name: "T2 - TESTING ENVIRONMENT 3.- Nodes: 2.1) Query Proxmox API node name dynamically"
      become: true
      ansible.builtin.shell: |
        pvesh get /nodes --output-format json | awk -F'\"node\":\"' '{print $2}' | awk -F'\"' '{print $1}'
      register: t1_pve_detected_node
      changed_when: false
      delegate_to: "{{ t1_hypervisor_node | default('localhost') }}"

    - name: "T2 - TESTING ENVIRONMENT 3.- Nodes: 2.2) Register node name as a runtime fact"
      ansible.builtin.set_fact:
        t1_hypervisor_api_hostname: "{{ t1_hypervisor_api_hostname | default(t1_captured_hostname) }}"
      vars:
        t1_captured_hostname: "{{ t1_pve_detected_node.stdout | trim | default(omit) }}"