---
# genesis.create 1_install_ironic
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0
#

#---------------------------------------
# 1. Install Ironic
#---------------------------------------  
- ansible.builtin.debug:
    msg: "{{ dump_text | split('\n') }}"
  vars:
    dump_text: |   
      => NETWORK INTERFACE RESOLUTION:
      genesis_target_mac:            {{ genesis_target_mac | default('Not defined') }}
      genesis_interface_found:       {{ genesis_interface_found | default('Not found') }}
      genesis_interfaces_fallback:   {{ genesis_interfaces_fallback | default('Not available') }}
      genesis_default_nic:           {{ genesis_default_nic | default('Not available') }}
      SELECTED NETWORK_INTERFACE:    {{ network_interface | default('network_interface not found') }}
      
      => GENERAL DHCP CONFIGURATION:
      enable_dhcp:   {{ enable_dhcp }}
      dhcp_provider: {{ dhcp_provider }}
      
      => IP ADDRESSING PROPERTIES:
      dhcp_ipv4:        {{ dhcp_ipv4 }}
      dhcp_address:     {{ dhcp_address | default('Error/Not calculated') }}
      dhcp_static_mask: {{ dhcp_static_mask | default('Error/Not calculated') }}
      dhcp_prefix:      {{ dhcp_prefix | default('Error/Not calculated') }}
      dhcp_subnet:      {{ dhcp_subnet | default('Error/Not calculated') }}
      dhcp_subnet_cidr: {{ dhcp_subnet_cidr | default('Error/Not calculated') }}
      
      => DYNAMIC POOL CALCULATIONS:
      dhcp_raw_node_count: {{ dhcp_raw_node_count }}
      dhcp_range_size:     {{ dhcp_range_size }}
      dhcp_last_usable:    {{ dhcp_last_usable | default('Error/Not calculated') }}
      DHCP_POOL_START:     {{ dhcp_pool_start | default('Error/Not calculated') }}
      DHCP_POOL_END:       {{ dhcp_pool_end | default('Error/Not calculated') }}
      -------------------------------------

- name: "G2 - CREATE - Install Ironic"
  ansible.builtin.include_role: 
    name: "{{ genesis_install_ironic_role.name }}"
  when: 
    - genesis_install_ironic_role.name is defined
    - genesis_install_ironic_role.condition | default(true) | bool
  loop: "{{ genesis_ironic_install_roles | default([]) }}"
  loop_control:
    loop_var: "genesis_install_ironic_role"  