---
# genesis.create main
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0
#
- name: "------------------> G2- CREATE GENESIS NODE <------------------" 
  ignore_errors: yes 
  block:
    - ansible.builtin.include_tasks: "1_install_ironic.yml"
    - ansible.builtin.include_tasks: "2_setup_ironic.yml"