---
# genesis.init 2_http/3_expone.yml
#   - Expones Image Repositories
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0
#

#---------------------------------------
# 1. Ownership of Folders to Expose (Web Server Owner = Ironic)
#---------------------------------------  
- name: "STEP 2.3 - HTTP: Folders to Expose"
  vars:
    g3_ruta_base: "{{ genesis_repo_path | default('../../../../repo') | realpath }}"
    g3_components: "{{ g3_repos['components'] | default('openstack') }}" 
    g3_mnt: "{{ g3_repos['repo'] | default('mnt') }}" 
  ansible.builtin.shell: |
    find {{ g3_ruta_base }} \( -name {{ g3_components }} -o -name {{ g3_mnt }} \) -prune -o -print
  register: "g3_exposure"
  changed_when: false

- name: "STEP 2.3 - HTTP: Ownership Before exposure"
  ansible.builtin.file:
    path: "{{ g3_exposure_file }}"
    owner: ironic
    group: ironic
  loop: "{{ g3_exposure.stdout_lines | default([]) }}"
  loop_control:
    loop_var: "g3_exposure_file"
  
#---------------------------------------
# 2. Create Symbolik Links to HTTP folder
#---------------------------------------  
- name: "STEP 2.3 - HTTP: Expose Image Repositories"
  file:
    src:  "{{ http_exposure.src }}"
    dest: "{{ http_exposure.dest }}"
    owner: ironic
    group: ironic
    state: link
  loop:
    - src:  "{{ g3_distro_repo_path }}"
      dest: "{{ g3_distro_http_path }}"
    - src:  "{{ g3_manifesto_repo_path }}"
      dest: "{{ g3_manifesto_http_path }}" 
  loop_control:
    loop_var: "http_exposure"  

#---------------------------------------
# 3. Create Symbolik Links to Mounted Folders
#---------------------------------------  
- name: "STEP 2.3 - HTTP: Expose Mounted ISOs"
  file:
    src:  "{{ g3_mount_src_path }}"
    dest: "{{ g3_mount_http_path }}"
    owner: ironic
    group: ironic    
    state: link
  vars:
    g3_mount_default_src_path:   "{{ g3_mount_path }}/{{ g3_image_os_distro }}/{{ g3_image_os_distro_version }}" 
    g3_mount_src_path: "{{ g3_image.mount_path | default(g3_mount_default_src_path) | realpath }}"
    g3_mount_dest_file: "{{ g3_image_os_distro | lower }}{{ g3_image_os_distro_version | lower }}"
    g3_mount_http_path: "{{ g3_http_path | realpath }}/{{ g3_mount_dest_file }}"
  when: 
    - g3_image.mount is defined
    - g3_image.mount       
     
#---------------------------------------
# 4. SELinux / AppArmor Permissions
#---------------------------------------  