---
#--------------------------
# OCI: QCOW Images with baked-in Cloud-Init Install Manifesto
#--------------------------
servera199.maas.lab:
   uuid: "c6c53f30-bc69-4bbb-b7df-05f1900e2fe6"
   driver_info:
     redfish_verify_ca: false
     redfish_username: "root@pam"
     redfish_address: "https://10.10.10.1:8000"
     redfish_password: "cesardgm"
     redfish_system_id: "/redfish/v1/Systems/102"
   nics:
     -
       mac: "BC:24:11:28:C3:E2"
     -
       mac: "BC:24:11:7A:BD:68"
   instance_info:
     image_source: "oci://10.10.10.5:5500/bifrost/images:centos-9.qcow2-1783316498"
   driver: "redfish"
   ipv4_address: "10.10.10.150"
   properties:
     cpu_arch: "x86_64"
     ram: "2048"
     disk_size: "32"
     cpus: "4"
   name: "servera199"

#--------------------------
# OCI: ISO Images with external Install Manifesto (kickstart, ignition)
#--------------------------
serverb199.maas.lab:
   uuid: "fa1331e3-b94c-48b6-bff8-992ec9f9b067"
   driver_info:
     redfish_verify_ca: false
     redfish_username: "root@pam"
     redfish_address: "https://10.10.10.1:8000"
     redfish_password: "cesardgm"
     redfish_system_id: "/redfish/v1/Systems/103"
   nics:
     -
       mac: "BC:24:11:70:D8:B0"
     -
       mac: "BC:24:11:E5:66:0C"
   instance_info:
     image_source: "oci://10.10.10.5:5500/bifrost/images:ubuntu-noble.qcow2-1783316498"
   driver: "redfish"
   ipv4_address: "10.10.10.151"
   properties:
     cpu_arch: "x86_64"
     ram: "2048"
     disk_size: "32"
     cpus: "4"
   name: "serverb199"

#--------------------------
# HTTP: QCOW Images with baked-in Cloud-Init Install Manifesto
#--------------------------
#workstation199.maas.lab:
#   ipa_kernel_url: "http://genesis.maas.lab:8080/ipa.kernel"
#   ipa_ramdisk_url: "http://genesis.maas.lab:8080/ipa.initramfs"
#   uuid: "0f86778e-c7f2-4712-8cc8-3a5000ad7e69"
#   driver_info:
#     redfish_username: "root@pam"
#     redfish_address: "https://cdglab.duckdns.org:8000"
#     redfish_password: "cesardgm"
#     redfish_system_id: "/redfish/v1/Systems/104"
#   nics:
#     -
#       mac: "BC:24:11:3F:E9:A7"
#     -
#       mac: "BC:24:11:3F:D5:14"
#   instance_info:
#     deploy_interface: "direct"
#     image_source: "oci://genesis.maas.lab:8080/centos-9.qcow"
#     boot-interface: "ipxe"
#   driver: "redfish"
#   ipv4_address: "10.10.10.152"
#   properties:
#     cpu_arch: "x86_64"
#     ram: "2048"
#     disk_size: "32"
#     cpus: "4"
#   name: "workstation199"
#
##--------------------------
## HTTP: ISO Images with external Install Manifesto (kickstart, ignition)
##--------------------------
#training.maas.lab:
#   ipa_kernel_url: "http://genesis.maas.lab:8080/ipa.kernel"
#   ipa_ramdisk_url: "http://genesis.maas.lab:8080/ipa.initramfs"
#   uuid: "9d2258ba-cc95-48c1-a109-d2517e7791a8"
#   driver_info:
#     redfish_username: "root@pam"
#     redfish_address: "https://cdglab.duckdns.org:8000"
#     redfish_password: "cesardgm"
#     redfish_system_id: "/redfish/v1/Systems/105"
#   nics:
#     -
#       mac: "BC:24:11:92:FB:3E"
#     -
#       mac: "BC:24:11:D0:FB:F6"
#   instance_info:
#     deploy_interface: "direct"
#     image_source: "oci://genesis.maas.lab:8080/centos-9.qcow"
#     boot-interface: "ipxe"
#   driver: "redfish"
#   ipv4_address: "10.10.10.153"
#   properties:
#     cpu_arch: "x86_64"
#     ram: "2048"
#     disk_size: "32"
#     cpus: "4"
#   name: "training"