---
test-ironic.maas.lab:
  ipa_kernel_url: "http://genesis.maas.lab:8080/ipa.kernel"
  ipa_ramdisk_url: "http://genesis.maas.lab:8080/ipa.initramfs"
  uuid: "c6c53f30-bc69-4bbb-b7df-05f1900e2fe6"
  instance_info:
    image_source: "http://genesis.maas.lab:8080/deployment_image.qcow2"
    image_os_hash_value: "bc1af1790f523d7aa78900d5cd9d76fb"
    image_os_hash_algo: "sha256"
    
  driver_info:
    redfish_username: "root@pam"
    redfish_address: "https://cdglab.duckdns.org:8000"
    redfish_password: "cesardgm"
    redfish_system_id: "/redfish/v1/Systems/102"
  nics:
    -
      mac: "BC:24:11:28:C3:E2"
  driver: "redfish"
  ipv4_address: "10.10.10.125"
  properties:
    cpu_arch: "x86_64"
    ram: "2048"
    disk_size: "30"
    cpus: "8"
  name: "test-ironic"
