---
# genesis.setup 1_manifesto
#   - Generate Install Manifesto (Kickstart, cloud init, ignition)
#   - Create Config Drive (drivers + manifesto) for cloud installers 
#  
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0
#