---
# genesis.setup 1_manifesto
#   - Generate Install Manifesto (Kickstart, cloud init, ignition)
#   - Create Config Drive (drivers + manifesto) for cloud installers 
#  
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0
#
- name: "B4 - SETUP: Setup Manifesto for Current Node"
  ansible.builtin.include_tasks: "{{ b4_manifesto | default ('1_manifesto/1_os_native.yml') }}" 
  loop:
     - "1_manifesto/1_os_native.yml"    
     #- "1_manifesto/2_cloud.yml"            
  loop_control:
    loop_var: "b4_manifesto"