---
# genesis.setup 2_enroll.yml
#   - Enroll the Node Into Ironic
#       - Ensure BMC Connectivity
#       - Node Inspection
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0
#
- name: "B4 - SETUP: Enroll Current Node Into Ironic"
  ansible.builtin.include_tasks: "{{ b4_enroll | default ('2_enroll/1_delete.yml') }}" 
  loop:
     - "2_enroll/1_delete.yml"   
     - "2_enroll/2_enroll.yml"
     #- "2_enroll/3_inspect.yml"	 	 
  loop_control:
    loop_var: "b4_enroll"