---
# genesis.setup 2_lifecycle.yml
#   - Setup Node Life-Cycle Stages
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0
#

- debug:
    msg: "{{  b4_enroll_node_nics | default('nono') }}"



- name: "B4 - SETUP: Setup Lifecycle Stages for Current Node"
  ansible.builtin.include_tasks: "{{ b4_manifesto | default ('2_lifecycle/8_delete.yml') }}" 
  vars:
     uuid:        "{{ b4_enroll_node_uuid       | default('') }}"
     name:        "{{ b4_enroll_node_name       | default('Unknown') }}" 
     properties:  "{{ b4_enroll_node_properties | default({}) }}"
     driver:      "{{ b4_enroll_node_bmc_driver | default('redfish') }}"
     driver_info: "{{ b4_enroll_node_bmc_driver_info[driver] | default({}) }}"
     nics:        "{{ b4_enroll_node_nics       | default([]) }}"
  loop:
     - "2_lifecycle/8_delete.yml"   
     - "2_lifecycle/1_enroll.yml" 
     #- "2_lifecycle/5_deploy.yml" 		 
  loop_control:
    loop_var: "b4_manifesto"