---
# genesis.setup datamodel.yml
#  - Render data model into test file
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0

#----------------------
# 1.- Dump Bifrost Data Model into File
#---------------------- 
- name: "B4 SETUP - Dump Bifrost Data Model to File"
  connection: local
  ansible.builtin.copy:
    dest: "{{ b4_datamodel_file }}"
    content: "{{ b4_data_model_content | to_nice_yaml(indent=2) }}"
  vars:
    b4_data_model_content:
      uuid: "{{ uuid | default('') }}"
      name: "{{ name | default('') }}"
      properties: "{{ properties | default({}) }}"
      driver: "{{ driver | default('redfish') }}"
      driver_info: "{{ driver_info | default({}) }}"
      instance_info: "{{ instance_info | default({}) }}"
      boot_interface: "{{ boot_interface | default('ipxe') }}"
      deploy_interface: "{{ deploy_interface | default('direct') }}"
      nics: "{{ nics | default([]) }}"
      mac: "{{ mac | default('') }}"
      ipv4_address: "{{ ipv4_address | default('') }}"
      ipv4_subnet_mask: "{{ ipv4_subnet_mask | default('') }}"
      ipv4_router: "{{ ipv4_router | default('') }}"
      provisioning_ipv4_address: "{{ provisioning_ipv4_address | default('') }}"
      power_cycle:      "{{ b4_node_power_cycle_profile | default('manual') }}"  
      clean_steps:   "{{ clean_steps | default([]) }}"
      power_interface: "{{ power_interface | default(driver) }}"
      management_interface: "{{ management_interface | default(driver) }}"
  when:
    - b4_datamodel_file is defined
    - b4_datamodel_file | length > 0