---
# genesis.setup main.yml
#   - Generate Install Manifesto for each Node
#   - Enroll Nodes
#   - Set Node Life-Cycle stages
#     - Clean: BMC steps to wipe disks
#     - Deploy: Boot Interface + Deploy Interface 
#   - Move transitions until Node is in Available State (ready to deploy)
#  
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0
#
- name: "------------------> B3- SETUP BAREMETAL NODES <------------------" 
  ignore_errors: yes
  block:
    - name: "B3 - SETUP"
      ansible.builtin.include_tasks: "{{ b4_stage | default ('1_manifesto.yml') }}"
      loop:
         - "1_manifesto.yml"
         - "2_enroll.yml"
    #     - "3_lifecycle.yml"
    #     - "4_transition.yml"         
      loop_control:
        loop_var: "b4_stage" 
  delegate_to: "{{ groups['target'][0] if groups['target'] is defined else 'localhost' }}"