---
# genesis.setup main.yml
#   - Node Lifecycle Stage 1 - Enroll
#   - Node Lifecycle Stage 2 - Manage
#  
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0
#

- name: "------------------> B4- SETUP BAREMETAL NODE <------------------" 
  block:
  
    #-----------------------------------------------------------------------
    # 1.- Bifrost Data Model (Hyper-Accelerated Eager Evaluation Fact Core)
    #-----------------------------------------------------------------------
    # 1.1.- Load Values as Persistent Static Values in Local Memory Cache
    - name: "B4 SETUP - A) Freeze Dynamic Model into Static RAM Facts"
      ansible.builtin.set_fact:  
        uuid:        "{{ b4_enroll_node_uuid | default('') }}"
        name:        "{{ b4_enroll_node_name | default('') }}" 
        properties:  "{{ b4_enroll_node_chassis_properties | default({}) }}"
        driver:      "{{ b4_enroll_node_bmc_driver | default('redfish') }}"
        driver_info: "{{ b4_node_driver_info | default({}) }}"
        nics:        "{{ b4_enroll_node_nics | default([]) }}"
        mac:              "{{ b4_enroll_nic_provision_mac | default('') }}"	 
        ipv4_address:     "{{ b4_enroll_nic_provision_ip | default('127.0.0.1') }}"
        ipv4_subnet_mask: "{{ b4_enroll_nic_provision_netmask | default('255.255.255.0') }}" 
        ipv4_router:      "{{ b4_enroll_nic_provision_gateway | default('127.0.0.1') }}" 
        boot_interface:   "{{ b4_node_boot_interface | default('ipxe') }}"
        deploy_interface: "{{ b4_node_deploy_interface | default('direct') }}"
        power_interface:  "{{ b4_node_power_interface | default(b4_enroll_node_bmc_driver) | default('redfish') }}"
        management_interface: "{{ b4_node_management_interface | default('noop') }}"
        hardware_type:    "{{ b4_node_hardware_type | default(b4_enroll_node_bmc_driver) | default('redfish') }}" 
        instance_info:    "{{ b4_node_instance_info | default({}) }}"
        provisioning_ipv4_address: "{{ b4_enroll_nic_provision_ip | default('127.0.0.1') }}"
        clean_steps:      "{{ b4_clean_steps | default([]) }}"
      delegate_to: localhost

    # 1.2.- Render Values into a Persistent Audit Ledger File 
    - name: "B4 SETUP - B) Commit Frozen Data Model Layout into Ledger"
      ansible.builtin.include_tasks: "datamodel.yml"

    # 1.3.- Dump File on Screen 
    - name: "B4 SETUP - C) Dump Local File Content to Terminal (Pure Local Cat)"
      ansible.builtin.debug:
        msg: "{{ lookup('ansible.builtin.file', b4_baremetal_vars_file) | string }}"
      delegate_to: localhost

    #-----------------------
    # 2.- Setup the Node in Ironic
    #-----------------------

    # => 2.1.- Stage 1: Enroll - Outband Control
    #.................................
    - ansible.builtin.include_tasks: "1_enroll/1_os_manifesto.yml"
    #- ansible.builtin.include_tasks: "1_enroll/2_config_drive.yml"
    - ansible.builtin.include_tasks: "1_enroll/3_delete.yml"
    - ansible.builtin.include_tasks: "1_enroll/4_outband.yml"
 
    # => 2.2.- Stage 2: Manage - Inband Provision
    #.................................
    - ansible.builtin.include_tasks: "2_manage/1_inband.yml"
    - ansible.builtin.include_tasks: "2_manage/2_boot_order.yml"
      when: 
        - b4_set_boot_order is defined
        - b4_set_boot_order | bool
    - ansible.builtin.include_tasks: "2_manage/3_power_interfaces.yml"
    - ansible.builtin.include_tasks: "2_manage/4_lifecycle.yml"
      vars:
        b4_lifecycle_instructions: "{{ b4_lifecycle_api_calls.setup | default([]) }}" 
    - ansible.builtin.include_tasks: "2_manage/5_available.yml"

  delegate_to: "{{ groups['target'][0] if groups['target'] is defined else 'localhost' }}"