---
# genesis.setup 1_enroll/1_os_manifesto.yml
#   - Generate OS Native Installer Manifesto:
#      - cloud-init (Ubuntu)
#      - kickstart  (RedHat)
#      - autoyast   (SuSE)
#      - preseed    (Debian)
#      - ignition   (CoreOS)
#      - combustion (MicroOS)
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0
#

#---------------------------------------
# 0. Log Entry
#---------------------------------------   
- name: "B4 SETUP - 1.- Enroll: 1.0) Freeze Manifesto Data Model"
  ansible.builtin.set_fact:
    j2_profile:         "{{ b4_node_os_profile                 | default('None') }}"  
    j2_input:           "{{ b4_node_os_manifesto['defaults']   | default({})   }}"
    j2_os_profiles:     "{{ b4_node_os_manifesto['os_version'] | default({})   }}"
    j2_system_profiles: "{{ b4_node_os_manifesto['system']     | default({})   }}"
    j2_node_profiles:   "{{ b4_node_os_manifesto['node']       | default({})   }}"
    j2_hostname:        "{{ b4_enroll_node_name  | default('')   }}" 

#---------------------------------------
# 1. OS Install Manifesto
#--------------------------------------- 
- name: "B4 SETUP - 1.- Enroll: 1) Rendering OS Installation Manifesto Files" 
  block:
   
    # 1.1 Manifesto Folder
    - name: "B4 SETUP - 1.- Enroll: 1.1) Create Manifesto Folders"
      ansible.builtin.file:
        path: "{{ b4_folder }}"
        state: "directory"  
        recurse: true
      vars:
        b4_folder: "{{ b4_file | default('') | string | dirname }}"
      when:
        - b4_file is defined
        - b4_file is not none
        - b4_file is string		
      loop: "{{ b4_node_manifesto_files | default([]) }}"
      loop_control:
        loop_var: "b4_file" 

    # 1. 2. Manifesto Rendering (KickStart, Cloud-Init, AutoYast, Preseed, Ignition)
    - name: "B4 SETUP - 1.- Enroll: 1.2) Rendering OS Installation Manifesto"
      ansible.builtin.template:
        src:   "{{ b4_node_manifesto_src  | default(omit) }}"
        dest:  "{{ b4_node_manifesto_dest | default(omit)  }}"
      vars:     
        b4_node_manifesto_default_dest: "{{ b4_node_manifesto_files[0] | default(b4_node_default_manifesto_file) }}"
        b4_node_manifesto_dest: "{{ b4_node_manifesto_files[b4_node_manifesto_dest_index] | default(b4_node_manifesto_default_dest) }}"
      when:
        - b4_node_manifesto_files is defined
        - b4_node_manifesto_files is not none
        - b4_node_manifesto_files is not string
        - b4_node_manifesto_files is iterable
        - b4_node_manifesto_files is not mapping
      loop: "{{ b4_os_manifesto_templates | default([]) }}"
      loop_control:
        loop_var: "b4_node_manifesto_src"
        index_var: "b4_node_manifesto_dest_index"

#---------------------------------------
# 2. OS Post Install Scripts Rendering
#--------------------------------------- 
- vars:
    b4_postinstall_scripts_subfolder: "post_scripts"
  block:

    # 2.1. Post Install Scripts Folder
    - name: "B4 SETUP - 1.- Enroll: 1.3) Create OS Installation PostInstall Folder"
      ansible.builtin.file:
        path: "{{ b4_folder }}"
        state: "directory"  
        recurse: true
      vars: 
        b4_folder: "{{ b4_script.dest | default('') | string | dirname }}/{{ b4_postinstall_scripts_subfolder }}"
      when:
        - b4_script.dest is defined
        - b4_script.dest is not none
        - b4_script.dest is string			
      loop: "{{ b4_os_postinstall_local_scripts_list | default([])}}"
      loop_control:
        loop_var: "b4_script"


    # 2.2. Render Post Install Scripts
    - name: "B4 SETUP - 1.- Enroll: 1.4) Rendering OS Installation PostInstall Scripts"
      ansible.builtin.copy:
        content: "{{ b4_script.content | default('') }}"
        dest: "{{ b4_dest }}"
      vars: 
        b4_folder: "{{ b4_script.dest | default('') | string | dirname }}/{{ b4_postinstall_scripts_subfolder }}"
        b4_name:  "{{ b4_script.dest | default('') | string | basename }}"
        b4_dest: "{{ b4_folder }}/{{ b4_name }}" 
      when:
        - b4_script.dest is defined
        - b4_script.dest is not none
        - b4_script.dest is string
        - b4_script.content is defined
        - b4_script.content is not none
        - b4_script.content is string	
      loop: "{{ b4_os_postinstall_local_scripts_list | default([])}}"
      loop_control:
        loop_var: "b4_script"
  
  #run_once: yes