---
# genesis.setup 1_enroll/1_os_manifesto.yml
#   - Generate Install OS Native Installer Manifesto:
#      - cloud-init
#      - kickstart
#      - ignition
#      - preseed
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0
#
- name: "B4 SETUP - 1.- Enroll: 1) Rendering OS Installation Manifesto Files" 
  vars:
    # Manifesto Files
    b4_os_manifesto_templates: "{{ b4_node_os_manifesto['template'] | default([]) }}"
    b4_node_manifesto_files:   "{{ b4_node_os_manifesto['file']     | default([]) }}"
    b4_node_default_manifesto_file: "{{ b4_repo_manifesto_path }}/{{ b4_node_name }}"
    
    # Manifesto Jinja2 Rendering Properties
    j2_profile:    "{{ b4_node_os_profile               | default('None') }}"  
    j2_input:      "{{ b4_node_os_manifesto['defaults'] | default({}) }}"
    j2_os_profiles:     "{{ b4_node_os_manifesto['os_version']  | default({}) }}"
    j2_system_profiles: "{{ b4_node_os_manifesto['system'] | default({}) }}"	
    j2_node_profiles:   "{{ b4_node_os_manifesto['node'] | default({}) }}"

  block:
  
    #---------------------------------------
    # 1. Manifest Folder
    #---------------------------------------   
    - name: "B4 SETUP - 1.- Enroll: 1.1) Create Manifesto Folders"
      file:
         path: "{{ b4_folder }}"
         state: "directory"  
         recurse: true
      vars:
         b4_folder: "{{ b4_file | string | dirname | default(omit) }}"
      loop: "{{ b4_node_manifesto_files | default([]) }}"
      loop_control:
        loop_var: "b4_file" 
               
    #---------------------------------------
    # 2. Manifest Rendering (KickStart, Cloud-Init, Ignition, Preseed)
    #---------------------------------------
    - name: "B4 SETUP - 1.- Enroll: 1.2) Rendering OS Installation Manifest"
      ansible.builtin.template:
        src:   "{{ b4_node_manifesto_src  | default(omit) }}"
        dest:  "{{ b4_node_manifesto_dest | default(omit)  }}"
      vars:     
        b4_node_manifesto_default_dest: "{{ b4_node_manifesto_files[0] | default(b4_node_default_manifesto_file) }}"
        b4_node_manifesto_dest: "{{ b4_node_manifesto_files[b4_node_manifesto_dest_index] | default(b4_node_manifesto_default_dest) }}"
      loop: "{{ b4_os_manifesto_templates | default([]) }}"
      loop_control:
        loop_var: "b4_node_manifesto_src"
        index_var: "b4_node_manifesto_dest_index"