---
# genesis.setup 1_enroll/3_delete.yml
#   - Delete Allocations
#   - Set Nodes to Maintanance Mode
#   - Clear Nodes from Ironic Database
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0
#
- name: "B4 SETUP - Enroll: Delete Node" 
  ignore_errors: yes
  block: 
    - ansible.builtin.include_role: 
        name: "{{ b4_delete.name }}"
      when: 
        - b4_delete.name is defined
        - b4_delete.condition | default(true) | bool 
      loop: "{{ b4_delete_roles | default([]) }}"
      loop_control:
        loop_var: "b4_delete" 