---
# genesis.deploy default
#  - Unattended OS installation
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0

######################################################
#  GENESIS PATHS (global for update all genesis roles at once)
######################################################
# 1.- Repos Paths
genesis_repo_path:     "{{ role_path | dirname | dirname | realpath }}/repo"
genesis_local_repo_url: "file://{{ genesis_repo_path | realpath }}"

# 2.- Bifrost Role Paths
genesis_bifrost_role_name: "genesis.bifrost"
genesis_bifrost_path:  "{{ role_path }}/../{{ genesis_bifrost_role_name }}"
genesis_bifrost_roles: "{{ genesis_bifrost_path | realpath }}/{{ genesis_bifrost_role_name }}/playbooks/roles"
genesis_bifrost_files_path: "{{ genesis_bifrost_path | realpath }}/files"
genesis_bifrost_venv_dir: "{{ lookup('env', 'VENV') or '/opt/stack/bifrost' }}"

# 3.- Bifrost Data Model Create on SetUp Stage
# Corregido: Añadidas comillas obligatorias en YAML
b5_baremetal_fact_caching_connection: "{{ lookup('ansible.builtin.config', 'fact_caching_connection', plugin_type='cache', plugin_name='jsonfile', errors='ignore') }}"
b5_baremetal_setup_vars_path: "{{ b5_baremetal_fact_caching_connection | default('/tmp', boolean=True) }}"
b5_baremetal_vars_filename: "genesis_{{ inventory_hostname }}.yml"
b5_baremetal_vars_file: "{{ b5_baremetal_setup_vars_path }}/{{ b5_baremetal_vars_filename }}"

######################################################
#  BIFROST ROLES DEFINITION 
######################################################
genesis_baremetal_deploy_roles:
   - name: "bifrost-deploy-nodes-dynamic"


######################################################
#  DEPLOY URLS
######################################################
#------------------
# 1.- Inband Provision URLs
#------------------
b5_url_protocol: "http"
b5_url_genesis_ipv4:    "{{ hostvars[groups['target'][0]]['dhcp_address'] | default('127.0.0.1/24') }}"
b5_url_genesis_ip:      "{{ b5_url_genesis_ipv4 | ansible.utils.ipaddr('address') }}"
b5_url_genesis_gateway: "{{ b5_url_genesis_ipv4 | ansible.utils.ipaddr('first_usable') }}"
b5_url_genesis_netmask: "{{ b5_url_genesis_ipv4 | ansible.utils.ipaddr('netmask') }}"

b5_genesis_port:
  http:  "{{ genesis_http_port  | default(file_url_port)     | default('8080') }}"
  https: "{{ genesis_https_port | default(file_url_port_tls) | default('8083') }}" 
  oci:   "{{ genesis_https_oci  | default(registry_port)     | default('5500') }}"
  ironic: "{{ genesis_ironic_port  | default(ironic_api_port)     | default('6385') }}"

b5_url_genesis_port: "{{ b5_genesis_port[b5_url_protocol] is defined | ternary (':','','') }}{{ b5_genesis_port[b5_url_protocol] | default('') }}"
b5_url_genesis_url: "{{ genesis_address | default(b5_url_genesis_ip) }}{{ b5_url_genesis_port }}"
b5_url_ironic_port: "{{ b5_genesis_port['ironic'] is defined | ternary (':','','') }}{{ b5_genesis_port['ironic'] | default('') }}"
b5_url_ironic_url: "{{b5_url_protocol}}://{{ genesis_address | default(b5_url_genesis_ip) }}{{ b5_url_ironic_port }}"

#------------------
# 2.- Proxmo Bypass
#------------------
#b5_proxmox_root_password: "cesardgm"
b5_proxmox_hypervisor_ip: "10.10.51.1"
