---
# genesis.test 3_zone/proxmox_nics.yml
#  - Plug/Unplug Nic from VMs
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0

- vars:
    # 1.- Action 
    t3_selector: "{{ t3_nics_state | default('present') }}"

    # 2.- Bridges of the Zone 
    t3_zone_internet_bridge: "{{ t1_proxmox_internet_bridge | default('vmbr0') }}"
    t3_zone_bridge_names: "{{ t3_zone_bridge | default([]) | map(attribute='name') | list }}"
    t3_zone_bridge_names_concat: "{{ t3_zone_bridge_names | join('|') }}"

    # 3.- Current VM Details 
    t3_proxmox_vmid: "{{ t3_proxmox_vm.vmid | default(omit) }}"
    t3_proxmox_config: "{{ t3_proxmox_vm.config | default({}) }}"

    # 4.- NICs of the VM 
    t3_proxmox_nics_list_capture: "{{ t3_proxmox_config | dict2items | selectattr('key', 'match', '^net\\d+$') | list }}"  
    t3_proxmox_nics_filtered_raw: "{{ t3_proxmox_nics_list_capture | map(attribute='value') | list }}"
    t3_proxmox_nics_list: "{{ t3_proxmox_nics_list_capture | rejectattr('value', 'contains', 'bridge=' ~ t3_zone_internet_bridge) | list }}"
    t3_proxmox_nics_absent: "{{ t3_proxmox_nics_list | map(attribute='key') | list | join(',') }}"
    t3_proxmox_nics_dict: "{{ t3_proxmox_nics_list | items2dict }}"
    t3_proxmox_nics_filtered: "{{ t3_proxmox_nics_list | map(attribute='value') | list }}"
    t3_proxmox_nics_connected: "{{ t3_proxmox_nics_filtered | select('regex', 'bridge=(' ~ t3_zone_bridge_names_concat ~ ')') | list }}"   
    t3_proxmox_vm_in_zone: "{{ t3_proxmox_nics_connected | length > 0 }}"

    # 5.- Genesis Details
    t3_proxmox_genesis_detection: "{{ t3_proxmox_nics_filtered_raw | select('regex', (genesis_nics.internet.mac | default('00:00') | lower)) | list }}"
    t3_proxmox_vm_is_genesis: "{{ t3_proxmox_genesis_detection | length > 0 }}"
    t3_proxmox_nics_genesis: "{{ t1_proxmox_nics_genesis | default({}) }}"
    t3_proxmox_vm_nics: "{{ t3_proxmox_nics_genesis if (t3_proxmox_vm_is_genesis | bool) else (t3_proxmox_nics_dict | default({})) }}"

    # 6.- Ansible Calls
    t3_proxmox_nics_ansible_call:
      present: 
        - { state: 'stopped', timeout: 15, force: false }      
        - { state: 'stopped', timeout: 10, force: true  }
        - { net: "{{ t3_proxmox_vm_nics | default(omit) }}", nic_update: true, update_unsafe: true } 
        
      absent: 
        - { state: 'stopped', timeout: 15, force: false }      
        - { state: 'stopped', timeout: 10, force: true  }
        - { delete: "{{ t3_proxmox_nics_absent | default(omit) }}" }

    # 7.-  CLI Calls 
    t3_cli_nics_present_args: >
      {% for key, val in (t3_proxmox_vm_nics | default({})).items() -%}
      --{{ key }} "{{ val }}"{{ ' ' }}
      {%- endfor %}
    t3_cli_nics_absent_args: " --delete {{ t3_proxmox_nics_absent | default('') }}"
    t3_cli_commands: 
      present: |
        qm shutdown {{ t3_proxmox_vmid | default('') }} --timeout 15 || true
        qm stop {{ t3_proxmox_vmid | default('') }}
        qm set {{ t3_proxmox_vmid | default('') }} {{ t3_cli_nics_present_args | default('') }}

      absent: |
        qm shutdown {{ t3_proxmox_vmid | default('') }} --timeout 15 || true
        qm stop {{ t3_proxmox_vmid | default('') }}
        qm set {{ t3_proxmox_vmid | default('') }} {{ t3_cli_nics_absent_args | default('') }}

  block:

    # --- PRE-FLIGHT DEBUG ---
    - name: "T3 - PROXMOX_NICS -3- Zone: 5) DEBUG VM Specs to Check if any NIC in Zone"
      ansible.builtin.debug:
        msg: "{{ debug_raw_text.splitlines() }}"
      vars:
        debug_raw_text: |
          --- ENV & ZONE CONFIG ---
          VMID: {{ t3_proxmox_vmid | default('t3_proxmox_vmid NOT DEFINED') }}
          Internet Bridge: {{ t3_zone_internet_bridge | default('t3_zone_internet_bridge NOT DEFINED') }}
          Bridges List: {{ t3_zone_bridge_names | default('t3_zone_bridge_names NOT DEFINED') }}
          Bridges Regex: {{ t3_zone_bridge_names_concat | default('t3_zone_bridge_names_concat NOT DEFINED') }}
          
          --- NETWORKING PIPELINE ---
          [2.1] Captured: {{ t3_proxmox_nics_list_capture | default('t3_proxmox_nics_list_capture NOT DEFINED') }}
          [2.2] No WAN: {{ t3_proxmox_nics_list | default('t3_proxmox_nics_list NOT DEFINED') }}
          [2.3] Flat Values: {{ t3_proxmox_nics_filtered | default('t3_proxmox_nics_filtered NOT DEFINED') }}
          [2.4] Connected: {{ t3_proxmox_nics_connected | default('t3_proxmox_nics_connected NOT DEFINED') }}
          
          --- GENESIS SYSTEM IDENTITY DETECTION ---
          Target Genesis MAC:   {{ genesis_nics.internet.mac | default('genesis_nics.internet.mac NOT DEFINED IN ENVIRONMENT VARS') }}
          Genesis Match Found:  {{ t3_proxmox_genesis_detection | default('t3_proxmox_genesis_detection NOT DEFINED') }}
          Is Node Genesis?:     {{ t3_proxmox_vm_is_genesis | default('t3_proxmox_vm_is_genesis NOT DEFINED') }}
          Profile Genesis Dict: {{ t3_proxmox_nics_genesis | default('t3_proxmox_nics_genesis NOT DEFINED') }}
          
          --- FINAL ACTIONS ---
          Affected: {{ t3_proxmox_vm_in_zone | default('t3_proxmox_vm_in_zone NOT DEFINED') }}
          Dict Present: {{ t3_proxmox_nics_dict | default('t3_proxmox_nics_dict NOT DEFINED') }}
          Nics Absent: {{ t3_proxmox_nics_absent | default('t3_proxmox_nics_absent NOT DEFINED') }}
          Payload Net: {{ t3_proxmox_vm_nics | default('t3_proxmox_vm_nics NOT DEFINED') }}
          
          --- EXECUTION MATRICES (PLANNED PAYLOADS) ---
          
          [Ansible Loop Payload]:
          {{ t3_proxmox_nics_ansible_call | default('NO CALL DEFINED') }}
          
          [CLI Shell Command Call]:
          {{ t3_cli_commands | default('NO COMMAND DEFINED') }}
      delegate_to: localhost

    #-----------------------------------------------------------------------
    # 1.- Nics Update via Proxmox Module  
    #-----------------------------------------------------------------------
    - name: "T3 - PROXMOX_NICS -3- Zone: 5) Manage VM Power State and NIC Specs"
      community.proxmox.proxmox_kvm:
        api_host: "127.0.0.1"
        api_user: "{{ t1_hypervisor_api_user         | default(omit) }}"
        api_password: "{{ t1_hypervisor_api_password | default(omit) }}"
        validate_certs: false
        node: "{{ t1_hypervisor_api_hostname | default('pve') }}" 
        vmid: "{{ t3_proxmox_vmid    | default(omit) }}"
        # Power configuration
        state: "{{ t3_nics_command['state'] | default(omit) }}"
        timeout: "{{ t3_nics_command['timeout'] | default(omit) }}"
        force: "{{ t3_nics_command['force'] | default(omit) }}"
        # Network configuration
        net: "{{ t3_nics_command['net'] | default(omit) }}"
        delete: "{{ t3_nics_command['delete'] | default(omit) }}"
        update: "{{ t3_nics_command['nic_update'] | default(omit) }}"
        update_unsafe: "{{ t3_nics_command['update_unsafe'] | default(omit) }}"
      loop: "{{ t3_proxmox_nics_ansible_call[t3_selector] | default([]) }}"
      loop_control:
        loop_var: t3_nics_command
      failed_when: false
      when:
        - (t3_proxmox_vm_in_zone | default(false) | bool) or (t3_proxmox_vm_is_genesis | default(false) | bool)
        - (t3_proxmox_vm_nics | default({}) | length > 0) or (t3_proxmox_nics_absent | default('') | length > 0)
      delegate_to: "{{ t1_hypervisor_node | default('localhost') }}"

  rescue:

    #-----------------------------------------------------------------------
    # 2.- Nics Update via Proxmox CLI 
    #-----------------------------------------------------------------------
    - name: "T3 - PROXMOX_NICS -3- Zone: 5.4) RESCUE: Modify VM NIC Specs via qm set"
      ansible.builtin.shell: 
        cmd: "{{ t3_cli_commands[t3_selector] | default('') }}"
      register: pve_nics_cli_result
      changed_when: true
      when: 
        - t3_proxmox_vm_in_zone | default(false) | bool 
        - (t3_proxmox_vm_nics | default({}) | length > 0) or (t3_proxmox_nics_absent | default('') | length > 0)
      delegate_to: "{{ t1_hypervisor_node | default('localhost') }}"
