---
# genesis.test 3_zone/proxmox_nics.yml
#  - Plug/Unplug Nic from VMs
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0

- name: "T2 - TESTING ENVIRONMENT -3- Zone: 5) Orquestar Tarjetas de Red Virtuales (NICs)"
  vars:
    t3_zone_internet_bridge: "{{ t1_proxmox_internet_bridge | default('vmbr0') }}"
    t3_zone_bridge_names: "{{ t3_zone_bridge | default([]) | map(attribute='name') | list }}"
    t3_zone_bridge_names_concat: "{{ t3_zone_bridge_names | join('|') }}"
    t3_proxmox_vmid: "{{ t3_proxmox_vm.vmid | default(omit) }}"
    t3_proxmox_config: "{{ t3_proxmox_vm.config | default({}) }}"
    t3_proxmox_nics_list_capture: "{{ t3_proxmox_config | dict2items | selectattr('key', 'match', '^net\\d+$') | list }}"  
    t3_proxmox_nics_filtered_raw: "{{ t3_proxmox_nics_list_capture | map(attribute='value') | list }}"
    t3_proxmox_genesis_detection: "{{ t3_proxmox_nics_filtered_raw | select('regex', (genesis_nics.internet.mac | default('00:00') | lower)) | list }}"
    t3_proxmox_vm_is_genesis: "{{ t3_proxmox_genesis_detection | length > 0 }}"
    t3_proxmox_nics_list: "{{ t3_proxmox_nics_list_capture | rejectattr('value', 'contains', 'bridge=' ~ t3_zone_internet_bridge) | list }}"
    t3_proxmox_nics_absent: "{{ t3_proxmox_nics_list | map(attribute='key') | list | join(',') }}"
    t3_proxmox_nics_dict: "{{ t3_proxmox_nics_list | items2dict }}"
    t3_proxmox_nics_filtered: "{{ t3_proxmox_nics_list | map(attribute='value') | list }}"
    t3_proxmox_nics_connected: "{{ t3_proxmox_nics_filtered | select('regex', 'bridge=(' ~ t3_zone_bridge_names_concat ~ ')') | list }}"   
    t3_proxmox_vm_in_zone: "{{ t3_proxmox_nics_connected | length > 0 }}"
    t3_proxmox_nics_genesis: "{{ t1_proxmox_nics_genesis | default({}) }}"
    t3_proxmox_vm_nics: "{{ t3_proxmox_nics_genesis if t3_proxmox_vm_is_genesis | bool else t3_proxmox_nics_dict }}"

  block:

    # --- PRE-FLIGHT DEBUG ---
    - name: "T3 - PROXMOX_NICS -3- Zone: 5.0) DEBUG VM Specs"
      ansible.builtin.debug:
        msg: |
          --- ENV & ZONE CONFIG ---
          VMID: {{ t3_proxmox_vmid | default('t3_proxmox_vmid NOT DEFINED') }}
          State: {{ t3_nics_state | default('t3_nics_state NOT DEFINED') }}
          Internet Bridge: {{ t3_zone_internet_bridge | default('t3_zone_internet_bridge NOT DEFINED') }}
          Bridges List: {{ t3_zone_bridge_names | default('t3_zone_bridge_names NOT DEFINED') | to_json }}
          Bridges Regex: {{ t3_zone_bridge_names_concat | default('t3_zone_bridge_names_concat NOT DEFINED') }}
          
          --- NETWORKING PIPELINE ---
          [2.1] Captured: {{ t3_proxmox_nics_list_capture | default('t3_proxmox_nics_list_capture NOT DEFINED') | to_json }}
          [2.2] No WAN: {{ t3_proxmox_nics_list | default('t3_proxmox_nics_list NOT DEFINED') | to_json }}
          [2.3] Flat Values: {{ t3_proxmox_nics_filtered | default('t3_proxmox_nics_filtered NOT DEFINED') | to_json }}
          [2.4] Connected: {{ t3_proxmox_nics_connected | default('t3_proxmox_nics_connected NOT DEFINED') | to_json }}
          
          --- GENESIS SYSTEM IDENTITY DETECTION ---
          Target Genesis MAC:   {{ genesis_nics.internet.mac | default('genesis_nics.internet.mac NOT DEFINED IN ENVIRONMENT VARS') }}
          Genesis Match Found:  {{ t3_proxmox_genesis_detection | default('t3_proxmox_genesis_detection NOT DEFINED') | to_json }}
          Is Node Genesis?:     {{ t3_proxmox_vm_is_genesis | default('t3_proxmox_vm_is_genesis NOT DEFINED') }}
          Profile Genesis Dict: {{ t3_proxmox_nics_genesis | default('t3_proxmox_nics_genesis NOT DEFINED') | to_json }}
          
          --- FINAL ACTIONS ---
          Affected: {{ t3_proxmox_vm_in_zone | default('t3_proxmox_vm_in_zone NOT DEFINED') }}
          Dict Present: {{ t3_proxmox_nics_dict | default('t3_proxmox_nics_dict NOT DEFINED') | to_json }}
          Nics Absent: {{ t3_proxmox_nics_absent | default('t3_proxmox_nics_absent NOT DEFINED') | to_json }}
          Payload Net: {{ t3_proxmox_vm_nics | default('t3_proxmox_vm_nics NOT DEFINED') | to_json }}
      delegate_to: localhost

    #-----------------------------------------------------------------------
    # 1.- Nics Update via Proxmox Module  
    #-----------------------------------------------------------------------
    - name: "T3 - PROXMOX_NICS -3- Zone: 5.2) Add NICs"
      community.proxmox.proxmox_kvm:
        api_host: "127.0.0.1"
        api_user: "{{ t1_hypervisor_api_user         | default(omit) }}"
        api_password: "{{ t1_hypervisor_api_password | default(omit) }}"
        validate_certs: false
        node: "{{ t1_hypervisor_api_hostname | default('pve') }}" 
        vmid: "{{ t3_proxmox_vmid    | default(omit) }}"
        net:  "{{ t3_proxmox_vm_nics | default(omit) }}"
        update: true
        update_unsafe: true
      when:
        - (t3_proxmox_vm_in_zone | bool) or (t3_proxmox_vm_is_genesis | bool)
        - (t3_proxmox_vm_nics | length) > 0
        - "'absent' not in (t3_nics_state | default(''))"
      delegate_to: "{{ t1_hypervisor_node | default('localhost') }}"

    - name: "T3 - PROXMOX_NICS -3- Zone: 5.3) Delete NICs"
      community.proxmox.proxmox_kvm:
        api_host: "127.0.0.1"
        api_user: "{{ t1_hypervisor_api_user         | default(omit) }}"
        api_password: "{{ t1_hypervisor_api_password | default(omit) }}"
        validate_certs: false
        node: "{{ t1_hypervisor_api_hostname | default('pve') }}" 
        vmid: "{{ t3_proxmox_vmid    | default(omit) }}"
        # Inyecta el string crudo limpio separado por comas (ej: "net1,net2")
        delete: "{{ t3_proxmox_nics_absent | default(omit) }}"
      when:
        - t3_proxmox_vm_in_zone | default(false) | bool
        - t3_proxmox_nics_absent | default('') | length > 0
        - "'absent' in (t3_nics_state | default(''))"
      delegate_to: "{{ t1_hypervisor_node | default('localhost') }}"

  rescue:

    #-----------------------------------------------------------------------
    # 2.- Nics Update via Proxmox CLI 
    #-----------------------------------------------------------------------
    - name: "T3 - PROXMOX_NICS -3- Zone: 5.4) RESCUE: Modify VM NIC Specs via qm set"
      ansible.builtin.shell: >-
        qm set {{ t3_proxmox_vmid | default(201) }}
        {% for key, val in (t3_proxmox_vm_nics | default({})).items() %}
        {{ '--delete ' ~ key if val == 'delete' else '--' ~ key ~ ' "' ~ val ~ '"' }}
        {% endfor %}
      register: pve_nics_cli_result
      changed_when: true
      when: 
        - t3_proxmox_vm_in_zone | default(false) | bool 
        - t3_proxmox_vm_nics    | default({})    | length > 0
      delegate_to: "{{ t1_hypervisor_node | default('localhost') }}"
