---
# genesis.test 3_nodes/proxmox_bridge.yml
#  - Dynamically Ensure Provision and RedFish Networks are present on Hypervisor
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0

- name: "T3 - PROXMOX_BRIDGE -3- Zone: 2.0) Display SDN Bridges Topology"
  ansible.builtin.debug:
    msg: |
      --- SDN Bridges Topology Specs ---
      {% for bridge in t1_airgap_zone.bridges | default([]) %}
      Net{{ loop.index0 }} (Bridge Name): {{ bridge.name }}
      ├─ Driver / Type: {{ bridge.type | default('ovs') | upper }}
      ├─ IPv4 Address:  {{ bridge.ipv4 | default('[ipv4 is NOT DEFINED]') }}
      └─ Node Gateway:   {{ bridge.ipv4 | default('0.0.0.0/0') | ansible.utils.ipaddr('address') }} (Hipervisor IP)
      {% else %}
      [ No bridges are defined in t1_airgap_zone.bridges]
      {% endfor %}
  delegate_to: localhost

- block:

    #-----------------------------------------------------------------------
    # 1.- Bridges Creation via Proxmox SDN (Environment Level)
    #-----------------------------------------------------------------------
    - name: "T3 - PROXMOX_BRIDGE -3- Zone 2.1) Ensure Provision and Redfish VNETs are present in Proxmox cluster"
      community.proxmox.proxmox_vnet:
        api_host: "127.0.0.1"
        api_user: "{{ t1_hypervisor_api_user | default(omit) }}"
        api_password: "{{ t1_hypervisor_api_password | default(omit) }}"
        validate_certs: false
        vnet: "{{ t3_proxmox_bridge.name | default('bridge' ~ t3_proxmox_index, true) }}"
        tag:  "{{ t1_proxmox_vnet_tag    | default(omit) }}"
        zone: "{{ t1_airgap_zone.zone    | default(omit) }}"
        state: "{{ t3_zone_state | default('present') }}"
      loop: "{{ t1_airgap_zone.bridges | default([]) }}"
      loop_control:
        loop_var: "t3_proxmox_bridge"
        index_var: "t3_proxmox_index" 
      register: t3_network_provision_api
      delegate_to: "{{ t1_hypervisor_node | default('localhost') }}"

  rescue:

    #-----------------------------------------------------------------------
    # 2.- Bridges Creation via CLI
    #-----------------------------------------------------------------------  
    - name: "T3 - PROXMOX_BRIDGE -3- Zone: 2.2) RESCUE: Check existing networking states on Hypervisor"
      become: true
      ansible.builtin.shell: "ls /sys/class/net/{{ t3_bride_name }} 2>/dev/null"
      register: t3_network_cli_probes
      failed_when: false
      changed_when: false
      vars:
        t3_bride_name: "{{ t3_proxmox_bridge.name | default('bridge' ~ t3_proxmox_index, true) }}" 
      loop: "{{ t1_airgap_zone.bridges | default([]) }}"
      loop_control:
        loop_var: "t3_proxmox_bridge" 
        index_var: "t3_proxmox_index" 
      delegate_to: "{{ t1_hypervisor_node | default('localhost') }}"

    - name: "T3 - PROXMOX_BRIDGE -3- Zone: 2.3) RESCUE: Inject configuration for Provision and Redfish bridges in interfaces file"
      become: true
      ansible.builtin.blockinfile:
        path: /etc/network/interfaces
        marker: "# {mark} ANSIBLE MANAGED GENESIS BRIDGES"
        block: |
          {% for bridge in t1_airgap_zone.bridges | default([]) %}
          auto {{ bridge.name | default('bridge' ~ loop.index0, true) }}
          iface {{ bridge.name | default('bridge' ~ loop.index0, true) }} inet static
                  address {{ bridge.ipv4 }}
                  {% if (bridge.type | default('') | lower) == 'ovs') %}
                  ovs_type OVSBridge
                  {% else %}
                  bridge_ports none
                  bridge_stp off
                  bridge_fd 0
                  {% endif %}
          {% endfor %}
      register: t3_network_file_modification
      delegate_to: "{{ t1_hypervisor_node | default('localhost') }}"
      when: t3_network_cli_probes is failed

    - name: "T3 - PROXMOX_BRIDGE -3- Zone: 2.4) RESCUE: Reload Proxmox networking sub-system to apply changes in live"
      become: true
      ansible.builtin.shell: |
        {% for bridge in t1_airgap_zone.bridges | default([]) %}
          ifdown {{ bridge.name | default('bridge' ~ loop.index0, true) }} --force 2>/dev/null || true
          ifup {{ bridge.name | default('bridge' ~ loop.index0, true) }}
        {% endfor %}
      delegate_to: "{{ t1_hypervisor_node | default('localhost') }}"
      when: t3_network_file_modification is changed