---
# genesis playbooks/setup.yml
#  - Enroll inventory to Ironic
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0

#---------------------------------
#  GATHERING FACT
#---------------------------------
- name: "Gather facts on localhost"
  hosts: localhost
  become: no
  gather_facts: yes

#---------------------------------
#  SETUP NODES
#---------------------------------
- hosts: "baremetal"
  become: no
  gather_facts: no
  roles:
    - role: "genesis.setup"
      when: 
      - not (skip_install | default(false) | bool)
      - (genesis_stage is not defined)  or  (genesis_stage=='B4') 