---
# genesis playbooks/deploy.yml
#   - Unattended OS installation
#
# SPDX-FileCopyrightText: © 2026 Genesis System 
# SPDX-License-Identifier: Apache-2.0
# 	
#---------------------------------
#  DEPLOY NODES
#---------------------------------
- name: "STEP 2 - Deploy Nodes"
  ansible.builtin.import_playbook: "{{bifrost_shoot_path | trim}}/deploy-dynamic.yaml"
  become: true
  vars:  
    deploy_config_drive: "none"
    bifrost_shoot_path: >-
     {{ bifrost_playbooks_path 
      | default(playbook_dir + '/../roles/openstack.bifrost/openstack.bifrost/playbooks', True)       
      | realpath  }}