---
# genesis playbooks/baremetal.yml
#  - Baremetal Nodes Life Cycle
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0

#---------------------------------
#  GATHERING FACT
#---------------------------------
- name: "Gather facts on localhost"
  hosts: localhost
  become: no
  gather_facts: yes

#---------------------------------
#  SETUP NODES
#---------------------------------
- hosts: "baremetal"
  become: no
  gather_facts: no
  roles:
  
    # -----> B4 - SETUP 
    - role: "genesis.setup"
      when: 
      - (genesis_stage is not defined)  or  (genesis_stage=='B4')
      
    # -----> B5 - DEPLOY   
    - role: "genesis.deploy"
      when: 
      - (genesis_stage is not defined)  or  (genesis_stage=='B5')    

    # -----> B6 - PROVISION
    #- role: "genesis.provision"
    #  when: 
    #  - (genesis_stage is not defined)  or  (genesis_stage=='B6')          