---
# genesis playbooks/G1_refresh.yml
#   - Download Bifrost Dependencies
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0

- hosts: "target"
  become: true
  connection: local
  vars:
    bifrost_venv_dir: "{{ lookup('env', 'VENV') or '/opt/stack/bifrost' }}"
    genesis_repo_path: "{{ playbook_dir }}/../repo"      
  roles:
    - role: "genesis.bootstrap"
      when: 
      - not (skip_install | default(false) | bool)
      - (genesis_stage is not defined)  or  (genesis_stage=='G1') 