---
# genesis playbooks/G1_refresh.yml
#   - Download Bifrost Dependencies
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0

- hosts: "target"
  become: true
  connection: local
  vars:
    genesis_bifrost_path: "{{ bifrost_workpath | default( playbook_dir + '/../roles/genesis.bifrost' ) | realpath }}"
    genesis_files_path: "{{ bifrost_airgap_path | default( genesis_bifrost_path + '/files' ) }}"
  environment:
    PIP_DEST:  "{{genesis_files_path}}/pip"
    PIP_OPTS: " --download"
  roles:
    - role: "genesis.refresh"
      when: not (skip_install | default(false) | bool)