---
# genesis playbooks/create.yml
#  - Deploy Ironic
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0
#
- hosts: target
  become: yes
  gather_facts: yes
  vars:
    bifrost_venv_dir: "{{ lookup('env', 'VENV') or '/opt/stack/bifrost' }}"
    genesis_repo_path: "{{ playbook_dir }}/../repo"    
  
  #---------------------------------------
  # 1. Pre-Tasks: Prepare Bifrost Python Virtual Environment 
  #---------------------------------------    
  pre_tasks:
    - name: install pip (and venv) to system
      package:
        name: "{{ packages | select | list }}"
      vars:
        packages:
          - python3-pip
          - "{{ (ansible_facts['os_family'] == 'Debian') | ternary('python3-venv', '') }}"

    - name: create venv
      command: python3 -m venv {{ bifrost_venv_dir }}
      args:
        creates: "{{ bifrost_venv_dir }}/bin/python3"

    # NOTE(ebbex): (in case it's missing, which it shouldn't normally be)
    - name: install setuptools in venv
      command: "{{ bifrost_venv_dir }}/bin/pip3 install setuptools"
      args:
        creates: "{{ bifrost_venv_dir }}/lib/python*/site-packages/setuptools"

    - name: override ansible_python_interpreter to venv
      set_fact:
        ansible_python_interpreter: "{{ bifrost_venv_dir + '/bin/python3' }}"

  #---------------------------------------
  # 2. Tasks: Spawn & Init Genesis Node
  #---------------------------------------    
  roles:
    - role: "genesis.create"
      when: 
        - not (skip_install | default(false) | bool)
        - (genesis_stage is not defined)  or  (genesis_stage=='G2') 
    - role: "genesis.init"
      when: 
        - not (skip_install | default(false) | bool)
        - (genesis_stage is not defined)  or  (genesis_stage=='G3')          
 
  environment:
    http_proxy: "{{ lookup('env','http_proxy') }}"
    https_proxy: "{{ lookup('env','https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"