---
# genesis playbooks/create.yml
#  - Deploy Ironic
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0
#

#---------------------------------
# INSTALL STANDALONE IRONIC
#---------------------------------
- name: "STEP 1: Install Standalone Ironic in Genesis Node"
  ansible.builtin.import_playbook: "{{bifrost_shoot_path|trim}}/install.yaml"
  ignore_errors: yes
  vars:
    bifrost_shoot_path: >-
     {{ bifrost_playbooks_path
      | default(playbook_dir + '/../roles/openstack.bifrost/openstack.bifrost/playbooks', True)
      | realpath  }}
    create_image_via_dib: false

#---------------------------------
# SETUP STANDALONE IRONIC
#---------------------------------
- hosts: target
  become: true
  tasks:

    - name: "STEP 2 - SETUP IRONIC: adjust |/etc/ironic/ironic.conf|"
      ansible.builtin.lineinfile:
        path: /etc/ironic/ironic.conf
        regexp: "{{replace.regexp}}"
        line: "{{replace.line}}"
      loop:
        - regexp: '^automated_clean'
          line: 'automated_clean = false'
        - regexp: '^enabled_deploy_interfaces '
          line: 'enabled_deploy_interfaces = ramdisk,bootc,direct,anaconda'
      loop_control:
        loop_var: "replace"  
        
    #- name: "STEP 2 - SETUP IRONIC: add lines to |/etc/ironic/ironic.conf|"
    #  ansible.builtin.lineinfile:
    #    path: /etc/ironic/ironic.conf
    #    regexp: "{{replace.regexp}}"
    #    insertafter: "{{replace.regexp}}"
    #    line:        "{{replace.line}}"
    #  loop:
    #    - regexp: '[DEFAULT]'
    #      line: 'configdrive_format = iso9660'
    #    - regexp: '[agent]'
    #      line: 'require_agent_token = False'
    #  loop_control:
    #    loop_var: "replace"        
    
    - name: "STEP 3 - RESTART IRONIC: apply changes"
      service:
        name: ironic
        state: restarted
