---
# genesis playbooks/init.yml
#   - Load OS images
#
# SPDX-FileCopyrightText: © 2026 Genesis System 
# SPDX-License-Identifier: Apache-2.0
# 	

#---------------------------------
# COPY DOWNLOADED OS IMAGES
#---------------------------------
- hosts: target
  become: true
  ignore_errors: yes
  vars:
    default_repo_path: "{{ playbook_dir  }}/../repo"
    bifrost_repo_path: "{{ bifrost_airgap_path | default( default_repo_path ) | realpath }}"
    bifrost_dest_folder: 
      - "{{ironic_tftp_master_path | default('/var/lib/ironic/master_images') }}"
      - "{{http_boot_folder | default('/var/lib/ironic/httpboot') }}"
      - "{{bifrost_iso_folder | default('/var/lib/ironic/isos') }}"
  tasks:

    - name: "STEP 0: Detect Ironic Destination Folder"
      file: 
        path: "{{ dest_folder }}"
        state: "directory"
        recurse: yes
        owner: ironic
        group: ironic 
      loop: "{{bifrost_dest_folder | default([]) }}"
      loop_control:
        loop_var: "dest_folder"
      
    - name: "STEP 1: Copy Downloaded Files to Ironic Destination Folder"
      ansible.builtin.copy:
        src: "{{bifrost_repo_path | realpath}}/qcow/"
        dest: "{{ironic_tftp_master_path | default('/var/lib/ironic/master_images') }}/"

#---------------------------------------
# CREATE IMAGE  
#---------------------------------------
- name: "STEP 2: Build OS Bootable Images from local repository"
  hosts: target
  become: yes
  gather_facts: yes
  vars:
    bifrost_venv_dir: "{{ lookup('env', 'VENV') or '/opt/stack/bifrost' }}"
    bifrost_path: "{{ bifrost_workpath | default( playbook_dir + '/../roles/openstack.bifrost' ) | realpath }}"
    default_repo_path: "{{ playbook_dir  }}/../repo"
    bifrost_repo_path: "{{ bifrost_airgap_path | default( default_repo_path ) | realpath }}"
    bifrost_repo: "{{ bifrost_repo_path }}/dib"
    bifrost_roles: "{{bifrost_path}}/openstack.bifrost/playbooks/roles"
    bifrost_ironic_init: "{{bifrost_roles}}/bifrost-create-dib-image"
    #dib_offline: true
    build_ramdisk: false
    
  pre_tasks:
  
    - name: override ansible_python_interpreter to venv
      set_fact:
        ansible_python_interpreter: "{{ bifrost_venv_dir + '/bin/python3' }}"  

  roles: 
    - role: bifrost-create-dib-image
      dib_imagename: "{{bifrost_repo}}/ubuntu"
      dib_imagetype: "qcow2"
      dib_os_element: "ubuntu"
      dib_elements: >
              {{ dib_image_type|default('vm') }}
              {% if default_boot_mode != "bios" %}block-device-efi{% endif %}
              enable-serial-console
              {{ dib_init_element|default('simple-init') }}
              {{ extra_dib_elements|default('') }}


#  tasks:
#  
#     - name: "STEP 2 - Build OS Bootable Images from local repository"
#       ignore_errors: true      
#       block:  
#         - name: "STEP 2 - Build OS Bootable Images from local repository"         
#           ansible.builtin.include_role: 
#              name: "{{bifrost_ironic_init}}"
#           vars: 
#              #dib_env_vars:
#              #  http_proxy: "{{ lookup('env', 'http_proxy') }}"
#              #  https_proxy: "{{ lookup('env', 'https_proxy') }}"
#              #  DIB_IMAGE_CACHE: "{{bifrost_repo_path}}/qcow"
#              #  DIB_INSTALLTYPE_simple_init: repo
#              #  DIB_INSTALLTYPE_pip_and_virtualenv: package
#              #  LANG: C
#              #  LC_ALL: C
#              #  LC_MESSAGES: C
#              dib_image_name: "{{ os.image | basename | splitext | list }}"
#              dib_image_extension: "{{ dib_image_name[1] | default('') }}" 
#              dib_cloud_image_detection: "{{ dib_image_extension in ['.qcow','.qcow2'] }}"
#              dib_imagename: "{{bifrost_repo}}/{{os.distro}}-{{os.release}}"
#              dib_imagetype: "{{os.imagetype | default('qcow') }}"
#              dib_os_element: "{{os.distro}}"
#              dib_os_release: "{{os.release}}" 
#              #dib_init_element: "{{os.manifesto | default('simple-init') }}" 
#              dib_local_image_url: "{{deploy_image_sources[dib_os_element]['image']| default(omit) }}"
#              dib_elements: >
#                {{ dib_image_type|default('vm') }}
#                {% if default_boot_mode != "bios" %}block-device-efi{% endif %}
#                enable-serial-console
#                {{ dib_init_element|default('simple-init') }}
#                {{ extra_dib_elements|default('') }}
#           when: 
#              - dib_cloud_image_detection | bool
#           loop: "{{ bifrost_download_images | default([]) }}"
#           loop_control:
#              loop_var: "os"
       
       
  environment:
    http_proxy: "{{ lookup('env','http_proxy') }}"
    https_proxy: "{{ lookup('env','https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
    
#---------------------------------------
# LOAD CREATED IMAGES TO IRONIC
#---------------------------------------
- hosts: target
  become: true
  ignore_errors: yes
  vars:
    default_repo_path: "{{ playbook_dir  }}/../repo"
    bifrost_repo_path: "{{ bifrost_airgap_path | default( default_repo_path ) | realpath }}"
    bifrost_repo: "{{ bifrost_repo_path }}/dib"
  tasks:
      
    - name: "STEP 3: Copy Bootable OS Images to Ironic Destination Folder"
      ansible.builtin.copy:
        src: "{{bifrost_repo}}/"
        dest: "{{ironic_tftp_master_path | default('/var/lib/ironic/httpboot') }}/"
        
#---------------------------------------
# CREATE ISO REPOSITORIES
#---------------------------------------

