---
# genesis playbooks/init.yml
#   - Load OS images
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0
#
- ansible.builtin.import_playbook: "G2_create.yml"
  vars:
    genesis_stage: "G3"