---
# genesis playbooks/hypervisor.yml
#  - Preprare Hypervisor for Genesis deployment
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0

#---------------------------------
#  GATHERING FACT
#---------------------------------
- name: "Gather facts on localhost"
  hosts: localhost
  become: no
  gather_facts: yes
 
#---------------------------------
#  TEST NODES
#--------------------------------
- hosts: "hypervisor"
  become: no
  gather_facts: no
  pre_tasks:
    - name: "GENESIS API: Cast global string variables to native booleans"
      ansible.builtin.set_fact:
        genesis_hypervisor: "{{ target_hypervisor | default(inventory_name) | default('proxmox') }}"

  roles: 
    - role: "genesis.test"
      vars:
        genesis_hypervisor_node: "{{ groups['hypervisor'][0] | default('localhost') }}"