---
# genesis playbooks/init.yml
#   - Load OS images
#
# SPDX-FileCopyrightText: © 2026 Genesis System 
# SPDX-License-Identifier: Apache-2.0
# 	
- name: "Load OS Images into Ironic"
  hosts: target
  become: yes
  vars:
    bifrost_venv_dir: "{{ lookup('env', 'VENV') or '/opt/stack/bifrost' }}"
    bifrost_path: "{{ bifrost_workpath | default( playbook_dir + '/../roles/openstack.bifrost' ) }}"
    bifrost_repo: "{{ bifrost_airgap_path | default( bifrost_path + '/files' ) }}/dib"
    bifrost_roles: "{{bifrost_path}}/openstack.bifrost/playbooks/roles"
    bifrost_ironic_init: "{{bifrost_roles}}/bifrost-create-dib-image"
    #dib_offline: true
    build_ramdisk: false
    
  pre_tasks:
    - name: override ansible_python_interpreter to venv
      set_fact:
        ansible_python_interpreter: "{{ bifrost_venv_dir + '/bin/python3' }}"

  tasks:
     - name: "STEP 1 - Build OS Bootable Images from local repository"
       ignore_errors: true      
       vars:
          bifrost_ironic_init: "{{bifrost_roles}}/bifrost-create-dib-image"
          ironic_tftp_master_path: "{{ bifrost_airgap_path | default( bifrost_path + '/files' ) }}/qcow"
          #dib_offline: true
          #build_ramdisk: false
       block:  
         - name: "STEP 1 - Build OS Bootable Images from local repository"         
           ansible.builtin.include_role: 
              name: "{{bifrost_ironic_init}}"
           vars: 
              dib_imagename: "{{bifrost_repo}}/{{os.distro}}-{{os.release}}.qcow2"
              dib_imagetype: "{{os.imagetype | default('qcow') }}"
              dib_os_element: "{{os.distro}}"
              dib_os_release: "{{os.release}}" 
              dib_local_image_url: "{{deploy_image_sources[dib_os_element]['image']| default(omit) }}"
              dib_elements: >
                {{ dib_image_type|default('vm') }}
                {% if default_boot_mode != "bios" %}block-device-efi{% endif %}
                enable-serial-console
                {{ dib_init_element|default('simple-init') }}
                {{ extra_dib_elements|default('') }}
           
           loop: "{{ download_image_sources | default([]) }}"
           loop_control:
              loop_var: "os"
       
  environment:
    http_proxy: "{{ lookup('env','http_proxy') }}"
    https_proxy: "{{ lookup('env','https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
    
 