---
# genesis playbooks/prepareAirgap.yml
#   - Download Bifrost Dependencies 
#
# SPDX-FileCopyrightText: © 2026 Genesis System 
# SPDX-License-Identifier: Apache-2.0
#

######################################################
#  CREATE REPOSITORIES FOLDERS
######################################################
- hosts: "target"
  become: true
  connection: local
  tasks:
     # ----> Refresh Repo Folders
     - name: "STEP 1 - Create Repos Folders"
       vars:
          bifrost_path: "{{ bifrost_workpath | default( playbook_dir + '/../roles/openstack.bifrost' ) }}"
          files_path: "{{ bifrost_airgap_path | default( bifrost_path + '/files' ) }}"       
          repos: 
           - git
           - pip
           - qcow
           - ipa
           - dib
       block:
         - name: "STEP 0 - Create an ironic service group"
           group:
             name: "ironic"
        
         - name: "STEP 0 - Create an ironic service user"
           user:
             name: "ironic"
             group: "ironic"
      
         - name: "STEP 1 - Create Repos Folders"
           file:
              path: "{{ files_path | default('/tmp') }}/{{ folder| default('repo') }}"
              state: "directory"
              recurse: true
           loop: "{{ repos | default([]) }}"
           loop_control:
             loop_var: "folder"

######################################################
#  DOWNLOAD OPENSTACK COMPONENTS FROM GIT
######################################################
- hosts: "target"
  become: true
  connection: local
  vars:
    # 1.- Components Selection
    copy_from_local_path: false
    ironicclient_source_install: true
    openstacksdk_source_install: true
    ironicinspector_source_install: true
    ironicinspectorclient_source_install: true
    sushy_source_install: true
    staging_drivers_source_install: true
    prometheus_exporter_source_install: true
    enable_inspector: true
    enable_keystone: true
    enable_prometheus_exporter: true
    staging_drivers_include: true
 
     # 2.- Paths
    bifrost_path: "{{ bifrost_workpath | default( playbook_dir + '/../roles/openstack.bifrost' ) }}"
    files_path: "{{ bifrost_airgap_path | default( bifrost_path + '/files' ) }}"
    bifrost_roles: "{{bifrost_path}}/openstack.bifrost/playbooks/roles"
    git_root: "{{files_path}}/git"
    dib_git_url: https://opendev.org/openstack/diskimage-builder
    dib_git_folder: "{{git_root}}/{{dib_git_url | basename }}"
    ironicclient_git_url: https://opendev.org/openstack/python-ironicclient
    ironicclient_git_folder: "{{git_root}}/{{ironicclient_git_url | basename }}"
    openstacksdk_git_url: https://opendev.org/openstack/openstacksdk
    openstacksdk_git_folder: "{{git_root}}/openstacksdk"
    ironic_git_url: https://opendev.org/openstack/ironic
    ironic_git_folder: "{{git_root}}/{{ironic_git_url | basename }}"
    staging_drivers_git_url: https://opendev.org/x/ironic-staging-drivers
    staging_drivers_git_folder: "{{git_root}}/{{staging_drivers_git_url | basename }}"
    staging_drivers_git_branch: "0.11.0"
    ironicinspector_git_url: https://opendev.org/openstack/ironic-inspector
    ironicinspector_git_folder: "{{git_root}}/{{ironicinspector_git_url | basename }}"
    ironicinspectorclient_git_url: https://opendev.org/openstack/python-ironic-inspector-client
    ironicinspectorclient_git_folder: "{{git_root}}/{{ironicinspectorclient_git_url | basename }}"
    ipa_git_url: https://opendev.org/openstack/ironic-python-agent
    ipa_git_folder: "{{git_root}}/{{ipa_git_url | basename }}"
    ipa_builder_git_url: https://opendev.org/openstack/ironic-python-agent-builder
    ipa_builder_git_folder: "{{git_root}}/{{ipa_builder_git_url | basename }}"
    prometheus_exporter_git_url: https://opendev.org/openstack/ironic-prometheus-exporter
    prometheus_exporter_git_folder: "{{git_root}}/{{prometheus_exporter_git_url | basename }}"
    
  environment:
    PIP_DEST:  "{{files_path}}/pip" 
    PIP_OPTS: " --download"
  roles:
    - name: "STEP 2 - Download OpenStack Components from GIT"
      role: "{{bifrost_roles}}/bifrost-prep-for-install"
      when: not (skip_install | default(false) | bool)
    #- role: "{{bifrost_roles}}/bifrost-pip-install"
    #  when: not (skip_install | default(false) | bool)

######################################################
#  IPA AND OS IMAGES RESPOSITORIES
######################################################
- hosts: "target"
  become: true
  ignore_errors: true
  connection: local  
  vars:
     bifrost_path: "{{ bifrost_workpath | default( playbook_dir + '/../roles/openstack.bifrost' ) }}"
     files_path: "{{ bifrost_airgap_path | default( bifrost_path + '/files' ) }}"
     bifrost_roles: "{{bifrost_path}}/openstack.bifrost/playbooks/roles"
     bifrost_ironic_install: "{{bifrost_roles}}/bifrost-ironic-install"
     bifrost_venv_dir: "{{ lookup('env', 'VENV') or '/opt/stack/bifrost' }}"
     bifrost_repo: "{{ bifrost_airgap_path | default( bifrost_path + '/files' ) }}/dib"
     bifrost_roles: "{{bifrost_path}}/openstack.bifrost/playbooks/roles"     
     default_download_image_sources:
       - image: "https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img"
         checksum: "https://cloud-images.ubuntu.com/focal/current/SHA256SUMS"
         checksum_algorithm: "sha256"
         distro: "ubuntu"
         release: "focal"  
       - image: "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img"
         checksum: "https://cloud-images.ubuntu.com/jammy/current/SHA256SUMS"
         checksum_algorithm: "sha256"
         distro: "ubuntu"
         release: "jammy"                
       - image: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img"
         checksum: "https://cloud-images.ubuntu.com/noble/current/SHA256SUMS"
         checksum_algorithm: "sha256"
         distro: "ubuntu"
         release: "noble"               
       - image: "https://dl.rockylinux.org/pub/rocky/8/images/x86_64/Rocky-8-GenericCloud.latest.x86_64.qcow2"
         checksum: "https://dl.rockylinux.org/pub/rocky/8/images/x86_64/CHECKSUM"
         checksum_algorithm: "sha256"
         distro: "rocky"
         release: "8" 
       - image: "https://dl.rockylinux.org/pub/rocky/9/images/x86_64/Rocky-9-GenericCloud.latest.x86_64.qcow2"
         checksum: "https://dl.rockylinux.org/pub/rocky/9/images/x86_64/CHECKSUM"
         checksum_algorithm: "sha256"
         distro: "rocky"
         release: "9"              
       - image: "https://dl.rockylinux.org/pub/rocky/10/images/x86_64/Rocky-10-GenericCloud-Base.latest.x86_64.qcow2"
         checksum: "https://dl.rockylinux.org/pub/rocky/10/images/x86_64/CHECKSUM"
         checksum_algorithm: "sha256"
       - image: "https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2"
         checksum: "https://cloud.centos.org/centos/9-stream/x86_64/images/CHECKSUM"
         checksum_algorithm: "sha256"
         distro: "centos"
         release: "9-stream"
       - image: "https://cloud.centos.org/centos/10-stream/x86_64/images/CentOS-Stream-GenericCloud-10-latest.x86_64.qcow2"
         checksum: "https://cloud.centos.org/centos/10-stream/x86_64/images/CHECKSUM"
         checksum_algorithm: "sha256"
         distro: "centos"
         release: "10-stream"
       - image: "{{ cirros_deploy_image_upstream_url | default('https://download.cirros-cloud.net/0.5.3/cirros-0.5.3-x86_64-disk.img') }}"
         checksum: "https://download.cirros-cloud.net/0.5.3/MD5SUMS"
         checksum_algorithm: "md5"
         distro: "cirros"
         release: "0.5.3"
     download_image_sources: "{{ bifrost_download_images | default(default_download_image_sources) | default([]) }}" 
     
  tasks:

     # ----> Download QCOW Images 
     - name: "STEP 3 - Download OS Cloud Ready images"
       vars:
          create_ipa_image: false
          #download_ipa_image: true
          #download_custom_deploy_image: true
    
       block:   
         - name: "STEP 3 - Download OS Cloud Ready images"
           include_tasks: "{{bifrost_ironic_install}}/tasks/download_deployment_image.yml"
           loop: "{{ download_image_sources | default([]) }}"
           loop_control:
              loop_var: "image_src"
           vars:
              deploy_image_upstream_url: "{{ image_src.image | default('') }}"
              deploy_image_checksum_url: "{{ image_src.checksum | default('') }}"
              deploy_image_checksum_algorithm: "{{ image_src.checksum_algorithm | default('') }}"
              deploy_image_filename: "{{ image_src.image | basename }}"
              http_boot_folder: "{{ files_path }}/qcow"
              deploy_image: "{{http_boot_folder}}/{{ image_src.image | basename }}"
              
      # ----> Download IPA Images
     - name: "STEP 4 - Download IPA images"
       vars:
          update_ipa: true
          ipa_image_sources:
            - kernel: "https://tarballs.opendev.org/openstack/ironic-python-agent/dib/files/ipa-debian-master.kernel"
              kernel_checksum_url: "https://tarballs.opendev.org/openstack/ironic-python-agent/dib/files/ipa-debian-master.kernel.sha256"
              kernel_checksum_algo: "sha256"
              ramdisk: "https://tarballs.opendev.org/openstack/ironic-python-agent/dib/files/ipa-debian-master.initramfs"
              ramdisk_checksum_url: "https://tarballs.opendev.org/openstack/ironic-python-agent/dib/files/ipa-debian-master.initramfs.sha256"
              ramdisk_checksum_algo: "sha256"  
            
            - kernel: "https://tarballs.opendev.org/openstack/ironic-python-agent/dib/files/ipa-centos9-master.kernel"
              kernel_checksum_url: "https://tarballs.opendev.org/openstack/ironic-python-agent/dib/files/ipa-centos9-master.kernel.sha256"
              kernel_checksum_algo: "sha256"
              ramdisk: "https://tarballs.opendev.org/openstack/ironic-python-agent/dib/files/ipa-centos9-master.initramfs"
              ramdisk_checksum_url: "https://tarballs.opendev.org/openstack/ironic-python-agent/dib/files/ipa-centos9-master.initramfs.sha256"
              ramdisk_checksum_algo: "sha256"             
       block:         
         - name: "STEP 4 - Download IPA images"
           include_tasks: "{{bifrost_ironic_install}}/tasks/download_ipa_image.yml"
           loop: "{{ ipa_image_sources | default([]) }}"
           loop_control:
              loop_var: "ipa_src"
           vars:
              ipa_kernel_upstream_url: "{{ ipa_src.kernel | default('') }}"
              ipa_kernel_upstream_checksum_url: "{{ ipa_src.kernel_checksum_url | default('') }}"
              ipa_kernel_upstream_checksum_algo: "{{ ipa_src.kernel_checksum_algo | default('') }}"
              ipa_ramdisk_upstream_url: "{{ ipa_src.ramdisk | default('') }}"
              ipa_ramdisk_upstream_checksum_url: "{{ ipa_src.ramdisk_checksum_url | default('') }}"
              ipa_ramdisk_upstream_checksum_algo: "{{ ipa_src.ramdisk_checksum_algo | default('') }}"          
              ipa_kernel: "{{ files_path }}/ipa/{{ ipa_kernel_upstream_url | basename }}"
              ipa_ramdisk: "{{ files_path }}/ipa/{{ ipa_ramdisk_upstream_url | basename }}"
           when: update_ipa | bool             
