---
# genesis playbooks/provision.yml
#   - Subsystem OS Provisioning: drivers and services
#
# SPDX-FileCopyrightText: © 2026 Genesis System 
# SPDX-License-Identifier: Apache-2.0
# 	
- ansible.builtin.import_playbook: "{{bifrost_playbooks_path }}/install.yaml"
  become: true
  vars:
    bifrost_playbooks_path: "{{ playbook_dir }}/../roles/openstack.bifrost/openstack.bifrost/playbooks"
    create_image_via_dib: false  
