---
# genesis playbooks/setup.yml
#  - Enroll inventory to Ironic
#
# SPDX-FileCopyrightText: © 2026 Genesis System 
# SPDX-License-Identifier: Apache-2.0

#---------------------------------
#  CLEAN IRONIC 
#---------------------------------
- name: "STEP 1 - Remove Nodes"
  hosts: localhost
  connection: local
  ignore_errors: yes
  vars:
    work_path: "{{ playbook_dir }}/../hosts"
    bifrost_default_inventory_source: "{{ work_path | realpath }}/baremetal.yml"
    bifrost_repo_path: "{{ playbook_dir }}/../repo"
    bifrost_inventory_source: "{{ lookup('env', 'BIFROST_INVENTORY_SOURCE') or bifrost_default_inventory_source }}"
    
  tasks:

    - name: "Load Nodes to Enroll from |{{ bifrost_inventory_source }}|"
      ansible.builtin.include_vars: 
         file: "{{ bifrost_inventory_source }}"
         name: "baremetal_nodes_enrolled"       
 
    - name: "STEP 1 - Remove Nodes"
      shell:
         cmd: "{{command | default('ls')}}"
      vars:
         node_uuid: "{{ node.value.uuid | default(' ') }}" 
         node_name: "{{ node.value.name | default(' ') }}"         
         command: |
           . /opt/stack/bifrost/bin/activate 
           export OS_CLOUD=bifrost
           baremetal allocation delete {{node_name}} 
           baremetal node set --retired {{node_uuid}}
           baremetal node maintenance set {{node_uuid}}
           baremetal node delete {{node_uuid}}           
      loop:  "{{ baremetal_nodes_enrolled | dict2items | default([]) }}"
      loop_control:
        loop_var: node 
  

#---------------------------------
#  ENROLL NODES
#---------------------------------
- name: "STEP 2 - Enroll Nodes"
  ansible.builtin.import_playbook: "{{bifrost_shoot_path | trim}}/enroll-dynamic.yaml"
  become: true
  vars: 
    bifrost_shoot_path: >-
     {{ bifrost_playbooks_path 
      | default(playbook_dir + '/../roles/openstack.bifrost/openstack.bifrost/playbooks', True)       
      | realpath  }}


#---------------------------------
#  SET INSTANCE INFORMATION 
#---------------------------------
- name: "STEP 3 - Set Instance Information"
  hosts: localhost
  connection: local
  vars:
    work_path: "{{ playbook_dir }}/../hosts"
    bifrost_default_inventory_source: "{{ work_path | realpath }}/baremetal.yml"
    bifrost_repo_path: "{{ playbook_dir }}/../repo"
    bifrost_inventory_source: "{{ lookup('env', 'BIFROST_INVENTORY_SOURCE') or bifrost_default_inventory_source }}"
    
  tasks:
    
    - name: "Load Nodes Enrolled from |{{ bifrost_inventory_source }}|"
      ansible.builtin.include_vars: 
         file: "{{ bifrost_inventory_source }}"
         name: "baremetal_nodes_enrolled"       
     
    - name: "STEP 3 - Set Instance Information"
      shell:
         cmd: "{{command | default('ls')}}"
      vars:
         node_uuid: "{{ node.value.uuid | default(' ') }}" 
         node_name: "{{ node.value.name | default(' ') }}"         
         node_image_source: "{{ node.value.instance_info.image_source | default('') }}"
         node_image_source_name: "{{node_image_source | basename | default('')}}"
         node_image_source_localpath: "{{bifrost_repo_path|realpath}}/dib/{{node_image_source_name}}"
         node_boot_iso: "{{ node.value.instance_info.boot_iso |  default('') }}"
         node_ks_template: "{{ node.value.instance_info.ks_template |  default('default.ks') }}" 
         node_boot_interface: "{{ node.value.instance_info.boot_interface |  default('ipxe') }}"
         node_deploy_interface: "{{ node.value.instance_info.deploy_interface |  default('direct') }}"
         node_command_iso_type: "{{ ( node_boot_iso | length ) > 1 }}"
         allocation_command: |
           . /opt/stack/bifrost/bin/activate 
           export OS_CLOUD=bifrost
           baremetal allocation delete {{node_name}}     
           baremetal allocation create --name {{node_name}} --resource-class baremetal --wait
           baremetal node set {{node_uuid}} --boot-interface {{node_boot_interface}}
           baremetal node set {{node_uuid}} --deploy-interface {{node_deploy_interface}}        
         instance_command: |
           HASH=$( sha256sum {{node_image_source_localpath}} )
           baremetal node set {{node_uuid}} --instance-info image_source="{{node_image_source}}" 
           baremetal node set {{node_uuid}} --instance-info image_os_hash_value="${HASH%% *}" 
           baremetal node set {{node_uuid}} --instance-info image_os_hash_algo="sha256"  
         
         iso_command: |
           baremetal node set {{node_name}} --instance-info boot_iso="{{node_boot_iso}}"
           baremetal node set {{node_name}} --instance-info ks_template="{{node_ks_template}}"           
         shoot_command: "{{ (node_command_iso_type | bool) |  ternary(iso_command,instance_command) }}"
         status_command: |       
           baremetal node validate {{node_name}}
         command: |
           {{ allocation_command }}
           {{ shoot_command }}
           {{ status_command }}
      loop:  "{{ baremetal_nodes_enrolled | dict2items | default([]) }}"
      loop_control:
        loop_var: node

#---------------------------------
#  IPA INSTALLATION MANIFESTO 
#---------------------------------
- name: "STEP 4 - IPA Installation Manifesto (kickstart, cloud-init, ignition)"
  hosts: localhost
  connection: local
  vars:
    work_path: "{{ playbook_dir }}/../hosts"
    bifrost_default_inventory_source: "{{ work_path | realpath }}/baremetal.yml"
    bifrost_repo_path: "{{ playbook_dir }}/../repo"
    bifrost_inventory_source: "{{ lookup('env', 'BIFROST_INVENTORY_SOURCE') or bifrost_default_inventory_source }}"
    
  tasks:
    
    - name: "Load Nodes Enrolled from |{{ bifrost_inventory_source }}|"
      ansible.builtin.include_vars: 
         file: "{{ bifrost_inventory_source }}"
         name: "baremetal_nodes_enrolled"    

 #   - name: 
         

#- name: "STEP 4 - Create configuration drive files and deploy machines from inventory"
#  hosts: baremetal
#  become: no
#  connection: local
#  roles:
#    - role: bifrost-configdrives-dynamic
#      when:
#        - provision_state == "available"
#        - maintenance | bool   

  # -> Environment do not work for import_playbook => You must set at shooting bash script command
  # -> Keeping the syntax, just in case  
  #---------------------------------------------------------------  
  #  bifrost_inventory_path: >-
  #    {{ ( bifrost_inventory_source | dirname )
  #    | default(inventory_path, True)       
  #    | realpath  }}     
  #  bifrost_dynamic_inventory_path: >-
  #    {{ ( bifrost_dynamic_inventory | dirname )
  #    | default(playbook_dir + '/../openstack.bifrost/bifrost/, True)       
  #    | realpath  }} 
  #environment:
  #  ANSIBLE_INVENTORY: >-
  #   {{ bifrost_dynamic_inventory 
  #    | default( bifrost_dynamic_inventory_path + '/inventory.py', True) }}  
  #  BIFROST_INVENTORY_SOURCE: "{{ bifrost_inventory_source | default( bifrost_inventory_path + '/group_vars.yml' )}}"
  #  OS_CLOUD: "{{ bifrost_cloud | default('bifrost') }}"
  #---------------------------------------------------------------
  # -> EnvironmentDo not work for import_playbook => You must set at shooting bash script command
  # -> Keeping the syntax, just in case  
  #--------------------------------------------------------------- 