---
# genesis playbooks/test.yml
#  - Baremetal Nodes Life Cycle Certification Testing
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0

#---------------------------------
# PREPARE GENESIS NODE
#--------------------------------
- import_playbook: "genesis.yml"

#---------------------------------
#  GATHERING FACT
#---------------------------------
- name: "Gather facts on localhost"
  hosts: localhost
  become: no
  gather_facts: yes
 

#---------------------------------
#  CLEAN IRONIC INSTANCE INFORMATION
#--------------------------------
- hosts: "baremetal"
  become: no
  gather_facts: no 
  roles: 
    - role: "genesis.setup"
      vars:
        b4_skip_setup: yes
        uuid: "{{ enroll.uuid }}" 

#---------------------------------
#  TEST NODES
#--------------------------------
- hosts: "baremetal"
  become: no
  gather_facts: no
  pre_tasks:
    - name: "GENESIS API: Cast global string variables to native booleans"
      ansible.builtin.set_fact:
        genesis_refresh_environment: "{{ genesis_refresh_testenv | default(false) | bool }}"
  roles: 
    - role: "genesis.test"
      vars:
        genesis_hypervisor: "proxmox"
        genesis_hypervisor_node: "{{ groups['hypervisor'][0] | default('localhost') }}"
