---
# genesis playbooks/test.yml
#  - Baremetal Nodes Life Cycle Certification Testing
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0

#---------------------------------
#  GATHERING FACT
#---------------------------------
- name: "Gather facts on localhost"
  hosts: localhost
  become: no
  gather_facts: yes
 
#---------------------------------
#  TEST NODES
#---------------------------------
- hosts: "baremetal"
  become: no
  gather_facts: no
  roles: 
    - role: "genesis.test"
      vars:
        genesis_hypervisor: "proxmox"
        genesis_hypervisor_node: "{{ groups['hypervisor'][0] | default('localhost') }}"
