---
# genesis.test 4_nodes.yml
#   - Create Airgap Zone
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0

#-----------------------------------------------------------------------
# 1.- Refresh Testing Virtual Machine
#-----------------------------------------------------------------------
- block:
    - ansible.builtin.include_tasks: "4_nodes/{{ t1_hypervisor }}_instance.yml"
      vars:
        t4_vm_state: "absent"
    - ansible.builtin.include_tasks: "4_nodes/{{ t1_hypervisor }}_instance.yml"
      vars:
        t4_vm_state: "present"
  when:
    - t1_refresh_vms | default(true) | bool