---
# genesis.test main.yml
#   - Set Hypervisor Conditions
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0

#-----------------------------------------------------------------------
# 1.- Create Bundle of Virtual Machines
#-----------------------------------------------------------------------
- vars: 
    ansible_user: "{{ t1_hypervisor_user }}"
  block:
    - ansible.builtin.include_tasks: "environment.yml"
  when:
    - t1_hypervisor_node is defined
    - t1_hypervisor_node is not none
    - t1_refresh_environment is defined
    - t1_refresh_environment is not none
    - t1_refresh_environment

#-----------------------------------------------------------------------
# 2.- Run Stage Tests
#-----------------------------------------------------------------------
- block:
    - ansible.builtin.include_role: 
        name: "genesis.setup"
    - ansible.builtin.include_role: 
        name: "genesis.deploy"