---
# genesis.test main.yml
#   - Set Hypervisor Conditions
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0

#-----------------------------------------------------------------------
# 1.- Create Emulation Environment on Hypervisor
#-----------------------------------------------------------------------
- ansible.builtin.include_tasks: "emulation.yml"

#-----------------------------------------------------------------------
# 2.- Run Baremetal Certification Tests
#-----------------------------------------------------------------------
- block:
    - ansible.builtin.include_role: 
        name: "genesis.setup"
    - ansible.builtin.include_role: 
        name: "genesis.deploy"
  when:
    - not (t1_skip_tests | default(false) | bool)