---
# genesis.init defaults
#   - Setup PXE Services
#
# SPDX-FileCopyrightText: © 2026 Genesis System
# SPDX-License-Identifier: Apache-2.0
#

######################################################
#  GENESIS PATHS (global for update all genesis roles at once)
######################################################
# 1.- Repos Paths
genesis_repo_path: "{{ role_path | dirname | dirname | realpath }}/repo"
genesis_local_repo_url: "file://{{ genesis_repo_path | realpath }}"

# 2.- Bifrost Role Paths
genesis_bifrost_role_name: "genesis.bifrost"
genesis_bifrost_path: "{{ role_path | dirname }}/{{ genesis_bifrost_role_name }}"
genesis_bifrost_roles: "{{ genesis_bifrost_path | realpath }}/{{ genesis_bifrost_role_name }}/playbooks/roles"
genesis_bifrost_files_path: "{{ genesis_bifrost_path | realpath }}/files"
genesis_bifrost_ironic_init: "{{ genesis_bifrost_roles | realpath }}/bifrost-create-dib-image"
genesis_bifrost_dest_folder:
  - "{{ ironic_tftp_master_path | default('/var/lib/ironic/master_images') }}"
  - "{{ http_boot_folder | default('/var/lib/ironic/httpboot') }}"
  - "{{ bifrost_iso_folder | default('/var/lib/ironic/isos') }}"
genesis_bifrost_ironic_install: "{{ genesis_bifrost_roles }}/bifrost-ironic-install"
genesis_bifrost_venv_dir: "{{ lookup('env', 'VENV') or '/opt/stack/bifrost' }}"

# 3.- Repositories
genesis_default_repos:
  os: "os"
  manifesto: "manifesto" 
  components: "openstack"
  cloud: "dib"
  ipa: "dib/files" 
  repo: "mnt"
 
genesis_default_os_image_name:
  qcow: "partition.qcow"
  qcow2: "partition.qcow2"
  img: "partition.img"
  raw: "wholedisk.raw" 
  iso: "netboot.iso"
  
######################################################
# G3 - PARTICULARS
######################################################
# 1.- Paths
g3_repos: "{{ genesis_airgap_repos | default(genesis_default_repos) }}" 
g3_repo_os_path: "{{ genesis_repo_path | realpath }}/{{ g3_repos['os'] | default('os') }}"
g3_repo_components_path: "{{ genesis_repo_path | realpath }}/{{ g3_repos['components'] | default('openstack') }}"
g3_repo_dib_path: "{{ genesis_repo_path | realpath }}/{{ g3_repos['cloud'] | default('dib') }}"
g3_repo_mount_path: "{{ genesis_repo_path | realpath }}/{{ g3_repos['repo'] | default('mnt') }}"
g3_tftp_path: "{{ genesis_tftp_path | default(ironic_tftp_master_path) | default('/var/lib/tftpboot') | realpath }}"
g3_http_path: "{{ genesis_http_path | default(http_boot_folder) | default('/var/lib/ironic/httpboot') | realpath }}"
g3_mount_repo_path: "{{ genesis_repo_mount_path | default(g3_repo_mount_path) | default('/mnt') | realpath }}"

# 2.- URL
g3_local_checksum_url: "file://{{ genesis_repo_path | realpath }}/checksum"

# 3.- Users
g3_webserver_user: "{{ genesis_werserver_user | default('www-data') }}"
g3_webserver_group: "{{ genesis_werserver_group | default('www-data') }}"
g3_groups_webserver_group: "{{ ansible_user }},{{ g3_webserver_group }},adm,cdrom,sudo,dip,plugdev,lxd,ironic" 
g3_iso_mount_properties: "loop,ro,uid={{ g3_webserver_user }},gid={{ g3_webserver_group }},mode=0755"

# 4.- Webserver Update
g3_node_default_os: "{{ genesis_node_default_os | default('CentOS') }}"
g3_node_default_os_version: "{{ genesis_node_default_version | default('9') }}"
g3_setup_webserver:
  - file: "/etc/nginx/conf.d/bifrost-httpboot.conf"
    regexp: '^\s*disable_symlinks\s+'
    line: '        disable_symlinks off;'
    insertafter: 'server {'
  - file: "/etc/nginx/conf.d/bifrost-httpboot.conf"
    regexp: '^\s*autoindex\s+'
    line: '        autoindex on;'
    insertafter: 'server {'
  
######################################################
#  G3 - OS IMAGES RESPOSITORIES
######################################################
g3_extract_os_installer:
  centos:
    - src: "images/pxeboot/vmlinuz"
      dest: "vmlinuz"
    - src: "images/pxeboot/initrd.img"
      dest: "initrd"
    - src: "images/install.img"
      dest: "install.img"
  redhat:
    - src: "images/pxeboot/vmlinuz"
      dest: "vmlinuz"
    - src: "images/pxeboot/initrd.img"
      dest: "initrd"
    - src: "images/install.img"
      dest: "install.img" 
  rocky:
    - src: "images/pxeboot/vmlinuz"
      dest: "vmlinuz"
    - src: "images/pxeboot/initrd.img"
      dest: "initrd"
    - src: "images/install.img"
      dest: "install.img" 
  ubuntu:
    - src: "casper/vmlinuz"
      dest: "vmlinuz"
    - src: "casper/initrd"
      dest: "initrd"	
  debian:
    - src: "install.amd/vmlinuz"
      dest: "vmlinuz"	
    - src: "install.amd/initrd.gz"
      dest: "initrd"
  suse: 
    - src: "boot/x86_64/loader/linux"
      dest: "vmlinuz"
    - src: "boot/x86_64/loader/initrd"
      dest: "initrd"
    - src: "LiveOS/squashfs.img"
      dest: "install.img"
  suse_old: 
    - src: "boot/x86_64/loader/linux"
      dest: "vmlinuz"
    - src: "boot/x86_64/loader/initrd"  
      dest: "initrd"   
    - src: "boot/x86_64/root"
      dest: "root"        

g3_native_os_installer:

   #- distribution: "Rocky"
   # distribution_version: "8"
   # os_image_name: "x86_64.iso"
   # image: "https://download.rockylinux.org/pub/rocky/8/isos/x86_64/Rocky-8.10-x86_64-dvd1.iso"
   # checksum: "https://download.rockylinux.org/pub/rocky/8/isos/x86_64/CHECKSUM"
   # checksum_algorithm: "sha256"
   # extract_ramdisk: yes
   # mount: yes

  - distribution: "CentOS"
    distribution_version: "9"
    os_image_name: "x86_64.iso"
    image: "https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/iso/CentOS-Stream-9-latest-x86_64-dvd1.iso"
    checksum: "https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/iso/CentOS-Stream-9-latest-x86_64-dvd1.iso.SHA256SUM"
    checksum_algorithm: "sha256"
    extract_ramdisk: yes
    mount: yes

  - distribution: "Ubuntu"
    distribution_version: "24.04"
    os_image_name: "x86_64.iso"
    image: "https://releases.ubuntu.com/noble/ubuntu-24.04.4-live-server-amd64.iso"
    checksum: "https://releases.ubuntu.com/noble/SHA256SUMS"
    checksum_algorithm: "sha256"
    extract_ramdisk: yes

  - distribution: "CoreOS"
    distribution_version: "44"
    os_image_name: "x86_64.iso"  
    image: "https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/44.20260707.3.1/x86_64/fedora-coreos-44.20260707.3.1-live-iso.x86_64.iso"
    checksum: "{{ g3_local_checksum_url }}"
    checksum_algorithm: "sha256"      

  - distribution: "CoreOS"
    distribution_version: "44"
    os_image_name: "vmlinuz"
    image: "https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/44.20260707.3.1/x86_64/fedora-coreos-44.20260707.3.1-live-kernel.x86_64"
    checksum: "{{ g3_local_checksum_url }}"
    checksum_algorithm: "sha256"

  - distribution: "CoreOS"
    distribution_version: "44"
    os_image_name: "initramfs" 
    image: "https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/44.20260707.3.1/x86_64/fedora-coreos-44.20260707.3.1-live-initramfs.x86_64.img"
    checksum: "{{ g3_local_checksum_url }}"
    checksum_algorithm: "sha256"

  - distribution: "CoreOS"
    distribution_version: "44"
    os_image_name: "install.img" 
    image: "https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/44.20260802.3.1/x86_64/fedora-coreos-44.20260802.3.1-live-rootfs.x86_64.img"
    checksum: "{{ g3_local_checksum_url }}"
    checksum_algorithm: "sha256"
    
g3_cloud_os_installer:
  - distribution: "CentOS"
    distribution_version: "9"
    os_image_name: "partition.qcow2"
    image: "https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2"
    checksum: "https://cloud.centos.org/centos/9-stream/x86_64/images/CHECKSUM"
    checksum_algorithm: "sha256"

# Using bifrost internal variable name
genesis_installers_download: "{{ g3_native_os_installer + g3_cloud_os_installer }}"
download_image_sources: "{{ genesis_download_images | default(genesis_installers_download) | default([]) }}"

######################################################
#  G3 - HTTP EXPOSURE DETAILS
######################################################
# HTTP Paths particulars    
g3_base_path: "{{ genesis_repo_path | default('../../../repo') | realpath }}"
g3_base_list_subfolders_base_path: >-
  {%- set partes = g3_base_path.split('/') | select('string') | list -%}
  {%- set lista = [] -%}
  {%- for i in range(1, partes | length + 1) -%}
    {%- set _ = lista.append('/' ~ partes[:i] | join('/')) -%}
  {%- endfor -%}
  {{ lista }}
g3_os_images_repo_path: "{{ g3_base_path | realpath }}/{{ g3_repos['os'] | default('os') }}"
g3_os_images_http_path: "{{ g3_http_path | realpath }}/{{ g3_repos['os'] | default('os') }}" 
g3_cloud_images_repo_path: "{{ g3_base_path | realpath }}/{{ g3_repos['cloud'] | default('dib') }}"
g3_cloud_images_http_path: "{{ g3_http_path    | realpath }}/{{ g3_repos['cloud'] | default('dib') }}"     
g3_mnt_repo_path: "{{ g3_base_path | realpath }}/{{ g3_repos['repo'] | default('mnt') }}"
g3_mnt_http_path: "{{ g3_http_path    | realpath }}/{{ g3_repos['repo'] | default('mnt') }}"       
g3_manifesto_repo_path: "{{ g3_base_path | realpath }}/{{ g3_repos['manifesto'] | default('manifesto') }}"
g3_manifesto_http_path: "{{ g3_http_path }}/{{ g3_repos['manifesto'] | default('manifesto') }}"  
g3_paths_to_expose:
  - repo:   "{{ g3_manifesto_repo_path }}"  
    expose: "{{ g3_manifesto_http_path }}"
  - repo:   "{{ g3_os_images_repo_path }}"
    expose: "{{ g3_os_images_http_path }}"
  - repo:   "{{ g3_cloud_images_repo_path }}"
    expose: "{{ g3_cloud_images_http_path }}"
  - repo:   "{{ g3_mnt_repo_path }}"
    expose: "{{ g3_mnt_http_path }}"